### ISSUE TITLE
bdr_init_copy doesn't clear seqam cache

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#101]
`bdr_init_copy` doesn't clear values in `bdr` global sequence's cache of current values in the seqam amdata. This can lead to duplicate sequence values after a node copy.

**Comment by ringerc** [comment]
As a workaround, all `bdr` sequences can be consumed and forced to advance. This works because we `ERROR` when we have to allocate a new sequence chunk. Something like:

```
DO
$$
DECLARE
    seqinfo record;
BEGIN
    FOR seqinfo IN 
        SELECT c.oid
        from pg_class c
        inner join pg_namespace n on (c.relnamespace = n.oid)
        inner join pg_seqam s on (c.relam = s.oid) 
        where relkind = 'S'  and n.nspname not in ('bdr', 'information_schema', 'pg_catalog') and seqamname = 'bdr'
    LOOP
        BEGIN
            PERFORM nextval(seqinfo.oid::regclass) from generate_series(1,10000);
        EXCEPTION
          WHEN serialization_failure THEN
            RAISE NOTICE '%', format('Sequence %I advanced', seqinfo.oid::regclass);
        END;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
```

**Comment by anarazel** [comment]
On 2015-06-29 02:16:38 -0700, Craig Ringer wrote:
> As a workaround, all `bdr` sequences can be consumed and forced to
> advance. This works because we `ERROR` when we have to allocate a new
> sequence chunk. Something like:

That's far to agressive tho - afaics only the blocks stored in the
sequence itself need to be reset. Everything else doesn't?

**Comment by PJMODOS** [comment]
Yes only the amdata needs to be cleared, actually it could just be set to NULL as we check for that in fill method. The above is just quick and dirty workaround as clearing amdata needs C coding.
