### ISSUE TITLE
Command filter should ignore DML to pg_catalog

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#102]
Since we don't replicate changes made to `pg_catalog` tables we should skip the executor hook check for `PRIMARY KEY` on DML against `pg_catalog`.

(If we don't already, we should also skip it while other extension's scripts are running, haven't checked).

**Comment by anarazel** [comment]
> Since we don't replicate changes made to `pg_catalog` tables we should skip the executor hook check for `PRIMARY KEY` on DML against `pg_catalog`.

What's the use case for that? I mean, I don't really mind, it'd be easy
to integrate and all, but what's the point?

**Comment by ringerc** [comment]
What prompted this note was me trying to clear the seqam cache by setting
`amdata` to `null` as a workaround for #101 . Which didn't work because of
the executor filter.

It also prevents directly updating `pg_trigger` to set existing triggers to
#62, which I think is likely cleaner than dropping and re-creating them.

**Comment by PJMODOS** [comment]
Well all it prevents are ugly solutions to problems, but I still think we should have this for correctness (and for quick workarounds on live sites perhaps if needed).
