### ISSUE TITLE
Frozen: Initializing BDR on the local node

### ISSUE THREAD

**Issue by pape-io** [2ndQuadrant/bdr#106]
Running bdr_init_copy freezes.

[VERSION on BOTH NODES]
```
SELECT bdr.bdr_version();
    bdr_version    
-------------------
 0.9.1-2015-05-26-
(1 row)
```

[NODE2]
```
/usr/lib/postgresql/9.4/bin/bdr_init_copy -D /var/lib/postgresql/9.4/main -n NAME -d "host=NODE1 dbname=DBNAME port=5432 user=postgres" --local-dbname="host=NODE2 dbname=DBNAME port=5432 user=postgres"
```

[NODE2]
```
bdr_init_copy: starting ...
Getting remote server identification ...
Detected 1 BDR database(s) on remote server
Updating BDR configuration on the remote node:
 DBNAME: validating BDR configuration ...
 DBNAME: creating replication slot ...
 DBNAME: creating node entry for local node ...
Creating restore point on remote node ...
Bringing local node to the restore point ...
pg_ctl: another server might be running; trying to start server anyway
Transaction log reset
Initializing BDR on the local node:
```

No logs in `postgresql-9.4-main.log` for [NODE2].

[NODE1] Logs
```
2015-07-03 17:20:52 UTC LOG:  logical decoding found consistent point at 0/1F000028
2015-07-03 17:20:52 UTC DETAIL:  There are no running transactions.
2015-07-03 17:20:52 UTC STATEMENT:  SELECT pg_create_logical_replication_slot('bdr_19068_6167332740252040116_2_19068__', 'bdr');
2015-07-03 17:20:52 UTC LOG:  restore point "bdr_6167332740252040116" created at 0/1F0002F8
2015-07-03 17:20:52 UTC STATEMENT:  SELECT pg_create_restore_point('bdr_6167332740252040116')
```

[NODE1] Replication Slots
```
SELECT * FROM pg_replication_slots ;
                slot_name                | plugin | slot_type | datoid | database | active | xmin | catalog_xmin | restart_lsn 
-----------------------------------------+--------+-----------+--------+----------+--------+------+--------------+-------------
 bdr_19068_6167332740252040116_2_19068__ | bdr    | logical   |  19068 | DBNAME  | f      |      |         1880 | 0/1F000028
(1 row)
```

[NODE1] BDR Nodes
```
SELECT * FROM bdr.bdr_nodes;
node_sysid      | node_timeline | node_dboid | node_status | node_name |                   node_local_dsn                   |                        node_init_from_dsn                        
---------------------+---------------+------------+-------------+-----------+----------------------------------------------------+------------------------------------------------------------------
 6167310327656349802 |             1 |      19068 | r           | sb        | host=NODE1 port=5432 dbname=DBNAME | 
 6167332740252040116 |             2 |      19068 | c           | FK        |                                                    | user=postgres dbname=DBNAME host=NODE1 port=5432
```

[NODE1] BDR Connections
```
SELECT * FROM bdr.bdr_connections;
 conn_sysid      | conn_timeline | conn_dboid | conn_origin_sysid | conn_origin_timeline | conn_origin_dboid | conn_is_unidirectional |                      conn_dsn                      | conn_apply_delay | conn_replication_sets 
---------------------+---------------+------------+-------------------+----------------------+-------------------+------------------------+----------------------------------------------------+------------------+-----------------------
 6167310327656349802 |             1 |      19068 | 0                 |                    0 |                 0 | f                      | host=NODE1 port=5432 dbname=DBNAME |                  | {default}
(1 row)
```

[NODE1] Replication Slots
```
SELECT * FROM pg_replication_slots
                slot_name                | plugin | slot_type | datoid | database | active | xmin | catalog_xmin | restart_lsn 
-----------------------------------------+--------+-----------+--------+----------+--------+------+--------------+-------------
 bdr_19068_6167332740252040116_2_19068__ | bdr    | logical   |  19068 | DBNAME  | f      |      |         1880 | 0/1F000028
```

BTW: Canceling this process leads to manual cleanup that has to be done after: replication_slots, bdr.nodes etc.

**Comment by pape-io** [comment]
When DB cluster was not yet existing (data directory is empty) it  freezes at:

```
Bringing local node to the restore point ...
```

**Comment by ringerc** [comment]
Was `/var/lib/postgresql/9.4/main` empty before `bdr_init_copy` was invoked?

There are some fixes coming that'll detect attempts to point `bdr_init_copy` at the wrong data directory, an already-reset basebackup, etc, but in 0.9.1 no such detection is performed.

Please attach the log files `bdr_init_copy` writes in the current directory when it's run.

**Comment by pape-io** [comment]
From the second attempt of bdr_init_copy which frooze at 

```
Bringing local node to the restore point ...
```

the logs contain
```
postgres cannot access the server configuration file "/var/lib/postgresql/9.4/main/postgresql.conf": No such file or directory
postgres cannot access the server configuration file "/var/lib/postgresql/9.4/main/postgresql.conf": No such file or directory
postgres cannot access the server configuration file "/var/lib/postgresql/9.4/main/postgresql.conf": No such file or directory
postgres cannot access the server configuration file "/var/lib/postgresql/9.4/main/postgresql.conf": No such file or directory
postgres cannot access the server configuration file "/var/lib/postgresql/9.4/main/postgresql.conf": No such file or directory
postgres cannot access the server configuration file "/var/lib/postgresql/9.4/main/postgresql.conf": No such file or directory
postgres cannot access the server configuration file "/var/lib/postgresql/9.4/main/postgresql.conf": No such file or directory
postgres cannot access the server configuration file "/var/lib/postgresql/9.4/main/postgresql.conf": No such file or directory

**Comment by pape-io** [comment]
I was not able to find the logs of the first attempt anymore, maybe I reinstalled that particular server. Next time I will capture those log files.

I will try another bdr_init_copy in the upcoming week. So, if I understood correctly, data directory has to exist (but has to empty?) and the postgresql.conf has to be around?? Is it okay, when the data directory is an already existing cluster? That way the directory and the conf file whould be arround allready.

Thanks

**Comment by ringerc** [comment]
> So, if I understood correctly, data directory has to exist (but has to empty?) and the postgresql.conf has to be around??

There are two ways to run `bdr_init_copy`:

* Point it at an empty or missing data directory and let it run a `pg_basebackup` of the target server; or

* Point it at an existing data directory, which *must* be a base backup of the target server you have taken by other means.

If the target directory is not empty and does not contain a base backup of the server you're cloning from, i.e. the remote server, then it *will not work*. More checks have been added to detect this and `ERROR` out in the coming release.

If `bdr_init_copy` fails then you must delete the data directory it created and try again. You can't re-run it on a data directory it's failed to join. Again, checks to detect this have been added to the coming release.

Usually `pg_basebackup` copies `postgresql.conf` so you don't have to worry about it. The exception to this is on Debian/Ubuntu systems, which symlink it to `/etc` if you're using packaged versions of PostgreSQL. On these systems you must manually copy `postgresql.conf` to a temporary location then pass it to the `--postgresql-conf` option to `bdr_init_copy` so it can copy it into place when the base backup completes. You'll want to do the same with `pg_hba.conf`, passing the `--hba-conf` argument.

It seems highly likely that one or more of these issues was at work in your case. I'm going to close this issue. If you supply *detailed* steps to reproduce, including exactly how BDR was installed, where from, the version, the exact commands run, etc, to get to this point and you think it's a bug, please comment to that effect.

**Comment by pape-io** [comment]
Using `--postgresql-conf` and `--hba-conf` made it work.

Something else I realized when doing bdr_init_copy is, that besides an empty data directory, postgresql processes should'n run!

**Comment by qnub** [comment]
@pape-io thanks, you just save my live! 👏
