### ISSUE TITLE
Altering the owner of a database does not replicate

### ISSUE THREAD

**Issue by kforte90** [2ndQuadrant/bdr#108]
ALTER DATABASE doesn't seem to replicate from one node to another.
Consider the following:
**node1**
--Get the owner name of the current BDR-active database
SELECT u.usename 
FROM pg_database d
JOIN pg_user u ON (d.datdba = u.usesysid)
WHERE d.datname = (SELECT current_database());

usename 
----------
 postgres

bdrdemo=# alter database bdrdemo owner to newdba;
ALTER DATABASE
SELECT u.usename 
 FROM pg_database d
  JOIN pg_user u ON (d.datdba = u.usesysid)
 WHERE d.datname = (SELECT current_database());

usename
---------
 newdba
(1 row)

**node2**
SELECT u.usename 
 FROM pg_database d
  JOIN pg_user u ON (d.datdba = u.usesysid)
 WHERE d.datname = (SELECT current_database());

usename
----------
 postgres
(1 row)

--------------
Probably the same issue as with other global objects.  With 0.9.1

**Comment by anarazel** [comment]
> ALTER DATABASE doesn't seem to replicate from one node to another.

That's documented to be the case. Databases are global objects and are
not replicated.

**Comment by kforte90** [comment]
An error would be good rather than having the user change the owner and have an inconsistency.

**Comment by anarazel** [comment]
> An error would be good rather than having the user change the owner and have an inconsistency.

No, that'd be worse, because it'd make it impossible to change settings.

**Comment by ringerc** [comment]
The only way we can make this something the user doesn't have to think
about is to have a BDR mode where we allow only one database per cluster,
and we decode global DDL.​

While we have global objects (databases, users, etc) that may relate to
more than one database, and we allow some DBs to be replicated and not
others, there's not a simple solution.

**Comment by martinmarques** [comment]
2015-07-07 15:41 GMT-03:00 Andres Freund <notifications@github.com>:
>
> > An error would be good rather than having the user change the owner and have an inconsistency.
>
> No, that'd be worse, because it'd make it impossible to change settings.

Why not just send a NOTICE when in bdr mode (bdr preloaded) saying
something like: The ALTER DATABASE statement will not be replicated to
other bdr nodes

I agree with Andres that this will make things worst, and it's not the
goal of BDR to do such things.

-- 
Martín Marqués                http://www.2ndQuadrant.com/
PostgreSQL Development, 24x7 Support, Training & Services
