### ISSUE TITLE
Add documention for node_status

### ISSUE THREAD

**Issue by gilesw** [2ndQuadrant/bdr#111]
It would be good to have the node status' in the documentation and what they mean to aid bdr monitoring. I found some mention in the code.

 - [b]i-directional ? 
 - [i]nitializing ? what is a database doing when it's initializing?
 - [c]atchup ? presumably this means a database is behind but part of a cluster?
 - n[o]ne ? database not being replicated. How is this switched off and on?
 - [r]eady ? should this be the expected state in a cluster?
 - [k]illed ?

**Comment by ringerc** [comment]
http://bdr-project.org/docs/next/catalog-bdr-nodes.html

We should probably provide a view over bdr.bdr_nodes and
pg_replication_slots that handles the mapping of sysid to slot name and
displays expanded status information.
​

**Comment by ringerc** [comment]
You're not the first to mention wanting docs for node_status, though
it is documented. Where did you look when you wanted to find out about
it? Where do you think we should have cross-references to make the
existing documentation discoverable?

**Comment by gilesw** [comment]
Hi ringerc,

That makes me feel a bit better that I'm not the only one. I grepped through the docs before I logged this ticket so I didn't look like a plonker.

     grep -r node_status *

the area I would expect to see this mentioned is under node-management.html

I personally liked the [x]term syntax in the code as it will make the terms more memorable.

**Comment by gilesw** [comment]
Definitely agree with the mappings btw. I'm writing some helper scripts at the moment to show the status of the cluster to join that info up.

**Comment by ringerc** [comment]
Ok, that makes sense.​

Any chance of sending a pull with a docs update adding an xref where you'd
expect to find it?

I'll try to find a chance to build a view.
