### ISSUE TITLE
Question: Replication Between 3 nodes

### ISSUE THREAD

**Issue by rafaelugolini** [2ndQuadrant/bdr#112]
I was testing BDR system with master-to-master replication in 3 nodes and I got a result which I'm not sure it's expected or if I did a mistake in the configuration. 

The purpose of this test is to see how BDR replication system works using nodes in different regions (USA, Europe and Asia) with network problems. 

After setting up the 3 nodes, when I update a row in one node it replicate to the others without any problem but if I block connection in Europe to Asia and I update a row in Asia, it only replicate to USA but if I update same row in USA, it replicates to Europe and Asia.
Is this the normal behavior? Or USA should see that there is a value different in Europe and update it automatically?

Configuration file was same for all the servers:
```bash
shared_buffers = 128MB
dynamic_shared_memory_type = posix
shared_preload_libraries = 'bdr,pg_stat_statements'  
pg_stat_statements.max = 10000
pg_stat_statements.track = all
track_activity_query_size = 2048
max_worker_processes = 100
wal_level = logical 
max_wal_senders = 60 
max_replication_slots = 60
track_commit_timestamp = on
```

To initialize the first node in Europe I did:
```sql
CREATE EXTENSION btree_gist;
CREATE EXTENSION bdr;
SELECT bdr.bdr_group_create(
 local_node_name := 'node1',
 node_external_dsn := 'host=192.168.59.103 port=5432 dbname=postgres');
```

The node in Asia:
```sql
CREATE EXTENSION btree_gist;
CREATE EXTENSION bdr;
SELECT bdr.bdr_group_join(
       local_node_name := 'node2',
       node_external_dsn := 'host=192.168.59.104 port=5432 dbname=postgres',
       join_using_dsn := 'host=192.168.59.103 port=5432 dbname=postgres');
```

The node in USA
```sql
CREATE EXTENSION btree_gist;
CREATE EXTENSION bdr;
SELECT bdr.bdr_group_join(
       local_node_name := 'node2',
       node_external_dsn := 'host=192.168.59.105 port=5432 dbname=postgres',
       join_using_dsn := 'host=192.168.59.103 port=5432 dbname=postgres');
```

In order to block the connections from nodes I was using this little iptables script
```bash
reject_ip () {
    IP=$1
    iptables -A OUTPUT -d $IP -j REJECT
    iptables -I FORWARD 1 -d $IP -j REJECT
    iptables -I FORWARD 1 -s $IP -j REJECT
    iptables -A INPUT -s $IP -j REJECT
}
 
unreject_ip () {
    IP=$1
    iptables -D OUTPUT -d $IP -j REJECT
    iptables -D FORWARD -d $IP -j REJECT
    iptables -D FORWARD -s $IP -j REJECT
    iptables -D INPUT -s $IP -j REJECT
}
```

**REJECT Test**

Test | USA | Europe | Asia
---- | --- | ------ | ----
Set counter in Europe to 250 | 250 | 250 | 250
*Block Asia in Europe* | 250 | 250 | 250
Set counter in Asia to 300 | 300 | **250** | 300
Set counter in USA to 350 | 350 | 350 | 350
Set counter in Europe to 400 | 400 | 400 | **350**
Set counter in Asia to 450 | 450 | **400** | 450
Set counter in Europe to 500 | 500 | 500 | **450**
*Restore connection* | 500 | 500 | 500

**Comment by ringerc** [comment]
​BDR is a mesh. You need connectivity from each node to each other node.
Changes are not forwarded from one node to another.

This is expected behaviour.

There's some future work that may enable change forwarding if a node
becomes partially unreachable, but it's a fairly long way off yet.

This isn't a bug, so I'll close the issue. Please submit general questions,
test reports, etc to the pgsql-general mailing list with BDR clearly in the
subject, rather than filing github issues.
