### ISSUE TITLE
Dropped columns break replication on nodes added after column drop

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#113]
Dropping a column then cloning a new node and making a change to the table with the dropped column results in breakage.

If the table is changed on the old node with the dropped columns:

```
[2015-07-20 03:32:08.692 GMT] [16956] [postgres] DETAIL:  There are no running transactions.
[2015-07-20 03:32:08.694 GMT] [16955] [] ERROR:  tuple natts mismatch, 3 vs 4
```

A similar issue occurs in reverse if you change the copied table without the dropped cols, as the receiver expects to find dropped attributes.

I'll push a branch showing this bug.

**Comment by ringerc** [comment]
For dropped columns I think we'll have to transform what we emit from
the output plugin, omitting dropped columns and compacting attnos.
Then on the apply side we map them in order to the non-dropped local
columns. 

This is a bit risky if done based on attno alone though; if you have a table like

(a text, b text [dropped], c text)

on the upstream and

(a text, b text, c text [dropped])

on the downstream then we'd happily copy the (a, c) tuple to (a,b) on
the downstream, since we're not bothering about column names and are
skipping over dropped columns.

I don't see any sensible way to avoid that without having a proper
column mapping. I don't think it's a replication problem we can afford
to just accept and ignore though.

We don't want to send a column name mapping on the wire with every tx
as it'll be horribly inefficient. We also can't ask the output plugin
for it when we first replicate any given table and cache it in memory
because we have to be able to replay transactions from on-disk state
only after the upstream node is lost in a crash. Maybe we need a
persistent downstream mapping of column names to attnos that gets sent
when a table is first replicated and updated when an ALTER TABLE or
similar gets executed upstream. It seems unnecessarily complicated,
but I'm not sure how else to solve this.

Sending a bitmap of dropped attnos won't help, it has the same issues
as omitting them.

Another option is hacking `pg_dump` to emit tables with dropped columns, followed by `ALTER TABLE ... DROP COLUMN ...` statements. Then use that when cloning a DB. That seems like an awful workaround though, and won't get us any further toward enabling use cases with user-managed DDL like UDR data accumulation.

**Comment by anarazel** [comment]
On 2015-07-19 20:42:39 -0700, Craig Ringer wrote:
> Another option is hacking `pg_dump` to emit tables with dropped columns, followed by `ALTER TABLE ... DROP COLUMN ...` statements. Then use that when cloning a DB. That seems like an awful workaround though, and won't get us any further toward enabling use cases with user-managed DDL like UDR data accumulation.

Note that pg_dump already has that, for binary upgrade.
