### ISSUE TITLE
Tuple natts mismatch, 15 vs 19

### ISSUE THREAD

**Issue by aletabu** [2ndQuadrant/bdr#114]
I've installed the BDR on Debian 7 (wheezy) from packages using "apt-get install bdr-9.4"

bdr_version: 0.9.1-2015-05-26-

I could create the group and join the node successfully but when I do a modification like an insert I got this error:

ERROR:  tuple natts mismatch, 15 vs 19
2015-07-22 20:40:51 UTC [4888-22] LOG:  worker process: bdr (6174415376201187442,1,20739,)->bdr (6174415376201187442,1, (PID 5037) exited with exit code 1
2015-07-22 20:40:56 UTC [4888-23] LOG:  starting background worker process "bdr (6174415376201187442,1,20739,)->bdr (6174415376201187442,1,"

Any idea?

**Comment by PJMODOS** [comment]
I think this is same issue as #113

**Comment by aletabu** [comment]
Note: In this case I'm just doing an insert. The database has the standard Django structure.

**Comment by aletabu** [comment]
It worked with an empty database on all nodes. If I run sql statements to create tables once the BDR is set up it works fine. Seems that is a bug in the init copy function.

**Comment by PJMODOS** [comment]
yes, also if you setup the new nodes via bdr_init_copy, the problem should not be present

**Comment by ringerc** [comment]
Yes, this looks like a case of #113. At this point the best options are:

* use `bdr_init_copy` to do a low-level clone of the database (including any dropped columns);
* join all the nodes before you create any schema; or
* don't drop columns

Needless to say the first is the most practical, so at this point we're going to pretty much have to deprecate `bdr_group_join` in BDR 0.9.x.

We're working on protocol changes that will address this, but it's unfortunately not something that can be worked around quickly and simply. The only reasonably simple fix creates other problems.

**Comment by aletabu** [comment]
Yes, I guess the best option is to use bdr_init_copy as if there are an existing replication schema with 2 nodes, then I can add a third one just executing that function. That is not possible to do if I have to start always with empty databases (it's harder)

**Comment by ringerc** [comment]
We'll be able to fix this issue​, it's just going to require some changes
to the internal version of pg_dump we use. Since there's a practical
workaround there's other work that needs to come first. This will be dealt
with; in the mean time, using bdr_init_copy will be the way to go.
