### ISSUE TITLE
Can not remove sequence from replication set

### ISSUE THREAD

**Issue by pascalbetz** [2ndQuadrant/bdr#115]
New to BDR so sorry if this is obvious.

Global sequences currently raise an error when they need to fetch a new block. Since blocking reads on global sequences are not (yet) available i wanted to create a interleaved sequences (different start values and increment = number of nodes).

In order to achieve this i think i need to remove the sequence from replication (otherwise start/increment values are repliacted). I have troubles doing so. Is there another solution to my problem?

Since global sequences will not work with a failed node in a two node setup (nodes/2 + 1 nodes need to be up in order for the sequences to work) i might need to change to interleaved sequences anyway, my setup should be fault tolerant even with a small number of nodes.

Problem is: i can not remove sequences from replication set.

I can list replicate sets for tables and sequences:

```sql
select bdr.table_get_replication_sets('orders')
 => {all}
select bdr.table_get_replication_sets('orders_id_seq')
=> {all,default}
```

I can change it for tables:
```sql
select bdr.table_set_replication_sets('orders', '{foo}')
select bdr.table_get_replication_sets('orders')
=> {all,foo}
```

But can not change it for sequences:

```sql

select bdr.table_set_replication_sets('orders_id_seq', '{foo}')

=>Error : ERROR:  "orders_id_seq" is not a table
CONTEXT:  SQL statement "SECURITY LABEL FOR bdr ON TABLE orders_id_seq IS '{ "sets" : ["foo"] }'"
PL/pgSQL function bdr.table_set_replication_sets(regclass,text[]) line 30 at EXECUTE statement
```

Also i don't seem to be able to re-add a table to 'default':

```sql

select bdr.table_set_replication_sets('orders', '{default}')

=> Error : ERROR:  replication set name "default" is reserved
CONTEXT:  SQL statement "SECURITY LABEL FOR bdr ON TABLE orders IS '{ "sets" : ["default"] }'"
PL/pgSQL function bdr.table_set_replication_sets(regclass,text[]) line 30 at EXECUTE statement

```

Thanks for the help.

**Comment by martinmarques** [comment]
Hi,

Sequence value changes are not replicated. The BDR sequences work by assigning chunks of values they can use on each node, and not overlapping those values (something like a partition of values of the sequence, with different chunks  assigned to each node).

What you want is to set the sequence as a local one instead of a bdr one.

For that, you have to ALTER the sequence, like this:

ALTER SEQUENCE orders_id_seq  USING local;

After that the sequence will be considered local and so will not need sophisticated voting procedures to get new values assigned. You can then work on the changing the currval and step of the sequence on each node, as you would do on a vanilla postgres sequence.

Regards,

**Comment by pascalbetz** [comment]
@martinmarques 

Thanks for the fast reply.

Actually the sequence are not BDR but local. While the current values are not synced amongst the nodes their definitions are. So i can not alter a sequence (setting its increment/start value) without this being replayed on other nodes.

I guess this is intended behavior. My Problem remains:

* can not remove a sequence from a replication set
* can not add a table back to "default"

**Comment by martinmarques** [comment]
Two options I can think of:

1) Inside a transaction set bdr.skip_ddl_replication and bdr.skip_ddl_locking to true so the DDL isn't replicated to the other nodes, and then run the appropriate ALTER SEQUENCE [1]

2) Set the sequence step globally with ALTER SEQUENCE and then change the start point on each node with setval() which will not be replicated

Hope that helps you

[1]: Be careful and reset the values once the txn is committed, or use SET LOCAL

**Comment by pascalbetz** [comment]
Thanks. I'll try those and will give  feedback.

**Comment by pascalbetz** [comment]
@martinmarques i went with 2) and this works so far. Thanks.

While i can continue with my work i think the original issue described is valid:

* can not remove a sequence from a replication set
* can not add a table back to "default"

**Comment by PJMODOS** [comment]
I doubt we'll change sequences anytime soon, but you can add table back to default - SELECT bdr.bdr.table_set_replication_sets('tablename', NULL);
Note that "default" replication set is special and can't be combined with any other currently.

**Comment by PJMODOS** [comment]
ALTER SEQUENCE <name> USING local; makes sequence use local generator instead of BDR voting. That's effectively what you want when you say you want to remove sequence from replication set.
