### ISSUE TITLE
Very large tables break replication

### ISSUE THREAD

**Issue by adamaku** [2ndQuadrant/bdr#116]
Hello,

I've set up a two node BDR database on Ubuntu 14.04 using your repository located at http://packages.2ndquadrant.com/bdr/apt/ using the following packages:

> ii  postgresql-bdr-9.4                  9.4.2-1trusty                 amd64        object-relational SQL database, version 9.4 server
> ii  postgresql-bdr-9.4-bdr-plugin       0.9.1-1trusty                 amd64        BDR Plugin for PostgreSQL-BDR 9.4
> ii  postgresql-bdr-client-9.4           9.4.2-1trusty                 amd64        front-end programs for PostgreSQL-BDR 9.4
> ii  postgresql-bdr-contrib-9.4          9.4.2-1trusty                 amd64        additional facilities for PostgreSQL

Using pgbench-tools located here: https://github.com/gregs1104/pgbench-tools

I create the databases necessary (pgbench, results), and then join the pgbench database together like so:

> create database pgbench;
> \c pgbench;
> CREATE EXTENSION btree_gist;
> CREATE EXTENSION bdr;
> (first node) select bdr.bdr_group_create(local_node_name := 'node01', node_external_dsn := 'host=node01 port=5432 dbname=pgbench');
> (second node to join) select bdr.bdr_group_join(local_node_name := 'node02', node_external_dsn := 'host=node02 port=5432 dbname=pgbench', join_using_dsn := 'host=node01 port=5432 dbname=pgbench');
> SELECT bdr.bdr_node_join_wait_for_ready();

I then run the default set of tests with pgbench-tools. When it gets to benchmarking a table with 100 million rows, replication breaks. 

99400000 of 100000000 tuples (99%) done (elapsed 388.32 s, remaining 2.34 s).
99500000 of 100000000 tuples (99%) done (elapsed 388.34 s, remaining 1.95 s).
99600000 of 100000000 tuples (99%) done (elapsed 388.52 s, remaining 1.56 s).
99700000 of 100000000 tuples (99%) done (elapsed 388.71 s, remaining 1.17 s).
99800000 of 100000000 tuples (99%) done (elapsed 388.73 s, remaining 0.78 s).
99900000 of 100000000 tuples (99%) done (elapsed 388.92 s, remaining 0.39 s).
100000000 of 100000000 tuples (100%) done (elapsed 388.95 s, remaining 0.00 s).
vacuum...
set primary keys...
*this is where it hangs*

Looking at the count for records in each table on each node, node01 has the correct amount of records (100mm), but node02 shows 199893508 rows. As if the table wasn't truncated correctly. However, this works on every test up to 100mm rows, and consistently fails at this point.

My logs look like this:

> 2015-07-23 18:01:30 CDT d= p=5841 a=ERROR:  XX000: connection to other side has died
> 2015-07-23 18:01:30 CDT d= p=5841 a=LOCATION:  bdr_apply_work, bdr_apply.c:2293
> 2015-07-23 18:01:30 CDT d= p=48079 a=LOG:  00000: worker process: bdr (6174782918793040278,1,16385,)->bdr (6174782940821662961,1, (PID 5841) exited with exit code 1
> 2015-07-23 18:01:30 CDT d= p=48079 a=LOCATION:  LogChildExit, postmaster.c:3325
> 2015-07-23 18:01:35 CDT d= p=48079 a=LOG:  00000: starting background worker process "bdr (6174782918793040278,1,16385,)->bdr (6174782940821662961,1,"
> 2015-07-23 18:01:35 CDT d= p=48079 a=LOCATION:  do_start_bgworker, postmaster.c:5412
> 2015-07-23 18:16:43 CDT d= p=48081 a=LOG:  00000: checkpoints are occurring too frequently (29 seconds apart)
> 2015-07-23 18:16:43 CDT d= p=48081 a=HINT:  Consider increasing the configuration parameter "checkpoint_segments".
> 2015-07-23 18:16:43 CDT d= p=48081 a=LOCATION:  CheckpointerMain, checkpointer.c:485
> 2015-07-23 18:30:02 CDT d=pgbench p=5842 a=bdr (6174782940821662961,1,16385,):receiveERROR:  XX000: invalid memory alloc request size 1073741824
> 2015-07-23 18:30:02 CDT d=pgbench p=5842 a=bdr (6174782940821662961,1,16385,):receiveCONTEXT:  slot "bdr_16385_6174782940821662961_1_16385__", output plugin "bdr", in the change callback, associated LSN 3/C535650
> 2015-07-23 18:30:02 CDT d=pgbench p=5842 a=bdr (6174782940821662961,1,16385,):receiveLOCATION:  repalloc, mcxt.c:724
> 2015-07-23 18:30:07 CDT d=pgbench p=16437 a=bdr (6174782940821662961,1,16385,):receiveLOG:  00000: starting logical decoding for slot "bdr_16385_6174782940821662961_1_16385__"
> 2015-07-23 18:30:07 CDT d=pgbench p=16437 a=bdr (6174782940821662961,1,16385,):receiveDETAIL:  streaming transactions committing after 8/1CC2000, reading WAL from 0/8A70CE00
> 2015-07-23 18:30:07 CDT d=pgbench p=16437 a=bdr (6174782940821662961,1,16385,):receiveLOCATION:  CreateDecodingContext, logical.c:442
> 2015-07-23 18:30:07 CDT d=pgbench p=16437 a=bdr (6174782940821662961,1,16385,):receiveLOG:  00000: logical decoding found consistent point at 0/8A70CE00
> 2015-07-23 18:30:07 CDT d=pgbench p=16437 a=bdr (6174782940821662961,1,16385,):receiveDETAIL:  There are no running transactions.
> 2015-07-23 18:30:07 CDT d=pgbench p=16437 a=bdr (6174782940821662961,1,16385,):receiveLOCATION:  SnapBuildFindSnapshot, snapbuild.c:1271
> 2015-07-23 18:44:34 CDT d=pgbench p=16437 a=bdr (6174782940821662961,1,16385,):receiveERROR:  XX000: invalid memory alloc request size 1073741824
> 2015-07-23 18:44:34 CDT d=pgbench p=16437 a=bdr (6174782940821662961,1,16385,):receiveCONTEXT:  slot "bdr_16385_6174782940821662961_1_16385__", output plugin "bdr", in the change callback, associated LSN 3/C535650

After that it just starts repeating. The behavior is for the pg_replslot directory to slowly increase until it runs out of space. Once it runs out of space, it clears up and slowly fills again.

Here is my postgresql.conf

> listen_addresses = '*'			# what IP address(es) to listen on;
> port = 5432				# (change requires restart)
> max_connections = 1000			# (change requires restart)
> unix_socket_directories = '/var/run/postgresql'	# comma-separated list of directories
> ssl = false				# (change requires restart)
> ssl_renegotiation_limit = 0		# amount of data between renegotiations
> ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'		# (change requires restart)
> ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'		# (change requires restart)
> shared_buffers = 8GB			# min 128kB
> work_mem = 10240MB				# min 64kB
> maintenance_work_mem = 10GB		# min 1MB
> autovacuum_work_mem = -1		# min 1MB, or -1 to use maintenance_work_mem
> dynamic_shared_memory_type = posix	# the default is the first option
> shared_preload_libraries = 'bdr'	# (change requires restart)
> max_worker_processes = 10
> wal_level = logical			# minimal, archive, hot_standby, or logical
> checkpoint_segments = 60		# in logfile segments, min 1, 16MB each
> max_wal_senders = 20		# max number of walsender processes
> max_replication_slots = 20	# max number of replication slot
> track_commit_timestamp = on	# collect timestamp of transaction commit
> random_page_cost = 1.1			# same scale as above
> effective_cache_size = 31GB
> log_min_messages = warning		# values in order of decreasing detail:
> log_error_verbosity = verbose		# terse, default, or verbose messages
> log_line_prefix = '%t d=%d p=%p a=%a%q'			# special values:
> log_timezone = 'localtime'
> datestyle = 'iso, mdy'
> timezone = 'localtime'
> lc_messages = 'en_US.UTF-8'			# locale for system error message
> lc_monetary = 'en_US.UTF-8'			# locale for monetary formatting
> lc_numeric = 'en_US.UTF-8'			# locale for number formatting
> lc_time = 'en_US.UTF-8'				# locale for time formatting
> default_text_search_config = 'pg_catalog.english'

This same exact benchmark works on 100k rows, 1mm rows, and 10mm rows. So I'm rather confused.

**Comment by PJMODOS** [comment]
It's not table size that's problem, it's the transaction size. We don't support replicating transactions which change 100M of tuples.

**Comment by adamaku** [comment]
Oh nice! I'm glad I am not doing something wrong here. Just curious, what is the limit on the size of tuples changed?

**Comment by ringerc** [comment]
It's mostly down to how much RAM you can throw at it. There's no firm limit. A rule of thumb would be "millions are too many".

**Comment by superattack** [comment]
I run into this issues by deleting about 1.5million records of one table and now I’m having this issue described above. What needs to be done in order to restore the cluster to the normal behavior? 

Thanks,

**Comment by markrowsoft** [comment]
I have run into this issue as well.  Now that I know how to avoid it, how do I fix the problem I created? (short of erasing the entire database)

**Comment by ringerc** [comment]
@superattack and @SoumitraBhandary please post to the bdr/pglogical mailing list for help with your specific issues if you see problems like this in future.

PostgreSQL's logical replication does not currently deal with extremely large single transaction as well as it could, but it should never fail or stop so long as sufficient disk and RAM are available. You'd need to check *why* it's failing though; I can't say anything useful from "damaged permanently" etc.
