### ISSUE TITLE
PL/R on BDR

### ISSUE THREAD

**Issue by tsykes** [2ndQuadrant/bdr#118]
I'm trying to run pl/r on BDR. I see there are packages for pl/python and pl/perl. I assume this means the regular pgdg postgres packages don't work under BDR. Will there be a BDR issue if I configure without using the pgdg plr package?

**Comment by ringerc** [comment]
While PL/R isn't specifically tested, in general the PGDG packages should
work fine with BDR. That's the main reason it's packaged in a way that
conflicts with PGDG's PostgreSQL packages, so that it can share the same
extension path.​

The reason PL/Python and PL/Perl are packaged is that they're in the main
PostgreSQL package and source tree. The other PLs are packaged separately.

**Comment by tsykes** [comment]
I had no luck getting pl/r running on BDR. I also ran on a vanilla instance and it was fine so I went ahead and created a backtrace. Someone might see something they understand. 

I'm running on Centos 7. R and pl/r are installed. Functions like  plr_environ() work fine. But when trying something that uses R like the basic median function, postgres crashes. 

This is the error in the pg_log
server process (PID 7071) was terminated by signal 11: Segmentation fault

This is the error in gdb
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7fdc840 (LWP 7225)]
hashoidvector (fcinfo=fcinfo@entry=0x7fffffffcd90) at hashfunc.c:130
130             return hash_any((unsigned char *) key->values, key->dim1 * sizeof(Oid));

This is the backtrace
 ======= Backtrace: =========
/lib64/libc.so.6(+0x7d1fd)[0x7fcf306de1fd]
gdb(find_pc_section+0x99)[0x605089]
gdb(lookup_minimal_symbol_by_pc_section+0x1d)[0x60898d]
gdb(find_pc_sect_symtab+0x29)[0x59eba9]
gdb(select_frame+0x71)[0x699a11]
gdb(get_selected_frame+0x39)[0x699a89]
gdb(get_current_arch+0x27)[0x5e5447]
gdb[0x52ba1e]
gdb(registry_clear_data+0x93)[0x6bea63]
gdb(registry_container_free_data+0xf)[0x6beadf]
gdb[0x6ba8b2]
gdb(prune_program_spaces+0x4c)[0x6ba99c]
gdb[0x5b71a1]
gdb(execute_command+0x2aa)[0x6901ba]
gdb[0x5d85d1]
gdb[0x5d8a8c]
/lib64/libreadline.so.6(rl_callback_read_char+0x8e)[0x7fcf32628c6e]
gdb[0x5d8639]
gdb[0x5d71f4]
gdb(gdb_do_one_event+0x5a)[0x5d753a]
gdb(start_event_loop+0x57)[0x5d77b7]
gdb[0x5d0623]
gdb(catch_errors+0x8a)[0x5cee0a]
gdb[0x5d12d6]
gdb(catch_errors+0x8a)[0x5cee0a]
gdb(gdb_main+0x24)[0x5d1f04]
gdb(main+0x3e)[0x4572ee]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fcf30682af5]
gdb[0x457331]
======= Memory map: ========
00400000-00a02000 r-xp 00000000 fd:01 26963884                           /usr/bin/gdb
00c01000-00c02000 r--p 00601000 fd:01 26963884                           /usr/bin/gdb
00c02000-00c19000 rw-p 00602000 fd:01 26963884                           /usr/bin/gdb
00c19000-00c3c000 rw-p 00000000 00:00 0
00ffc000-10a98000 rw-p 00000000 00:00 0                                  [heap]
7fcf2600b000-7fcf26a29000 rw-p 00000000 00:00 0
7fcf26a29000-7fcf27103000 r--p 00795000 fd:01 4015913750                 /usr/lib/debug/usr/pgsql-9.4/bin/postgres.debug
7fcf27103000-7fcf2723e000 r--p 005e2000 fd:01 4015913750                 /usr/lib/debug/usr/pgsql-9.4/bin/postgres.debug
7fcf2723e000-7fcf27301000 r--p 0049e000 fd:01 6482355015                 /usr/lib/debug/usr/lib64/libc-2.17.so.debug
7fcf27301000-7fcf27398000 r--p 00408000 fd:01 6482355015                 /usr/lib/debug/usr/lib64/libc-2.17.so.debug
7fcf27398000-7fcf2778f000 r--p 00012000 fd:01 6482355015                 /usr/lib/debug/usr/lib64/libc-2.17.so.debug
7fcf2780c000-7fcf278bf000 rw-p 00000000 00:00 0
7fcf2793c000-7fcf279e4000 rw-p 00000000 00:00 0
7fcf27a2d000-7fcf27a42000 r--p 000be000 fd:01 448076                     /usr/lib64/libkrb5.so.3.3
7fcf27a42000-7fcf27b04000 r--p 00e6e000 fd:01 4015913750                 /usr/lib/debug/usr/pgsql-9.4/bin/postgres.debug
7fcf27b04000-7fcf27c76000 rw-p 00000000 00:00 0
7fcf27c7e000-7fcf27ca9000 r--p 00188000 fd:01 3169                       /usr/lib64/libc-2.17.so
7fcf27ca9000-7fcf27cb1000 r--p 00047000 fd:01 115844                     /usr/lib64/libldap-2.4.so.2.10.2
7fcf27cb1000-7fcf27cb7000 r--p 000f9000 fd:01 3177                       /usr/lib64/libm-2.17.so
7fcf27cb7000-7fcf27cbe000 r--p 00042000 fd:01 205977                     /usr/lib64/libgssapi_krb5.so.2.2
7fcf27cbe000-7fcf27cf1000 r--p 0018a000 fd:01 205992                     /usr/lib64/libcrypto.so.1.0.1e
7fcf27cf1000-7fcf27cf9000 r--p 0005b000 fd:01 205997                     /usr/lib64/libssl.so.1.0.1e
7fcf27cf9000-7fcf27d1c000 r--p 0013b000 fd:01 144978                     /usr/lib64/libxml2.so.2.9.1
7fcf27d1c000-7fcf28413000 rw-p 00000000 00:00 0
7fcf28413000-7fcf2841c000 r--p 00033000 fd:01 4051381080                 /usr/lib/debug/usr/pgsql-9.4/lib/cstore_fdw.so.debug
7fcf2841c000-7fcf28425000 r--p 00024000 fd:01 4016351220                 /usr/lib/debug/usr/pgsql-9.4/lib/btree_gist.so.debug
7fcf28425000-7fcf2843a000 r--p 000c7000 fd:01 6482648873                 /usr/lib/debug/usr/lib64/libldap_r-2.4.so.2.10.2.debug
7fcf2843a000-7fcf28445000 r--p 00066000 fd:01 4016893382                 /usr/lib/debug/usr/pgsql-9.4/lib/libpq.so.5.7.debug
7fcf28445000-7fcf28457000 r--p 00080000 fd:01 3925868910                 /usr/lib/debug/usr/pgsql-9.4/lib/bdr.so.debug
7fcf28457000-7fcf28460000 r--p 000d1000 fd:01 6482648894                 /usr/lib/debug/usr/lib64/libpcre.so.1.2.0.debug
7fcf28460000-7fcf28469000 r--p 00064000 fd:01 6482648887                 /usr/lib/debug/usr/lib64/libselinux.so.1.debug
7fcf28469000-7fcf2847a000 r--p 0009a000 fd:01 6482648775                 /usr/lib/debug/usr/lib64/libnspr4.so.debug
7fcf2847a000-7fcf28489000 r--p 00055000 fd:01 6482648822                 /usr/lib/debug/usr/lib64/libnssutil3.so.debug
7fcf28489000-7fcf284e1000 r--p 00362000 fd:01 6482648817                 /usr/lib/debug/usr/lib64/libnss3.so.debug
7fcf284e1000-7fcf284f6000 r--p 00080000 fd:01 6482648820                 /usr/lib/debug/usr/lib64/libsmime3.so.debug
7fcf284f6000-7fcf2850d000 r--p 000a7000 fd:01 6482648821                 /usr/lib/debug/usr/lib64/libssl3.so.debug
7fcf2850d000-7fcf28514000 r-xp 00000000 fd:01 3267                       /usr/lib64/libthread_db-1.0.so
7fcf28514000-7fcf28713000 ---p 00007000 fd:01 3267                       /usr/lib64/libthread_db-1.0.so
7fcf28713000-7fcf28714000 r--p 00006000 fd:01 3267                       /usr/lib64/libthread_db-1.0.so
7fcf28714000-7fcf28715000 rw-p 00007000 fd:01 3267                       /usr/lib64/libthread_db-1.0.so
7fcf2871a000-7fcf28720000 r--p 00043000 fd:01 6482648879                 /usr/lib/debug/usr/lib64/libsasl2.so.3.0.0.debug
7fcf28720000-7fcf28728000 r--p 00090000 fd:01 6482648673                 /usr/lib/debug/usr/lib64/libpthread-2.17.so.debug
7fcf28728000-7fcf28759000 r--p 001fe000 fd:01 6482648804                 /usr/lib/debug/usr/lib64/libkrb5.so.3.3.debug
7fcf28759000-7fcf28763000 r--p 0006c000 fd:01 6482648884                 /usr/lib/debug/usr/lib64/liblzma.so.5.0.99.debug
7fcf28763000-7fcf28799000 r--p 00817000 fd:01 6482355015                 /usr/lib/debug/usr/lib64/libc-2.17.so.debug
7fcf28799000-7fcf288c9000 rw-p 00000000 00:00 0
7fcf288c9000-7fcf288dd000 r--p 000bb000 fd:01 6482648870                 /usr/lib/debug/usr/lib64/libldap-2.4.so.2.10.2.debug
7fcf288dd000-7fcf288e9000 r--p 001ff000 fd:01 6482355023                 /usr/lib/debug/usr/lib64/libm-2.17.so.debug
7fcf288e9000-7fcf288f6000 r--p 00101000 fd:01 6482648778                 /usr/lib/debug/usr/lib64/libgssapi_krb5.so.2.2.debug
7fcf288f6000-7fcf28945000 r--p 00435000 fd:01 6482648731                 /usr/lib/debug/usr/lib64/libcrypto.so.1.0.1e.debug
7fcf28945000-7fcf28a6a000 rw-p 00000000 00:00 0
7fcf28a6a000-7fcf28a76000 r--p 000cc000 fd:01 6482648734                 /usr/lib/debug/usr/lib64/libssl.so.1.0.1e.debug
7fcf28a76000-7fcf28aac000 r--p 00332000 fd:01 6481563384                 /usr/lib/debug/usr/lib64/libxml2.so.2.9.1.debug
7fcf28aac000-7fcf28b13000 r--p 00524000 fd:01 5704253590                 /usr/pgsql-9.4/bin/postgres
7fcf28b13000-7fcf28b47000 r--p 0006d000 fd:01 6482355008                 /usr/lib/debug/usr/lib64/ld-2.17.so.debug
7fcf28b47000-7fcf28b97000 r--p 00001000 fd:01 6482355008                 /usr/lib/debug/usr/lib64/ld-2.17.so.debugAborted

**Comment by ringerc** [comment]
That's odd, you seem to have posted a backtrace of gdb its self, not of PostgreSQL, and in the form of a glibc memory error dump. Something might be badly wrong with this system if gdb its self is crashing when debugging a crashing program.

**Comment by ringerc** [comment]
I'm closing this, since there's been no follow-up.
