### ISSUE TITLE
BDR replication over SSL

### ISSUE THREAD

**Issue by lynchc** [2ndQuadrant/bdr#119]
I'm assuming I can't find much on this because everyone else already knows how to do this. Can someone point me in the direction of a good tutorial or leave me some pointers on this?

**Comment by martinmarques** [comment]
Hi,

BDR uses normal replication connections, so doing so over SSL involves the same steps as with Stream Replication, or normal libpq connections.

*) Configure your pg_hba.conf to accept replication connections
*) Add the appropriate sslmode=require parameter when creating the group and using bdr_init_copy

You will then see the sslmode=require in the connection lines in bdr.bdr_nodes and the connections will run over ssl

**Comment by lynchc** [comment]
Thanks
