### ISSUE TITLE
DROP of TEMPORARY table takes DDL lock unless table name is schema-qualified

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#124]
Version 0.10.0-2015-08-25-b17e62b

With DDL lock held on another node:

```
bdr_testdb=# CREATE TEMPORARY TABLE bob(id integer);
CREATE TABLE
bdr_testdb=# DROP TABLE bob;
ERROR:  database is locked against ddl by another node
HINT:  Node (6195732349873241211,1,16385) in the cluster is already performing DDL
```

**Comment by ringerc** [comment]
It seems to be an issue with unqualified `search_path` based lookups and caching.

In `bdr_commandfilter.c`, `statement_affects_only_nonpermanent`:

```
549						/* Can't be sure the next lookup will hit the same relation */
550						if (rv->schemaname == NULL)
551							return false;
```

Sure enough, schema-qualifying it works, but is ugly for temp tables.

```
bdr_testdb=# select nspname from pg_namespace n inner join pg_class c on (n.oid = c.relnamespace) where c.oid = 'bob'::regclass;
  nspname  
-----------
 pg_temp_8
(1 row)

bdr_testdb=# DROP TABLE pg_temp_8.bob;
DROP TABLE
```

**Comment by otaviofcs** [comment]
@ringerc , 

If you use 'bob'::regclass and the temporary table does not exists, it will throw an error.

I was able to implement it using:

```
select count(*) as cnt, max(nspname||'.bob') as complete_name into namespace_session_table from pg_namespace n inner join pg_class c on (n.oid = c.relnamespace) where relname = 'bob';
IF namespace_session_table.cnt > 0 THEN
EXECUTE 'DROP TABLE IF EXISTS '||namespace_session_table.complete_name;
END IF;
```
If count is greater than zero he drops the table using the namespace. Hope it helps.

**Comment by martinmarques** [comment]
Hi Otavio,

Your a better off selecting fro pg_class and using the special FOUND variable:

perform 1 from pg_class where relname = 'bob' and relpersistence = 't';
IF FOUND THEN;
      select nspname into namespace from pg_namespace n inner join pg_class c on (n.oid = c.relnamespace) where c.oid = 'bob'::regclass  and relpersistence = 't';
      EXECUTE 'DROP TABLE IF EXISTS '||namespace||'.bob';
END IF;

I guess you get the idea from that example (which you shouldn't use until it's polished ;))

P.D.: The relpersistence='t' is just so you don't get a non-temp table

See you,

**Comment by anarazel** [comment]
Hi,

On 2015-09-17 23:23:27 -0700, Craig Ringer wrote:
> It seems to be an issue with unqualified `search_path` based lookups and caching.
> 
> In `bdr_commandfilter.c`, `statement_affects_only_nonpermanent`:
> 
> ```
> 549						/* Can't be sure the next lookup will hit the same relation */
> 550						if (rv->schemaname == NULL)
> 551							return false;
> ```
> 
> Sure enough, schema-qualifying it works, but is ugly for temp tables.
> 
> ```
> bdr_testdb=# select nspname from pg_namespace n inner join pg_class c on (n.oid = c.relnamespace) where c.oid = 'bob'::regclass;
>   nspname  
> -----------
>  pg_temp_8
> (1 row)
> 
> bdr_testdb=# DROP TABLE pg_temp_8.bob;
> DROP TABLE
> ```

Maybe I'm missing something here, but why don't you just use pg_temp. as
the schema? That should always do the right thing? And it doesn't look
particularly ugly imo?

Andres

**Comment by PJMODOS** [comment]
Can't we just look the table up and lock it exclusively (obviously we can only lock it exclusively if it's a temp table)? It's going to be dropped so it will get locked exclusively later anyway and it would remove the lookup race condition.

**Comment by anarazel** [comment]
On 2016-05-02 02:50:41 -0700, Petr Jelinek wrote:
> Can't we just look the table up and lock it exclusively (obviously we
> can only lock it exclusively if it's a temp table)? It's going to be
> dropped so it will get locked exclusively later anyway and it would
> remove the lookup race condition.

An exclusive lock to a dropped table isn't very meaningful - it'll not
be acquired if gone from the search path.

**Comment by ringerc** [comment]
On 2 May 2016 at 22:23, Andres Freund <notifications@github.com> wrote:

> On 2016-05-02 02:50:41 -0700, Petr Jelinek wrote:
> > Can't we just look the table up and lock it exclusively (obviously we
> > can only lock it exclusively if it's a temp table)? It's going to be
> > dropped so it will get locked exclusively later anyway and it would
> > remove the lookup race condition.
>
> An exclusive lock to a dropped table isn't very meaningful - it'll not
> be acquired if gone from the search path.
>
>
Yeah.

This does seem to be one of the more frequently hit real world problems
though. Especially with reporting systems, scripts, etc. It's unfortunate
that DDL locking is asymmetric here, with creation of temp tables
problem-free but drop needing the DDL lock.

I'm aware that there are issues with search_path changes between the
commandfilter and execution of the deparse trigger, local execution of the
DDL and/or remote execution of the captured DDL. I'm not sure I understand
exactly how those can arise, though.

It sounds like you're saying that if we lock the table in the command
filter the search path could change and we might then find a different
table when actually executing the DDL. But is that actually reasonably
likely? I don't really see what's going to change the search path between
the command filter in ProcessUtility_hook and execution in
standard_ProcessUtility .

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment]
Petr fixed this some time ago.
