### ISSUE TITLE
How to replace a failed server

### ISSUE THREAD

**Issue by wreplicator** [2ndQuadrant/bdr#126]
I have set up a 2-node PG 9.4 system with BDR. Replication is working great.

Now, let's suppose that one of the two nodes needs to be replaced. In fact, let's be more specific. Let's say that the node on which I ran the command to create the group : SELECT bdr.bdr_group_create() has to be replaced.

What is the procedure to do this?

Do I build a new BDR server and join the remaining replica? But the remaining replica isn't where I created the group. Does that matter? I tried this. I didn't get any error but replication didn't work.

Do I build a new BDR server and do a bdr_init_copy? I tried this also. I got a copy of the remaining replica's db but replication didn't work in either direction.

Thanks

**Comment by ringerc** [comment]
On 19 September 2015 at 02:12, wreplicator <notifications@github.com> wrote:

> I have set up a 2-node PG 9.4 system with BDR. Replication is working
> great.
>
> Now, let's suppose that one of the two nodes needs to be replaced. In
> fact, let's be more specific. Let's say that the node on which I ran the
> command to create the group : SELECT bdr.bdr_group_create() has to be
> replaced.
>
> What is the procedure to do this?
>

bdr.bdr_part_by_node_names the failed server from the still-online server.

Join a new node.

> Do I build a new BDR server and join the remaining replica? But the
> remaining replica isn't where I created the group. Does that matter?
>
It does not matter.

> I tried this. I didn't get any error but replication didn't work.
>
Details? What commands did you run, on what nodes, in what order?

What do you see in the log files on each node?

What's in the bdr.bdr_nodes table on each node?

> Do I build a new BDR server and do a bdr_init_copy? I tried this also. I
> got a copy of the remaining replica's db but replication didn't work in
> either direction.
>

You must remove the failed node first.



-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by wreplicator** [comment]
Here are details of my attempt to rejoin a node to the an existing group.
1. Start with a two node cluster. Make sure replication is working both ways.
2. Shutdown the second node (10.35.29.223). This is the node to be replaced.
3. On node 1 (10.35.29.222), do a part: 
huysbdrdemo=# select bdr.bdr_part_by_node_names(ARRAY['10.35.29.223']);
 bdr_part_by_node_names
------------------------

(1 row)
huysbdrdemo=# select * from bdr.bdr_nodes;
     node_sysid      | node_timeline | node_dboid | node_status |  node_name   |                 node_local_dsn                 |
            node_init_from_dsn
---------------------+---------------+------------+-------------+--------------+------------------------------------------------+---
---------------------------------------------
 6195496652434463325 |             1 |      16385 | r           | 10.35.29.222 | host=10.35.29.222 port=5598 dbname=huysbdrdemo |
 6174755930384795483 |             1 |      16385 | k           | 10.35.29.223 | host=10.35.29.223 port=5598 dbname=huysbdrdemo | ho
st=10.35.29.222 port=5598 dbname=huysbdrdemo
(2 rows)

4. Rebuild node 2 and following the quick-start guide (http://bdr-project.org/docs/stable/quickstart.html) all the way to step 2.5, which is to createdb

5. On node 1 do:
huysbdrdemo=# select bdr.bdr_node_join_wait_for_ready();
 bdr_node_join_wait_for_ready
------------------------------

(1 row)

6. On node 2 do:
huysbdrdemo=# create extension btree_gist;
CREATE EXTENSION
huysbdrdemo=# create extension bdr;
CREATE EXTENSION
huysbdrdemo=# select bdr.bdr_group_join(local_node_name:='10.35.29.223', node_external_dsn:='host=10.35.29.223 port=5598 dbname=huysbdrdemo', join_using_dsn:='host=10.35.29.222 port=5598 dbname=huysbdrdemo');
 bdr_group_join
----------------

(1 row)
huysbdrdemo=# select * from bdr.bdr_nodes;
     node_sysid      | node_timeline | node_dboid | node_status |  node_name   |                 node_local_dsn                 |
            node_init_from_dsn
---------------------+---------------+------------+-------------+--------------+------------------------------------------------+---
---------------------------------------------
 6195496652434463325 |             1 |      16385 | r           | 10.35.29.222 | host=10.35.29.222 port=5598 dbname=huysbdrdemo |
 6174755930384795483 |             1 |      16385 | k           | 10.35.29.223 | host=10.35.29.223 port=5598 dbname=huysbdrdemo | ho
st=10.35.29.222 port=5598 dbname=huysbdrdemo
 6174757537032485053 |             1 |      16385 | c           | 10.35.29.223 | host=10.35.29.223 port=5598 dbname=huysbdrdemo | ho
st=10.35.29.222 port=5598 dbname=huysbdrdemo
(3 rows)


6. On node 1 do:
huysbdrdemo=# select * from bdr.bdr_nodes;
     node_sysid      | node_timeline | node_dboid | node_status |  node_name   |                 node_local_dsn                 |
            node_init_from_dsn
---------------------+---------------+------------+-------------+--------------+------------------------------------------------+---
---------------------------------------------
 6195496652434463325 |             1 |      16385 | r           | 10.35.29.222 | host=10.35.29.222 port=5598 dbname=huysbdrdemo |
 6174755930384795483 |             1 |      16385 | k           | 10.35.29.223 | host=10.35.29.223 port=5598 dbname=huysbdrdemo | ho
st=10.35.29.222 port=5598 dbname=huysbdrdemo
 6174757537032485053 |             1 |      16385 | i           | 10.35.29.223 | host=10.35.29.223 port=5598 dbname=huysbdrdemo | ho
st=10.35.29.222 port=5598 dbname=huysbdrdemo
(3 rows)

At this point, the two nodes show different status for node 2. Node 1 sees node 2 in 'i' state whereas node 2 sees itself in 'c' state.

The database started the same on both nodes but updates on one node does not get propagated to the other.

Logs on node 2 continuously show:

< 2015-09-21 11:36:07.009 EDT >LOG:  starting background worker process "bdr db: huysbdrdemo"
< 2015-09-21 11:36:07.069 EDT >ERROR:  System identification mismatch between connection and slot
< 2015-09-21 11:36:07.069 EDT >DETAIL:  Connection for bdr (6174755930384795483,1,16385,) resulted in slot on node bdr (6174757537032485053,1,16385,) instead of expected node
< 2015-09-21 11:36:07.070 EDT >LOG:  worker process: bdr db: huysbdrdemo (PID 7074) exited with exit code 1

**Comment by wreplicator** [comment]
?? why does this web page reformat my text ??

**Comment by ringerc** [comment]
@wreplicator When you use the web UI text is treated as markdown. Click the "markdown supported" button on the top right of the comment box to learn more. See the "preview" tab on the bar above the comment field? Use that.

This lets you format text more readably once you get the hang of it. See how I edited your prior comments?

**Comment by ringerc** [comment]
Ah, ok. This was fixed in 0.9.3, and 0.10.0, which are due for release soon. In the mean time you can work around this issue by deleting the bdr.bdr_nodes entry with the `k` status and the corresponding `bdr.bdr_connections` entry before you join the new node.

**Comment by wreplicator** [comment]
@ringerc: Superb reformatting job. Cheers!

I'm going to try your suggested work around. Mind letting me know how to delete the bdr_nodes entry and the bdr_connections entry?

**Comment by martinmarques** [comment]
2015-09-22 10:00 GMT-03:00 wreplicator <notifications@github.com>:
>
> @ringerc: Superb reformatting job. Cheers!
>
> I'm going to try your suggested work around. Mind letting me know how to delete the bdr_nodes entry and the bdr_connections entry?

Just like any other table, you delete the unwanted rows.

DELETE FROM bdr.bdr_nodes WHERE node_name = 'bad_node';
DELETE FROM bdr.bdr_connections WHERE conn_sysid = 'connection sysid';

Be careful, as the last one is not always unique, but it is if you
replicate only 1 DB. For insurance use the PK.

-- 
Martín Marqués                http://www.2ndQuadrant.com/
PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment]
I'd use a `delete from`, e.g.

```
delete from bdr.bdr_connections
using bdr.bdr_nodes
where node_state = 'k'
  and (node_sysid, node_timeline, node_dboid) = (conn_sysid, conn_timeline, conn_dboid)
```

then 

```
delete from bdr.bdr_nodes
where node_state = 'k'
```

**Comment by ringerc** [comment]
See also #50, #97
