### ISSUE TITLE
Can't DROP DATABASE even after parting a node, or on the last node

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#127]
We don't have a way to cleanly shut down BDR and remove it on a node.

Here's the manual process, in the mean time.

```
BEGIN;
SET LOCAL bdr.skip_ddl_locking = on;
SET LOCAL bdr.permit_unsafe_ddl_commands = on;
SET LOCAL bdr.skip_ddl_replication = on;
SECURITY LABEL FOR bdr ON DATABASE mydb IS NULL;
DELETE FROM bdr.bdr_connections;
DELETE FROM bdr.bdr_nodes;
SELECT bdr.bdr_connections_changed();
COMMIT;

SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = current_database() AND application_name LIKE '%): perdb';

DROP EXTENSION bdr;
```

... then remove 'bdr' from `shared_preload_libraries`.

**Comment by ringerc** [comment]
The right way to do this is probably in the perdb worker, in `bdr_maintain_db_workers()`, by detecting when we've terminated all the active workers and dropped all slots. Then drop the security label and change the node state.

**Comment by ringerc** [comment]
Bumped from 0.9.3; doing this right looks like it requires the addition of a "parted" state too, and it was going to require more testing than I had time for.

In production deployments it's typical to just destroy the whole PostgreSQL install when you part a node, if not the whole (usually virtual) machine. So it hasn't been a concern that it's fiddly to manually "de-BDR-ize" a database to date.

**Comment by jstuhli** [comment]
After doing this I'm stuck with:

2016-06-02 07:20:28 UTC LOG:  starting background worker process "bdr db: mydb"
2016-06-02 07:20:28 UTC ERROR:  bdr extension is not installed in the current database
2016-06-02 07:20:28 UTC LOG:  worker process: bdr db: mydb (PID 2213) exited with exit code 1

If I remove 'bdr' from shared_preload_libraries the errors go away, however I would like to start with a clean slate and setup UDR from scratch.
Is there a way to remove everything bdr related from my cluster, and to reinstall it?
