### ISSUE TITLE
no function bdr_unsubscribe for UDR

### ISSUE THREAD

**Issue by digoal** [2ndQuadrant/bdr#131]
NO function for this document describ:

UDR	bdr.bdr_unsubscribe(local_node_name)	void	Removes a previously created UDR subscription.

**Comment by ringerc** [comment]
This is being fixed in the coming 0.9.3 release. You can build from git in the mean time if needed.

The priority has been on BDR, and this issue with UDR got missed in the 0.9.2 release.

**Comment by ringerc** [comment]
See #39 . Pending for 0.9.3 release.
