### ISSUE TITLE
Issues while join cluster

### ISSUE THREAD

**Issue by lysenkooo** [2ndQuadrant/bdr#141]
Hello, I found one issue when I try to create multi-master cluster of two nodes. At first, I perform follow commands on the first node:

```
CREATE EXTENSION btree_gist;
CREATE EXTENSION bdr;
SELECT bdr.bdr_group_create(local_node_name := 'app01', node_external_dsn := 'host=192.168.33.101 port=5432 dbname=app_production user=app password=app');
```

Then I execute these two commands on second node:

```
/usr/pgsql-9.4/bin/pg_basebackup -d 'host=192.168.33.101 port=5432 dbname=app_production user=app password=app' -D /var/lib/pgsql/9.4-bdr/data -X stream
/usr/pgsql-9.4/bin/bdr_init_copy -d 'host=192.168.33.101 port=5432 dbname=app_production user=app password=app' -D /var/lib/pgsql/9.4-bdr/data --local-dbname='host=192.168.33.102 port=5432 dbname=app_production user=app password=app' -n app02
```

As a result I got hanged process, because forgot to execute `service postgresql-9.4 stop` on second node. Then I interrupt bdr_init_copy with ^C I can't stop postgresql service after. So I need to kill processes manually by pid from output of `ps aux | grep post` command.

I think bd_init_copy should make sure of that postgresql daemon is stopped before copying the process.

**Comment by ringerc** [comment]
That'd be pg_basebackup's job, really, rather than bdr_init_copy's.

Don't overwrite a running data directory. This isn't a bdr specific issue.
