### ISSUE TITLE
PL/R on BDR

### ISSUE THREAD

**Issue by tsykes** [2ndQuadrant/bdr#142]
New ticket since I didn't get back in time on ticket #118. If anyone is working on PL/R with BDR. I haven't been able to get it to work. I posted a gdb error in the original ticket but apparently didn't do it right.  If anyone is working on PL/R, I will help.

**Comment by ringerc** [comment]
Try downloading the PL/R SRPM from yum.postgresql.org and rebuilding it.
Does it work then? If so, we've presumably somehow broken binary
compatibility in the BDR packages.

**Comment by tsykes** [comment]
Craig,

Thanks so much for that suggestion. I rebuilt the SRPM and installed it and
it worked. No more crashing. Let me know if there is anything I can help
you with determining what was wrong with installing the binary pl/r RPM.

Todd

**Comment by ringerc** [comment]
On 17 November 2015 at 14:45, tsykes <notifications@github.com> wrote:

> Craig,
>
> Thanks so much for that suggestion. I rebuilt the SRPM and installed it and
> it worked. No more crashing. Let me know if there is anything I can help
> you with determining what was wrong with installing the binary pl/r RPM.


I'm glad that worked.

I'll need to investigate to see what possible differences there are in the
build between the BDR RPMs and the original 9.4 ones.


-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment]
I'm now confident I found a binary compatibility issue; see #42.
