### ISSUE TITLE
[ERROR:  duplicate key] Cannot Change node_sysid

### ISSUE THREAD

**Issue by srkunze** [2ndQuadrant/bdr#146]
I created LXD containers for an easy BDR setup. However, I found that BDR uses the PostgreSQL sysid, which is created at cluster creation. So far, I found no way to change that sysid later after I duplicated the containers. Thus, all BDR containers have the same sysid which leads to:

```
Nov 21 22:31:58 bdr postgres[744]: STATEMENT:  COPY bdr.bdr_nodes FROM stdin
Nov 21 22:31:58 bdr postgres[744]: ERROR:  duplicate key value violates unique constraint "bdr_nodes_pkey"
Nov 21 22:31:58 bdr postgres[744]: DETAIL:  Key (node_sysid, node_timeline, node_dboid)=(6218868612212977048, 1, 12187) already exists.
```

Is there a way to set the node_sysid in BDR?

The issue is I would like to have a super-easy setup for BDR (copy blueprint container, link it to BDR group, done). LXD's templates do not allow scripts (like re-creating the whole cluster when copying the container).
So, I am stuck with simple file replacement. Some ideas?

Btw. finding this error took quite some time as the original error message was hidden by:
```
Nov 21 22:32:03 bdr postgres[744]: DETAIL:  Found bdr.bdr_nodes entry for bdr (6218868612212977048,1,12187,) with state=i in remote bdr.bdr_nodes
Nov 21 22:32:03 bdr postgres[744]: HINT:  Remove all replication identifiers and slots corresponding to this node from the init target node then drop and recreate this database and try 
```
I would also appreciate a hint in the "HINT" to look further down at older error messages.

**Comment by srkunze** [comment]
Found it: `pg_resetxlog -s data`

However, I would really appreciate a more file-based configuration

**Comment by ringerc** [comment]
> I would also appreciate a hint in the "HINT" to look further down at older error messages.

That'd be true for every error in BDR. Or most systems, really. It'd be pretty noisy in the logs. Beyond emphasising it in the documentation I'm not sure what more we can do there.

> Found it: `pg_resetxlog -s data`

Yep. Though I don't understand why you don't just initdb each node separately, with whatever node management automation (puppet/chef/ansible/cloud-init/whatever) you are using.

> However, I would really appreciate a more file-based configuration

That's not going to happen.

We actually used to rely more on config files in 0.7.x. It's a nightmare. Cluster structure/topology changes require reconfiguration of all nodes. It's hard to reliably validate and sanity check. It's error prone and hard work for the admin. It requires server restarts on every server whenever you reconfigure anything. We're not going back there.

Having as much configuration as possible at the SQL level is a significant priority.

`pglogical` will take that further; it doesn't rely on the sysid anymore and you can change the identity of a node live, without a restart.

In your case what I recommend is duplicating the containers before you initdb. Then initdb after you clone them.

**Comment by ringerc** [comment]
I thought we checked for this case though - our sysid/timeline/dboid tuple already existing in the join target node.

Can you tell me more about the exact steps taken to get to this point?

It's possible an extra sanity check in `bdr_node_join` would help here by providing a better error message, immediately at join time, rather than having to rely on the logs. We try to `ERROR` out immediately for as many problem conditions as possible.

**Comment by srkunze** [comment]
> That'd be true for every error in BDR. Or most systems, really. It'd be pretty noisy in the logs. Beyond emphasising it in the documentation I'm not sure what more we can do there.

I would show the original error. Instead of just telling state=i, storing the error in the bdr_nodes table and printing that out.

> Yep. Though I don't understand why you don't just initdb each node separately, with whatever node management automation (puppet/chef/ansible/cloud-init/whatever) you are using.

Because I don't want to execute code (if possible none) on the new nodes. Just copy them and get them up. Otherwise, it's not only initdb, but also configuring postgresql, providing certificates, etc. It's error-prone scripting when a simple copy could suffice.

> pglogical will take that further; it doesn't rely on the sysid anymore and you can change the identity of a node live, without a restart.

That's an improvement. Right now, I need to start and enable the bdr service in the container AFTER I changed the sysid. Doing this live would be great. pglogical is the successor of BDR?

> We actually used to rely more on config files in 0.7.x. It's a nightmare.

I can understand that. It would just be great for the initial start up of the node. So, the node knows where to find its cluster. Then, I agree everything should be db-based.

**Comment by srkunze** [comment]
> Can you tell me more about the exact steps taken to get to this point?

I created a blueprint LXD container from which I created copies. Then I did `bdr_group_create` on the first copy, and `bdr_group_join` on all subsequent copies.

> It's possible an extra sanity check in bdr_node_join would help here by providing a better error message, immediately at join time, rather than having to rely on the logs. We try to ERROR out immediately for as many problem conditions as possible.

I would appreciate that. It really helps as the issue pops up immediately. No need to look into a second place (logfiles).

**Comment by ringerc** [comment]
On 24 November 2015 at 02:21, Sven R. Kunze <notifications@github.com>
wrote:

> That'd be true for every error in BDR. Or most systems, really. It'd be
> pretty noisy in the logs. Beyond emphasising it in the documentation I'm
> not sure what more we can do there.
>
> I would show the original error. Instead of just telling state=i, storing
> the error in the bdr_nodes table and printing that out.
>

If it was that easy we'd do it. It isn't.

Writing to the database from an error handler isn't simple to do, nor is it
well supported.

Yep. Though I don't understand why you don't just initdb each node
> separately, with whatever node management automation
> (puppet/chef/ansible/cloud-init/whatever) you are using.
>
> Because I don't want to execute code (if possible none) on the new nodes.
> Just copy them and get them up.
>

"execute code"? I'm guessing you mean "run additional custom scripting
steps".

> Otherwise, it's not only initdb, but also configuring postgresql,
> providing certificates, etc. It's error-prone scripting when a simple copy
> could suffice.
>

Use one of the many well-established automation tools like Ansible, Puppet,
Chef, Salt, Cloud-init, etc.

You can't really expect to clone a node and have it automagically find its
peers and know what to connect to. So you're doing some kind of post-clone
scripting anyway.

> pglogical will take that further; it doesn't rely on the sysid anymore and
> you can change the identity of a node live, without a restart.
>
> That's an improvement. Right now, I need to start and enable the bdr
> service in the container AFTER I changed the sysid. Doing this live would
> be great. pglogical is the successor of BDR?
>

Sort-of.

We've taken some of the core functionality from BDR - the logical decoding
plugin and the basics of the replication apply engine. Stripped out DDL
replication, multimaster, DDL locking, global sequences, etc to get a
simple replication solution. Like UDR, but with the lessons we've learned
from BDR/UDR development. Designed to be much more modular and with more
flexible catalogs.

So you can't replace BDR with pglogical. Of course, we're not dropping BDR;
instead, we'll be rebuilding BDR around pglogical, so it becomes an add-on
layer/module that adds full multi-master support. This is fairly long term,
so don't expect significant changes in the near future; at the soonest I'd
expect to be in beta around when PostgreSQL 9.6 is released.

We'll be maintaining BDR on 9.4 for a long time yet.

The pglogical output plugin has been submitted as a candidate for inclusion
into 9.6. Hopefully the downstream can be too, in the next commitfest cycle.

> We actually used to rely more on config files in 0.7.x. It's a nightmare.
>
> I can understand that. It would just be great for the initial start up of
> the node. So, the node knows where to find its cluster. Then, I agree
> everything should be db-based.
>

I think you are trying to replace one problem with another. To avoid
post-clone setup on your containers you're trying to add complex
workarounds to the tools. Don't do that; instead, use any of the numerous
well-established tools around to help you do post-clone setup simply and
reliably.



-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment]
On 24 November 2015 at 02:25, Sven R. Kunze <notifications@github.com>
wrote:

> Can you tell me more about the exact steps taken to get to this point?
>
> I created a blueprint LXD container from which I created copies. Then I
> did bdr_group_create on the first copy, and bdr_group_join on all
> subsequent copies.
>

I can't really do anything with that.

If you can supply an exact step-by-step process to reproduce the error,
preferably without relying on LXC, let me know. Exact commands, command
arguments, etc.

Or a patch to add the appropriate sanity check, of course. Patches are
always welcome.

Otherwise I'll consider this closed at this point, though I'll see if I can
reproduce the error in a few simple configurations if time permits.


-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by srkunze** [comment]
> If it was that easy we'd do it. It isn't.
> Writing to the database from an error handler isn't simple to do, nor is it well supported.

I didn't know. I thought a venerable software product like PostgreSQL developed such measures over time in order find error as soon as possible.

> You can't really expect to clone a node and have it automagically find its peers and know what to connect to.

I tend to disagree on this point as my experience with peer-to-peer networks tells me otherwise. A new node simply needs a **set of nodes of the existing cluster** to join in.

Peer-to-peer networks deal with much greater uncertainty regarding authenticity and data integrity etc. whereas a BDR cluster normally runs in a controlled environment.

> So you're doing some kind of post-clone scripting anyway.

I also tend to disagree here. Assuming I need to create a new db cluster, I would then, e.g., take the BDR base container and inject the initial IP(s) (available via the cloud provider etc.). I could **then clone** the container 30x and distribute them over the instances I have and they already know where to find its initial peer. I am all set.

> Use one of the many well-established automation tools like Ansible, Puppet, Chef, Salt, Cloud-init, etc.

As I have some experience with those tools as well, my gut-feeling here is that they should do as little setup and configuration of the service as possible and from time to time they are responsible for re-scaling the application (adding/removing nodes).

In order to put it differently: peer-to-peer nodes should be able to handle themselves whereas automation tools should focus on clusters, not on singe nodes within a cluster.

**Comment by srkunze** [comment]
> The pglogical output plugin has been submitted as a candidate for inclusion into 9.6. Hopefully the downstream can be too, in the next commitfest cycle.

Besides all the discussion here, I would like to **thank you** for your commitment. PostgreSQL still needs solutions in this area.

**Comment by srkunze** [comment]
> If you can supply an exact step-by-step process to reproduce the error, preferably without relying on LXC, let me know. Exact commands, command arguments, etc.

Not sure but I think I have an idea. Copying the data directory after the cluster has been created and then trying to setup a BDR group. I will get back to you.

**Comment by ringerc** [comment]
> As I have some experience with those tools as well, my gut-feeling here
is that they should do as little setup and configuration of the service as
possible and from time to time they are responsible for re-scaling the
application (adding/removing nodes)
>
> In order to put it differently: peer-to-peer nodes should be able to
handle themselves whereas automation tools should focus on clusters, not on
singe nodes within a cluster.
So you're looking for dynamic node discovery, autoscaling, reprovisioning,
etc.

This isn't the same when dealing with a relational DBMS as it is with
Bittorrent or whatever. Schema changes, consistency, transactions, etc all
play a part.

It's not impossible, but I'd it'd require roughly the same amount of time
and effort already put into BDR​ all over again to add reliable and robust
auto-discovery, automatic failed node removal, lockless concurrent node
join, etc. Feel free to prototype this based on the existing BDR code base.

I consider this issue closed at this point. If you want to get involved in
development you should study the source code and then come up with a
detailed plan for how you're going to implement what you propose, with
clear definitions of all states and state transitions, protocol changes,
etc. I will not be pursuing it myself.
