### ISSUE TITLE
Database locked against DDL by another node in BDR

### ISSUE THREAD

**Issue by jcnleejohn** [2ndQuadrant/bdr#148]
I have successfully created 2 nodes running "postgresql-bdr94" (v9.4.2) and BDR (v0.9.1).

postgresql-bdr94-libs-9.4.2_bdr1-1_2ndQuadrant.el6.x86_64
postgresql-bdr94-bdr-0.9.1-1_2ndQuadrant.el6.x86_64
postgresql-bdr94-9.4.2_bdr1-1_2ndQuadrant.el6.x86_64
postgresql-bdr94-contrib-9.4.2_bdr1-1_2ndQuadrant.el6.x86_64
postgresql-bdr94-server-9.4.2_bdr1-1_2ndQuadrant.el6.x86_64

At one node, packages (whose functions have return type TRIGGER) and triggers are created. They can be replicated to another node without any problem. One of the functions in the package is attached below for reference.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE OR REPLACE
    FUNCTION PKG_TGR_MGT.TGR_SYS_FUNCNODETBL_01 (
    )
    RETURNS TRIGGER AS $$
    BEGIN
        -- System Function Selection Node Details Table
        PERFORM PKG_ADM_MGT_ACCOUNT.InsertFuncNodeList(
            new.NODENAME,
            new.PROJSHTNAMELIST,
            new.CMDNOUNLIST,
            new.CMDVERBLIST
        );
        RETURN new;
    END;
    $$ LANGUAGE plpgsql;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
However, when the package is dropped at one node using "DROP SCHEMA IF EXISTS PKG_TGR_MGT", it cannot be created again in next CREATE. The rejection is something like below.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR:  database is locked against ddl by another node
HINT:  Node (6158090345987221693,1,17189) in the cluster is already 
performing DDL
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I was not able to recover the situation even after stopping and starting postgreSQL at both nodes. One possible way is to drop and create the database again, but it should not be like that when the database is in production.

**Comment by ringerc** [comment]
Does the same issue occur when running 0.9.3?

Please examine the log files on both nodes to see if there's anything
interesting or relevant.

**Comment by jcnleejohn** [comment]
The latest version of RPM available in CentOS 6 x86_64 are the following only (http://packages.2ndquadrant.com/postgresql-bdr94-2ndquadrant/yum/centos-6-x86_64/repoview/). There is no 0.9.3 for BDR.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2015-05-26: postgresql94-udr-0.9.1-1_2ndQuadrant.el6
    2015-05-26: postgresql94-udr-debuginfo-0.9.1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-bdr-0.9.1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-bdr-debuginfo-0.9.1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-9.4.2_bdr1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-contrib-9.4.2_bdr1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-debuginfo-9.4.2_bdr1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-devel-9.4.2_bdr1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-docs-9.4.2_bdr1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-libs-9.4.2_bdr1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-plperl-9.4.2_bdr1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-plpython-9.4.2_bdr1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-pltcl-9.4.2_bdr1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-server-9.4.2_bdr1-1_2ndQuadrant.el6
    2015-05-26: postgresql-bdr94-test-9.4.2_bdr1-1_2ndQuadrant.el6
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jcnleejohn** [comment]
Finally I can download the latest version v9.4.5 with BDR v0.9.3, and the issue is fixed.
~~~~~~~~~~~~~~~~~~~~~~~~~~
postgresql-bdr94-9.4.5_bdr1-1_2ndQuadrant.el6.x86_64.rpm
postgresql-bdr94-bdr-0.9.3-1_2ndQuadrant.el6.x86_64.rpm
postgresql-bdr94-contrib-9.4.5_bdr1-1_2ndQuadrant.el6.x86_64.rpm
postgresql-bdr94-libs-9.4.5_bdr1-1_2ndQuadrant.el6.x86_64.rpm
postgresql-bdr94-server-9.4.5_bdr1-1_2ndQuadrant.el6.x86_64.rpm
~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ringerc** [comment]
At a guess your yum cache was outdated.​ Nothing has changed in the
repository.

I didn't get a chance to follow up earlier, sorry.
