### ISSUE TITLE
Documentation coverage of all BDR functions

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#15]
The docs need to cover all the functions we expose

**Comment by ringerc** [comment]
Note management functions are skeletally covered in a table, minimal description. No other functions covered yet.

**Comment by ringerc** [comment]
All functions now have table entries, not detailed descriptions yet.

**Comment by ringerc** [comment]
Done as much as possible for this release, bumping. Not many have detailed descriptions.

**Comment by PJMODOS** [comment]
Do we actually need these documentation tasks?
