### ISSUE TITLE
Document use of pg_upgrade

### ISSUE THREAD

**Issue by eradman** [2ndQuadrant/bdr#151]
There appear to be a number of manual steps required to enable `pg_upgrade`.
First I created a copy of a snapshot taken with `pg_basebackup`, then tried to
run `pg_upgrade`:

    $ rsync -a dbhost1/ dbhost1.A
    $ rsync -a dbhost1/ dbhost1.B
    $ /usr/pgsql-9.4/bin/pg_upgrade -b /usr/pgsql-9.4-bdr/bin -B /usr/pgsql-9.4/bin -d dbhost1.B -D dbhost1.A`
    $ /usr/pgsql-9.4-bdr/bin/pg_ctl -D dbhost1.B start

I noticed that some folder are missing and created them

    $ mkdir dbhost1.A/pg_logical/{checkpoints,snapshots,mappings}

After a restart I found that some some system entries required by postgres-bdr are missing

    < 2015-12-18 16:32:32.458 EST >FATAL:  could not open relation with OID 6000

It's not clear how to install these system tables

    test=# select relname,oid from pg_class where relname ~ 'pg_replication' order by oid;
                     relname                  |  oid  
    ------------------------------------------+-------
     pg_replication_identifier                |  6000
     pg_replication_identifier_riiident_index |  6001
     pg_replication_identifier_riname_index   |  6002
     pg_replication_slots                     | 11293
     pg_replication_identifier_progress       | 11320
    (5 rows)

Only `pg_replication_slots` appears in my stock 9.4.5 install

**Comment by eradman** [comment]
After further experimentation with a 3-node BDR cluster I think I can answer this myself. Logical replication has a lot of moving parts, and it seems best to use dump/restore to minimize surprises.

**Comment by ringerc** [comment]
To use pg_upgrade for what, exactly?

It's not clear what you are trying to accomplish here. Are you trying to
take a standalone PostgreSQL 9.4 and switch to the BDR-patched 9.4? If so,
that's not supported. pg_upgrade doesn't know how to add commit timestamp
information etc. You will need to dump and restore.

It'll be possible to pg_upgrade from normal 9.4 to BDR once we get a
9.6-based BDR out, but that's still a long time coming.

**Comment by eradman** [comment]
Yes, I was foolishly trying to upgrade a basebackup of a standalone 9.4 database and switch to bdr-patched 9.4.
