### ISSUE TITLE
Solo Node - cannot acquire DDL lock

### ISSUE THREAD

**Issue by esnellman** [2ndQuadrant/bdr#153]
I am experiencing
"ERROR:  No peer nodes or peer node count unknown, cannot acquire DDL lock"

Could this be because I created the group with a external node_external_dsn host value matching my ip address?  I did notice that during creation it connected to itself...

      PERFORM bdr.bdr_group_create(
        local_node_name := 'node{{item[0]}}',
        node_external_dsn := 'host={{item[0]}} port={{item[1]}} dbname=example'
      );

SELECT * FROM bdr.bdr_nodes

node_sysid      | node_timeline | node_dboid | node_status |   node_name    |            node_local_dsn             | node_init_from_dsn
 6214214590456620012 |             1 |      16386 | r           | node45.79.1.80 | host=45.79.1.80 port=5598 dbname=example |

I think I am using the latest bits
        bdr_version
---------------------------
 0.9.3-2015-10-21-718ee775

Thanks,
Eric

**Comment by esnellman** [comment]
Turned out to be a issues with certs.  I ended up having to set values for sslkey= sslcert= in the node_external_dsn string and in the later group join  join_using_dsn string

**Comment by ringerc** [comment]
Standalone nodes aren't expected to work.​ This should probably be
documented more clearly. Time's pretty limited right now, so patches there
would be welcomed.

**Comment by esnellman** [comment]
Interesting.  Do I need to sign an agreement or something to contribute
documentation?

**Comment by ringerc** [comment]
No. Nor code. BDR is under the PostgreSQL license. PostgreSQL doesn't
require a CLA so neither do we.
