### ISSUE TITLE
issue using vacuumdb with -a option

### ISSUE THREAD

**Issue by gbroccolo** [2ndQuadrant/bdr#154]
Hi,

The vacuumdb tool breaks on bdr environment, due to the presence of the  bdr_supervisordb database:

~$ vacuumdb -v -z -a
vacuumdb: vacuuming database "bdr_supervisordb"
vacuumdb: could not connect to database bdr_supervisordb: FATAL:  The BDR extension reserves the database bdr_supervisordb for its own use
HINT:  Use a different database

Can this be managed avoiding that the error is raised?

**Comment by ringerc** [comment]
Good point there.

We should probably allow connections to bdr_supervisordb after all, then,
and just ERROR whenever the user tries to actually do anything except
SELECT or VACUUM.

This could possibly cause issues with xid wraparound as-is. Unsure.

**Comment by PJMODOS** [comment]
Yup agree, let's allow connections there.

**Comment by amenonsen** [comment]
Any updates here?

**Comment by ringerc** [comment]
Nope, been busy on failover slots, pglogical, etc. Needs to be fixed for 0.10.0 though.

**Comment by ringerc** [comment]
I don't think that will actually fix it; it should've been failing in the client authentication hook.
