### ISSUE TITLE
Issues with sysid

### ISSUE THREAD

**Issue by eloycoto** [2ndQuadrant/bdr#155]
Hi, 

We use to deploy our DB servers based on templates. So the main problem that we have is that nodes has always the same sysid. Like this: 

Node01:
```
xpbx=# select bdr.bdr_get_local_nodeid();
     bdr_get_local_nodeid
-------------------------------
 (6234401232683047118,1,16398)
```

Node02:
```
xpbx=# select bdr.bdr_get_local_nodeid();
     bdr_get_local_nodeid
-------------------------------
 (6234401232683047118,1,16398)
```

Any method to reset the nodeid? Can be possible? 

Regards.

**Comment by moench-tegeder** [comment]
BDR itself faces the very same problem when creating a new node from a base backup (bdr_init_copy), so of course we have a solution for that, and it's user-accessable, too.
Please see the bdr_resetxlog utility, you'll need option "-s", everything else is just like pg_resetxlog.

**Comment by ringerc** [comment]
BTW, pglogical moves away from using sysid, partly for this reason.
