### ISSUE TITLE
Problem installing BDR packages on ubuntu 14.04

### ISSUE THREAD

**Issue by rvanlaar** [2ndQuadrant/bdr#156]
I can't install BDR on ubuntu 14.04.

The error during the installation is:

/var/lib/dpkg/info/postgresql-bdr-9.4.postinst: 95: /var/lib/dpkg/info/postgresql-bdr-9.4.postinst: db_stop: not found

It seems that the file "/usr/share/debconf/confmodule" is not included.

The steps to set it up on a clean ubuntu 14.04:

wget -qO - http://packages.2ndquadrant.com/bdr/apt/AA7A6805.asc |sudo apt-key add -
wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc |sudo apt-key add -
sudo add-apt-repository 'deb http://packages.2ndquadrant.com/bdr/apt/ trusty-2ndquadrant main'
sudo add-apt-repository 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
sudo apt-get update
sudo apt-get upgrade

And install it:
$ sudo apt-get install postgresql-bdr-9.4-bdr-plugin
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-3.13.0-57 linux-headers-3.13.0-57-generic
  linux-headers-3.13.0-61 linux-headers-3.13.0-61-generic
  linux-image-3.13.0-57-generic linux-image-3.13.0-61-generic
  linux-image-extra-3.13.0-57-generic linux-image-extra-3.13.0-61-generic
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libpq5 libxslt1.1 pgdg-keyring postgresql-bdr-9.4 postgresql-bdr-client-9.4
  postgresql-bdr-contrib-9.4 postgresql-client-common postgresql-common
  ssl-cert
Suggested packages:
  oidentd ident-server locales-all postgresql-bdr-doc-9.4 libdbd-pg-perl
  openssl-blacklist
The following NEW packages will be installed:
  libpq5 libxslt1.1 pgdg-keyring postgresql-bdr-9.4
  postgresql-bdr-9.4-bdr-plugin postgresql-bdr-client-9.4
  postgresql-bdr-contrib-9.4 postgresql-client-common postgresql-common
  ssl-cert
0 upgraded, 10 newly installed, 0 to remove and 3 not upgraded.
Need to get 5,995 kB of archives.
After this operation, 28.4 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://mirrors.digitalocean.com/ubuntu/ trusty/main libxslt1.1 amd64 1.1.28-2build1 [145 kB]
Get:2 http://mirrors.digitalocean.com/ubuntu/ trusty/main ssl-cert all 1.0.33 [16.6 kB]
Get:3 http://packages.2ndquadrant.com/bdr/apt/ trusty-2ndquadrant/main postgresql-bdr-client-9.4 amd64 9.4.5-1trusty [1,068 kB]
Get:4 http://packages.2ndquadrant.com/bdr/apt/ trusty-2ndquadrant/main postgresql-bdr-9.4 amd64 9.4.5-1trusty [3,677 kB]
Get:5 http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg/main libpq5 amd64 9.4.5-1.pgdg14.04+1 [122 kB]
Get:6 http://packages.2ndquadrant.com/bdr/apt/ trusty-2ndquadrant/main postgresql-bdr-contrib-9.4 amd64 9.4.5-1trusty [443 kB]
Get:7 http://packages.2ndquadrant.com/bdr/apt/ trusty-2ndquadrant/main postgresql-bdr-9.4-bdr-plugin amd64 0.9.3-1trusty [230 kB]
Get:8 http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg/main pgdg-keyring all 2014.1 [5,898 B]
Get:9 http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg/main postgresql-client-common all 171.pgdg14.04+1 [76.6 kB]
Get:10 http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg/main postgresql-common all 171.pgdg14.04+1 [210 kB]
Fetched 5,995 kB in 1s (4,540 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libpq5:amd64.
(Reading database ... 146095 files and directories currently installed.)
Preparing to unpack .../libpq5_9.4.5-1.pgdg14.04+1_amd64.deb ...
Unpacking libpq5:amd64 (9.4.5-1.pgdg14.04+1) ...
Selecting previously unselected package libxslt1.1:amd64.
Preparing to unpack .../libxslt1.1_1.1.28-2build1_amd64.deb ...
Unpacking libxslt1.1:amd64 (1.1.28-2build1) ...
Selecting previously unselected package pgdg-keyring.
Preparing to unpack .../pgdg-keyring_2014.1_all.deb ...
Unpacking pgdg-keyring (2014.1) ...
Selecting previously unselected package postgresql-client-common.
Preparing to unpack .../postgresql-client-common_171.pgdg14.04+1_all.deb ...
Unpacking postgresql-client-common (171.pgdg14.04+1) ...
Selecting previously unselected package postgresql-bdr-client-9.4.
Preparing to unpack .../postgresql-bdr-client-9.4_9.4.5-1trusty_amd64.deb ...
Unpacking postgresql-bdr-client-9.4 (9.4.5-1trusty) ...
Selecting previously unselected package ssl-cert.
Preparing to unpack .../ssl-cert_1.0.33_all.deb ...
Unpacking ssl-cert (1.0.33) ...
Selecting previously unselected package postgresql-common.
Preparing to unpack .../postgresql-common_171.pgdg14.04+1_all.deb ...
Adding 'diversion of /usr/bin/pg_config to /usr/bin/pg_config.libpq-dev by postgresql-common'
Unpacking postgresql-common (171.pgdg14.04+1) ...
Selecting previously unselected package postgresql-bdr-9.4.
Preparing to unpack .../postgresql-bdr-9.4_9.4.5-1trusty_amd64.deb ...
Unpacking postgresql-bdr-9.4 (9.4.5-1trusty) ...
Selecting previously unselected package postgresql-bdr-contrib-9.4.
Preparing to unpack .../postgresql-bdr-contrib-9.4_9.4.5-1trusty_amd64.deb ...
Unpacking postgresql-bdr-contrib-9.4 (9.4.5-1trusty) ...
Selecting previously unselected package postgresql-bdr-9.4-bdr-plugin.
Preparing to unpack .../postgresql-bdr-9.4-bdr-plugin_0.9.3-1trusty_amd64.deb ...
Unpacking postgresql-bdr-9.4-bdr-plugin (0.9.3-1trusty) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up libpq5:amd64 (9.4.5-1.pgdg14.04+1) ...
Setting up libxslt1.1:amd64 (1.1.28-2build1) ...
Setting up pgdg-keyring (2014.1) ...
Removing apt.postgresql.org key from trusted.gpg: OK
Importing apt.postgresql.org key: OK
Setting up postgresql-client-common (171.pgdg14.04+1) ...
Setting up postgresql-bdr-client-9.4 (9.4.5-1trusty) ...
Setting up ssl-cert (1.0.33) ...
Setting up postgresql-common (171.pgdg14.04+1) ...
Adding user postgres to group ssl-cert

Creating config file /etc/postgresql-common/createcluster.conf with new version

Creating config file /etc/logrotate.d/postgresql-common with new version
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Removing obsolete dictionary files:
 * No PostgreSQL clusters exist; see "man pg_createcluster"
Processing triggers for ureadahead (0.100.0-16) ...
Setting up postgresql-bdr-9.4 (9.4.5-1trusty) ...
Creating new cluster 9.4/main ...
  config /etc/postgresql/9.4/main
  data   /var/lib/postgresql/9.4/main
  locale en_US.UTF-8
  port   5432
/var/lib/dpkg/info/postgresql-bdr-9.4.postinst: 95: /var/lib/dpkg/info/postgresql-bdr-9.4.postinst: db_stop: not found
dpkg: error processing package postgresql-bdr-9.4 (--configure):
 subprocess installed post-installation script returned error exit status 127
dpkg: dependency problems prevent configuration of postgresql-bdr-contrib-9.4:
 postgresql-bdr-contrib-9.4 depends on postgresql-bdr-9.4 (= 9.4.5-1trusty); however:
  Package postgresql-bdr-9.4 is not configured yet.

dpkg: error processing package postgresql-bdr-contrib-9.4 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of postgresql-bdr-9.4-bdr-plugin:
 postgresql-bdr-9.4-bdr-plugin depends on postgresql-bdr-9.4; however:
  Package postgresql-bdr-9.4 is not configured yet.
 postgresql-bdr-9.4-bdr-plugin depends on postgresql-bdr-contrib-9.4; however:
  Package postgresql-bdr-contrib-9.4 is not configured yet.

dpkg: error processing package postgresql-bdr-9.4-bdr-plugin (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
No apport report written because the error message indicates its a followup error from a previous failure.
 No apport report written because the error message indicates its a followup error from a previous failure.
  Errors were encountered while processing:
 postgresql-bdr-9.4
 postgresql-bdr-contrib-9.4
 postgresql-bdr-9.4-bdr-plugin
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by rvanlaar** [comment]
When trying to fix this issue I ran into three other problems:
- There is no documentation where the debian build repository is
- There are no debian source packages available
- There is no source tarball available

I found the debian repository here: https://github.com/2ndQuadrant/bdr-packaging/tree/debian/bdr-pg-9.4.5
I couldn't build a debian package because it needs a source tarball:
$ dpkg-buildpackage -us -uc
<snip>
`
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../postgresql-bdr-9.4_9.4.5.orig.tar.{bz2,gz,lzma,xz}
`

**Comment by PJMODOS** [comment]
This is problem with postgresql-common 171 package from pgdg, all debian postgresql distributions have been affected, the package has been since fixed and upgraded to 172 and 171 was removed from repo.

We don't have debian source packages in the repository.

**Comment by rvanlaar** [comment]
I'm using postgresql-common: Version: 172.pgdg14.04+1 

This is still an issue an not fixed.

**Comment by lbdremy** [comment]
I'm having the exact same issue, I'm also using `postgresql-common: Version: 172.pgdg14.04+1

` but it is not working.

Thanks for your help.

**Comment by rvlander** [comment]
Same problem here.

**Comment by lbdremy** [comment]
Since the issue is coming from the fact that the command `db_stop` is not found. I have just added a fake executable named `db_stop` to fake the command exists. That's ugly but it works around the problem. Who is supposed to install this utility ?

**Comment by PJMODOS** [comment]
Okay, sorry, so there were multiple issues, the one fixed in 172 wasn't the one you had, I thought it was based on the log you provided.

The do_stop is not command, but function provided by debian install scripts, it's just that the logic for including those scripts in the new postgresql-common is really not compatible with postgresql-bdr package naming. I built new packages which work around this. So apt-get update and try install again please.

**Comment by rvanlaar** [comment]
This issue is fixed. 

Running apt-get update and installing postgres bdr continues and doesn't result in an error anymore.

**Comment by kxxoling** [comment]
Upgrading to 172.pgdg14.04+1 fixed my issue. Thanks!
