### ISSUE TITLE
BDR on PostgreSQL 9.5

### ISSUE THREAD

**Issue by sebastianwebber** [2ndQuadrant/bdr#157]
Hi there,

Its possible use BDR on PostgreSQL 9.5? 

How can I install it?

Thanks.

**Comment by rvanlaar** [comment]
BDR is specifically for 9.4. So, no.

**Comment by sebastianwebber** [comment]
@rvanlaar ,

Any plans to use it on 9.5 as a regular extension?

**Comment by moench-tegeder** [comment]
http://www.postgresql.org/message-id/CANP8+jJ6DwgNaSXsxkqOyC=w8wB5PYm4qLyimbzG_Coh4V1OUA@mail.gmail.com

**Comment by sebastianwebber** [comment]
Thanks @moench-tegeder !

**Comment by ringerc** [comment]
At this point we plan to skip 9.5 and release an updated BDR built around pglogical that'll run on an unmodified 9.6 server. That's one less variant to support while trying to push development forward.

As with most things this may vary based on the requirements of the customers who're supporting and driving BDR development.
