### ISSUE TITLE
"Locked against DDL operations" is misleading

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#160]
The "Locked against DDL operations" message is misleading. We should preferably say "Locked against writes because of in-progress DDL on another node" or something.

Per  #159

Also need to make it clearer in the ddl locking docs why we lcok against concurrent ops, that that locking includes concurrent dml, etc.

**Comment by PJMODOS** [comment]
This message actually shouldn't exist in master any more, at least not for DML
