### ISSUE TITLE
In table bdr.bdr_nodes node_status keeps being "initializing" for one node

### ISSUE THREAD

**Issue by pierre-sion** [2ndQuadrant/bdr#161]
Hello,

I am using BDR 0.9.3. I have a setup with 2 nodes, say node1 and node2. 
The BDR group was created from node1. When node2 joined the group, a conflict was registered in the bdr.bdr_conflict_history table:

conflict_id              | 1
local_node_sysid         | 6241795782928356619
local_conflict_xid       | 1837
local_conflict_lsn       | 0/1ABF9E0
local_conflict_time      | 2016-01-20 11:05:49.869761+01
object_schema            | bdr
object_name              | bdr_nodes
remote_node_sysid        | 6241795796634624909
remote_txid              | 1857
remote_commit_time       | 2016-01-20 11:05:42.242831+01
remote_commit_lsn        | 0/1C53100
conflict_type            | update_update
conflict_resolution      | last_update_wins_keep_local
local_tuple              | {"node_sysid":"6241795796634624909","node_timeline":"1","node_dboid":"17935","node_status":"i","node_name":"node2","node_local_dsn":"host=172.26.2.95 port=5432 db
name=bdrdemo","node_init_from_dsn":"host=172.26.2.94 port=5432 dbname=bdrdemo"}
remote_tuple             | {"node_sysid":"6241795796634624909","node_timeline":"1","node_dboid":"17935","node_status":"r","node_name":"node2","node_local_dsn":"host=172.26.2.95 port=5432 db
name=bdrdemo","node_init_from_dsn":"host=172.26.2.94 port=5432 dbname=bdrdemo"}
local_tuple_xmin         | 1832

As as result, the node_status of bdr.bdr_nodes is inconsistent between node1 and node2.

**From node1:**
bdrdemo=# select * from bdr.bdr_nodes;
-[ RECORD 1 ]------+------------------------------------------
node_sysid         | 6241795782928356619
node_timeline      | 1
node_dboid         | 16385
node_status        | r
node_name          | node1
node_local_dsn     | host=172.26.2.94 port=5432 dbname=bdrdemo
node_init_from_dsn |
-[ RECORD 2 ]------+------------------------------------------
node_sysid         | 6241795796634624909
node_timeline      | 1
node_dboid         | 17935
**node_status        | i**
node_name          | node2
node_local_dsn     | host=172.26.2.95 port=5432 dbname=bdrdemo
node_init_from_dsn | host=172.26.2.94 port=5432 dbname=bdrdemo

**From node2:**
bdrdemo=# select * from bdr.bdr_nodes;
-[ RECORD 1 ]------+------------------------------------------
node_sysid         | 6241795782928356619
node_timeline      | 1
node_dboid         | 16385
node_status        | r
node_name          | node1
node_local_dsn     | host=172.26.2.94 port=5432 dbname=bdrdemo
node_init_from_dsn |
-[ RECORD 2 ]------+------------------------------------------
node_sysid         | 6241795796634624909
node_timeline      | 1
node_dboid         | 17935
**node_status        | r**
node_name          | node2
node_local_dsn     | host=172.26.2.95 port=5432 dbname=bdrdemo
node_init_from_dsn | host=172.26.2.94 port=5432 dbname=bdrdemo

From node1's perspective, the status of node2 keeps being "initializing".
From node2's perspective, the status of node2 is "ready" (correct).

I restarted PostgreSQL on both nodes, but to no avail; the content of bdr.bdr_nodes remains incoherent.

This does not prevent the replication from working correctly.

Thank you for your attention,
Best regards,
Pierre Sion

**Comment by PJMODOS** [comment]
Thanks, yes this is known issue during initialization. As you say it should not prevent BDR from working correctly, but we will fix it in next release.

**Comment by mz407f** [comment]
I've noticed the same thing.  Is there a work around?  Can we simply update bdr.bdr_nodes.node_status to 'r'?  How can we tell that a given node is truly 'r'?

**Comment by ujae7142** [comment]
I have similar situation, is there any workaround?

**Comment by dpitard** [comment]
We occasionally see this as well.  The member node never gets past "joining: initial sync (3/5)" but there does not seem to otherwise be a problem.

We are using version 1.0.5:
select * from bdr.bdr_version();
    bdr_version
-------------------
 1.0.5-2018-03-12-
(1 row)
