### ISSUE TITLE
BDR deb versions

### ISSUE THREAD

**Issue by eloycoto** [2ndQuadrant/bdr#167]
Hi, 

I've just realised that the version are not equal from here that the deb server. In the deb server the bdr-plugin is postgresql-bdr-9.4-bdr-plugin_0.9.3-1*, there is any method to create deb packages from source? 

Regards

**Comment by ringerc** [comment]
The source packaging info is in https://github.com/2ndQuadrant/bdr-packaging/tree/debian/bdr .

There appears to have been an oversight when preparing 0.9.3. We focus heavily on the RPMs as that's what our customers use, but the debs should've been uploaded. I should be able to push new ones when we do a release on an updated base PostgreSQL soon.

**Comment by ringerc** [comment]
I just pushed bdr-pg 9.4.6 RPMs, and the debs should be done shortly. I'll check on progress.

**Comment by ringerc** [comment]
Debs pushed.
