### ISSUE TITLE
Run pg_restore with session_replication_role = replica

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#171]
We should `pg_restore` with `session_replication_role = 'replica'` and/or triggers disabled, and run our apply workers with `session_replication_role = 'replica'` too. This won't be as good as pglogical, but will be an improvement on our current FK-handling situation.

The docs will need to be updated to note that FKs can be violated at least transiently by conflicts and replication anomalies.

**Comment by PJMODOS** [comment]
Fixed by e76b7535565243a0fe27e2580e97b094957a3fdc
