### ISSUE TITLE
BDR replication recovery 

### ISSUE THREAD

**Issue by volga629** [2ndQuadrant/bdr#172]
Hello Everyone,
Looking for suggestion how to recovery after the failure of share storage.
Setup is 2 nodes bdr.

Here are the log 

http://fpaste.org/347689/93853361/

Thank you for any help.

**Comment by ringerc** [comment]
This isn't a bug report, so closing. Feel free to mail the pgsql-general mailing list for discussion, but you'll want to provide a lot more information than "after the failure of shared storage".
