### ISSUE TITLE
Default to enabling TCP keepalives on client side (or at least document recommendation)

### ISSUE THREAD

**Issue by altipeak** [2ndQuadrant/bdr#173]
If I have BDR configured between 2 nodes:
1 - I disconnect the network of the joined node
2 - Make an sql change on the node that is connected
3 - Connect the node again

Result: The changes made on step 2 are not executed on the server when got alive again. Only if I restart postgresql the data is synchronized

I'm using BDR 0.9.3

**Comment by ringerc** [comment]
On 1 April 2016 at 18:22, altipeak <notifications@github.com> wrote:

> If I have BDR configured between 2 nodes:
> 1 - I disconnect the network of the joined node
> 2 - Make an sql change on the node that is connected
> 3 - Connect the node again
>
> Result: The changes made on step 2 are not executed on the server when got
> alive again. Only if I restart postgresql the data is synchronized
>
> Check the logs on both servers to see if there's anything informative
there. That should always be your first step.

How exactly do you "disconnect" and "reconnect"?

What is the "sql change" made?

_details_ please.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by altipeak** [comment]
Hi Craig,

Thanks for your support. I'm using VirtualBox with two VMs. When I say "disconnect" and "reconnect" means to change the network configuration of the VM toggling the "cable connected" option. Same results on VMWare.

Setup:
 - Server A (who created the group) 
 - Server B (joined node)

Steps to reproduce it:
1 - "Disconnect" the network on server B by toggling the "Cable connected" option of the VirtualBox (or device status "Connected" in VMWare)
Then wait some seconds for the timeout to see the "terminating walsender process" message.

Postgres logs at server A:
_2016-04-01 10:54:40 UTC [7625-5] postgres@safewalk-server LOG:  terminating walsender process due to replication timeout_

Postgres logs at server B:
_2016-04-01 10:54:33 UTC [8200-5] postgres@safewalk-server LOG:  terminating walsender process due to replication timeout_

2 - Do an insert on a table of server A (on a table that belongs to a replica set).
3 - "re connect" the network cable on server B
4 - Check if the row was synchronised on server B (It's not being synchronised in my case)

The replication slot on node B is not active. There aren't entries on pg_stat_replication table.
# select * from pg_replication_slots;
                slot_name                | plugin | slot_type | datoid |    database     | active | xmin | catalog_xmin | restart_lsn 
-----------------------------------------+--------+-----------+--------+-----------------+--------+------+--------------+-------------
 bdr_16388_6185190932131829313_1_16388__ | bdr    | logical   |  16388 | safewalk-server | **f**      |      |         2089 | 0/85EF988
(1 row)

I did some test modifying the recovery.done file on the server B adding the following options:
_standby_mode = 'on'
primary_conninfo = 'dbname=''safewalk-server'' host=192.168.1.142 port=5432 user=postgres connect_timeout=30 keepalives_idle=5 keepalives_interval=1'
recovery_target_name = 'bdr_6257555349521950242'
recovery_target_inclusive = true_

This way seems to be working but I don't know if it works if the network is disconnected for a long time. I'm doing some tests on it.

Thanks in advance!

**Comment by altipeak** [comment]
Can be solved by changing the bdr_connections with keepalives options:
Like this:

host=192.168.1.140 port=5432 dbname=safewalk-server connect_timeout=10 keepalives_idle=5 keepalives_interval=1

I guess is not the idea, right?

**Comment by mz407f** [comment]
> host=192.168.1.140 port=5432 dbname=safewalk-server connect_timeout=10 keepalives_idle=5 keepalives_interval=1

Confused.  Are you saying that adding the above options SOLVES this issue?

**Comment by ringerc** [comment]
On 2 April 2016 at 22:42, mz407f <notifications@github.com> wrote:

> host=192.168.1.140 port=5432 dbname=safewalk-server connect_timeout=10
> keepalives_idle=5 keepalives_interval=1
>
> Confused. Are you saying that adding the above options SOLVES this issue?
>
That would make sense.

I think we need to start adding that by default to the client side of
replication connections, or at least documenting them as a strong
recommendation, because people don't tend to set up OS-level keepalives and
the OS's defaults for connection loss are a bit too permissive for most
people's needs. I've seen other issues that've been somewhat similar.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by altipeak** [comment]
Yes, seems that it solves the issue. I'll apply it manually on my current configurations.

Thanks

**Comment by mz407f** [comment]
Altipeak.  Can you explain exactly how you update your config?  I'm currently evaluating BDR and noticed this same behavior by simply doing "ifconfig eth0 down".  

The postgres config has these:

 tcp_keepalives_count           | 0 | Maximum number of TCP keepalive retransmits.
 tcp_keepalives_idle              | 0 | Time between issuing TCP keepalives.
 tcp_keepalives_interval        | 0 | Time between TCP keepalive retransmits.

Is this where you adjust?  Your previous post seemed to indicate an adjustment to the dsn lines, and your values didn't have "tcp_" tacked on.

Thanks!

**Comment by altipeak** [comment]
Hi mz407f,

You need to change the bdr connection dsn at the table bdr.bdr_connections

Example of dsn_connection field:
host=192.168.1.140 port=5432 dbname=safewalk-server connect_timeout=10 keepalives_idle=5 keepalives_interval=1

**Comment by mz407f** [comment]
So, for clarification:  Adding "connect_timeout=10 keepalives_idle=5 keepalives_interval=1" is done during:

bdr.bdr_group_create: (node_external_dsn line)
bdr.bdr_group_join: (node_external_dsn line) --and-- (join_using_dsn)

Is the above correct?   This is a big deal for us.  Our WAN connection drops frequently and the nodes must reconnect perfectly under all circumstances.

**Comment by altipeak** [comment]
Yes, you are right, you can configure it from bdr_group_create and bdr_group_join, or by updating the rows con the bdr_connections table ( in case you already have a configured schema).

Let me know if this solves your problem. We are interesting also in get a better knowledgement to get the best results.

Regards,

Alejandro

**Comment by altipeak** [comment]
Dear Craig Ringer,

We will make sure your question is answered later on today.

Regards,AltiPeak Support

---- On Wed, 6 Apr 2016 18:29:31 +0100 notifications@github.com  wrote ----
