### ISSUE TITLE
Reassign global sequences ranges

### ISSUE THREAD

**Issue by altipeak** [2ndQuadrant/bdr#175]
Hi,

I've configured 2 nodes using global sequences. One of the nodes is using the range [1-1001), etc and the other one the [5000-5001).
Is there any way to reassign the ranges? I would like to have something like [3000-3001) in the first node instead the original id seq.

Thank you!

**Comment by PJMODOS** [comment]
No there is no way to do this at the moment and we don't even have plans for supporting something like that.
