### ISSUE TITLE
Error installing UDR on Gentoo w/ PostgreSQL 9.5.2 error: too few arguments to function ‘ExecOpenIndices’

### ISSUE THREAD

**Issue by bryanconlon** [2ndQuadrant/bdr#179]
Getting error after ./config runs on gentoo version:  Linux 4.0.5-gentoo #1 SMP Tue Aug 4 13:37:39 CDT 2015 x86_64 Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz GenuineIntel GNU/Linux

2ndquadrant_bdr # PG_CONFIG=/usr/bin/pg_config ./configure
checking for a sed that does not truncate output... /bin/sed
configure: building against PostgreSQL 9.5
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for replication/replication_identifier.h... no
configure: postgres-bdr patches missing, forcing UDR build
configure: creating ./config.status
config.status: creating Makefile
config.status: creating Makefile.global
config.status: creating doc/Makefile
config.status: creating run_tests
config.status: creating bdr_config_generated.h
config.status: bdr_config_generated.h is unchanged

2ndquadrant_bdr # make
x86_64-pc-linux-gnu-gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -march=native -O2 -pipe -fpic -I/usr/include/postgresql-9.5 -I. -I./ -I/usr/include/postgresql-9.5/server -I/usr/include/postgresql-9.5/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o bdr_apply.o bdr_apply.c
bdr_apply.c: In function ‘process_remote_insert’:
bdr_apply.c:456:2: error: too few arguments to function ‘ExecOpenIndices’
  ExecOpenIndices(estate->es_result_relation_info);
  ^
In file included from /usr/include/postgresql-9.5/server/funcapi.h:21:0,
                 from bdr_apply.c:20:
/usr/include/postgresql-9.5/server/executor/executor.h:366:13: note: declared here
 extern void ExecOpenIndices(ResultRelInfo *resultRelInfo, bool speculative);
             ^
<builtin>: recipe for target 'bdr_apply.o' failed
make: *** [bdr_apply.o] Error 1

**Comment by bryanconlon** [comment]
Gentoo version:  Linux 4.0.5-gentoo #1 SMP Tue Aug 4 13:37:39 CDT 2015 x86_64 Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz GenuineIntel GNU/Linux

**Comment by PJMODOS** [comment]
Postgres 9.5 is not supported, and UDR is being deprectaed. If you want one way logical replication check pglogical - http://2ndquadrant.com/en/resources/pglogical/
