### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#183]
BDR could use a mailing list.

**Comment by PJMODOS** [comment]
+1

**Comment by ringerc** [comment]
@umairshahid we talked about this a few weeks ago, any luck?

**Comment by umairshahid** [comment]
@ringerc, as discussed on Skype, please go ahead and create a Google Group for this purpose. We discussed why forums or github's issue tracker wouldn't be of much to us. 
Once the group is created, I will add the information to BDR landing page on our website.

**Comment by ringerc** [comment]
All done
