### ISSUE TITLE
local node record not found

### ISSUE THREAD

**Issue by fluancefg** [2ndQuadrant/bdr#187]
Hi,

I've tried to setup the UDR plugin using bdr 0.9.3 and PotgreSQL 9.4.7. Then I've tried to completely remove the bdr extension as explained in issue #127 
However, I'm stucked with a background process that I can't kill and always restart with an error message:
`user=,db= ERROR:  local node record not found`

Even if I remove the extension from shared_preload_libraries, as soon as I add it again, the background process start again and the error message appears again.

**Comment by fluancefg** [comment]
Ok, I've discovered that dropping the bdr_supervisor db after removing the bdr extension does the trick.
However, I don't know if it is the right way to totaly remove the extension.
Can anyone confirm it ?

**Comment by martinmarques** [comment]
UDR is being deprecated in favor of pglogical. I suggest to take a look at the pglogical project for uni-directional replication

**Comment by mz407f** [comment]
Does this mean that 0.10.0 will have UDR removed?  Is there any target date for 0.10.0 yet?

**Comment by ringerc** [comment]
Yes, we're removing UDR from 0.10.0. Use pglogical -
https://github.com/2ndQuadrant/pglogical .

About a month or so for BDR 0.10.0, give or take depending on other time
requirements.

**Comment by jstuhli** [comment]
Is there a way to solve this and restart UDR? I've tried pglogical, but is simply doesn't work for our production database (issue has been raised).
UDR did work, but after an invalid setup for another node this happened (wrong pg_hba) , and there's no way to undo it, short of dropping the whole cluster and trying again.
