### ISSUE TITLE
BDR subscribe can't find local connection configurations

### ISSUE THREAD

**Issue by eloycoto** [2ndQuadrant/bdr#193]
Hi,

I use to work with 2 BDR servers and all works perfectly. In the last days I tried to add a read replica server but I always had problems. Before was the issue with table tuple mistmatch (#114), but nowadays I can't get it working with the last versions of the code compiled from scratch.

The query that I used to subscribe to the master nodes is:

```
SELECT bdr.bdr_subscribe(
   local_node_name := 'foehnReplica',
   subscribe_to_dsn := 'host=192.168.10.10 port=5432 dbname=foehn',
   node_local_dsn := 'host=192.168.10.20 port=5432 dbname=foehn');
)
```

The error message that I got is the following:
```
ERROR:  XX000: cannot find local BDR connection configurations
```

I log all the queries before the error, and the results are the following:
```
SELECT 1 FROM pg_proc p INNER JOIN pg_namespace n ON (p.pronamespace = n.oid) WHERE n.nspname = 'bdr' AND p.proname = 'bdr_version_num';
 ?column?
──────────
        1
(1 row)

SELECT bdr.bdr_version_num(),        bdr.bdr_variant() AS variant,        bdr.bdr_min_remote_version_num();
 bdr_version_num │ variant │ bdr_min_remote_version_num
─────────────────┼─────────┼────────────────────────────
            1000 │ BDR     │                        700
(1 row)

SELECT 1 FROM pg_proc p INNER JOIN pg_namespace n ON (p.pronamespace = n.oid) WHERE n.nspname = 'bdr' AND p.proname = 'bdr_get_local_nodeid';
 ?column?
──────────
        1
(1 row)

SELECT sysid, timeline, dboid FROM bdr.bdr_get_local_nodeid()

        sysid        │ timeline │ dboid
─────────────────────┼──────────┼───────
 6291226144277948045 │        1 │ 16386
(1 row)

```

pg_replication_slots are empty too.

In the remote nodes I didn't see any connection, so I can't log anything. Related with the remote nodes is the master version too.

Do you have any idea why this happens? Is there another way to add a read-replica to a BDR cluster? Is this a bug? 

Many thanks!

**Comment by martinmarques** [comment]
You know that the standby on a bdr environment can't be used to replace the primary it's replication from by failing over?

**Comment by eloycoto** [comment]
Hey @martinmarques 

Yes, I knew that. This replica is only to have the data in another place, make backups and run some long queries that we don't want to have in the master nodes. 

Regards.

**Comment by ringerc** [comment]
BDR is symmetric. There's no such thing as a read replica in BDR terms. You can make a regular PostgreSQL streaming physical replica though - with `recovery.conf` and streaming replication / WAL archiving.
