### ISSUE TITLE
Documentation: Explain why DDL is prohibited where it is

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#20]
In http://bdr-project.org/docs/x576.html we say some DDL is prohibited but not why. Also that some DDL is not replicated but not why.

**Comment by anarazel** [comment]
Hi,

On 2015-03-16 21:14:33 -0700, Craig Ringer wrote:
> In http://bdr-project.org/docs/x576.html we say some DDL is prohibited but not why. Also that some DDL is not replicated but not why.

I don't think user facing docs are the right place to explain that in
detail. Maybe add one comment ontop that DDL that causes a rewrite is
prohibited? Everything else (and even that) will just go over the head
of normal users.

Greetings,

Andres Freund

**Comment by ringerc** [comment]
I agree, I don't mean doing it in excessive detail, just that it's rewrites that we prevent. Done.
