### ISSUE TITLE
Test 0.9.3 to 0.10.0 upgrade process, and document it

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#214]

**Comment by umairshahid** [comment]
Guidelines from Craig: 

For each BDR node:

* Stop the server
* Install the latest bdr-pg 9.4 binaries if not already running them
* Install the 1.0 bdr extension binaries
* Start the server

There is no need to stop them all at once, you can do it piecemeal. Or should be able to if everything's OK. You cannot, however, part or join nodes between when you start the upgrade on the first node and finish it on the last node.

**Comment by amrutadeolasee** [comment]
I did a manual upgrade from version 0.9.3-2016-07-26-3fb5559 to bdr version 0.10.0-2016-07-22-72f8593.

Following steps were followed:
1. Created a bdr cluster using bdr_testcluster
2. Created a table "t1bdr", inserted some rows and confirmed that replication is working fine.
3. Stopped all the nodes.
4. Installed the 1.0 bdr extension binaries
5.  Restarted all the nodes.

Observations:
1. bdr_version changed from 0.9.x to 0.10.x

bdr version before replacing binaries
bdr_testdb=# select * from  bdr.bdr_version();
       bdr_version        
--------------------------
 0.9.3-2016-07-26-3fb5559

bdr version after changing binaries and restarting the servers
bdr_testdb=# select * from  bdr.bdr_version();
        bdr_version        
---------------------------
 0.10.0-2016-07-22-72f8593

2. Node status of all nodes is 'r'
bdr_testdb=# select * from bdr.bdr_nodes;
     node_sysid      | node_timeline | node_dboid | node_status | node_name |              node_local_dsn               |            node_init_from_dsn             | node_read_only 
---------------------+---------------+------------+-------------+-----------+-------------------------------------------+-------------------------------------------+----------------
 6311575265135391449 |             1 |      16385 | r           | nodeA     | port=5598 dbname=bdr_testdb user=postgres |                                           | f
 6311575476929038125 |             1 |      16385 | r           | nodeB     | port=5599 dbname=bdr_testdb user=postgres | port=5598 user=postgres dbname=bdr_testdb | f
 6311575562052094397 |             1 |      16385 | r           | nodeC     | port=5597 dbname=bdr_testdb user=postgres | port=5598 user=postgres dbname=bdr_testdb | f
(3 rows)

3. Tried to check replication by inserting a new row in "t1bdr". But the insert is not reflected on another node.
4. Tried to create a new table 'test'. But  the statement freezes and no table is created.

Note: I tried to install 1.0 bdr extension in two ways.
a. By stopping only 1 instance.
b. By stopping all three instances.
But the observations are similar.  

I find some unusual errors in the log file when I start the server.
2016-07-26 20:35:01 JST 25341:4 5/0:2016-07-26 20:35:01 JST bdr (6311575476929038125,1,16385,):receive: ERROR:  could not parse slot name: È^G
2016-07-26 20:35:01 JST 25341:5 5/0:2016-07-26 20:35:01 JST bdr (6311575476929038125,1,16385,):receive: CONTEXT:  slot "bdr_16385_6311575476929038125_1_16385__", output plugin "bdr"
2016-07-26 20:35:01 JST 25338:6 4/0:2016-07-26 20:35:01 JST : ERROR:  data stream ended
2016-07-26 20:35:01 JST 25262:71 :2016-07-26 20:35:01 JST : LOG:  worker process: bdr (6311575265135391449,1,16385,)->bdr (6311575562052094397,1, (PID 25338) exited with exit code 1
2016-07-26 20:35:02 JST 25341:6 5/0:2016-07-26 20:35:02 JST bdr (6311575476929038125,1,16385,):receive: DEBUG:  unexpected EOF on client connection
Attaching complete logs.

Also, for the sake of completeness, I tried to stop all the instances and restarted them *without* replacing the bdr binaries. In that case, instances start fine and replication works as expected.

[postgresql-2016-07-26_203414.log.zip](https://github.com/2ndQuadrant/bdr/files/384277/postgresql-2016-07-26_203414.log.zip)

**Comment by ringerc** [comment]
> 2016-07-26 20:35:01 JST 25341:4 5/0:2016-07-26 20:35:01 JST bdr (6311575476929038125,1,16385,):receive: ERROR: could not parse slot name: È^G
2016-07-26 20:35:01 JST 25341:5 5/0:2016-07-26 20:35:01 JST bdr 
> (6311575476929038125,1,16385,):receive: CONTEXT: slot "bdr_16385_6311575476929038125_1_16385__", output plugin "bdr"

Interesting. Note that the slot name is reported fine in the context callback, but not the parsing error.

Thanks for this, I'll look into it now since this is obviously a critical priority for 1.0. I suspect we're looking at the wrong offset somewhere due to a structural change, but need to track down exactly what and where.

Am I correct in assuming that you didn't change the underlying bdr-pg binaries, i.e. you used the same postgres for both? That's fine if so, bdr-pg hasn't changed much at all for BDR 1.0 and can be updated independently of the BDR extension.

Now I have a few extra days grace I'm going to try to update bdr-testcluster to handle this.

**Comment by ringerc** [comment]
I've updated`bdr_testcluster` to test 1.0 upgrades. Changes pushed.

It's failing with

```
2016-08-01 14:24:03 AWST 7505:8 5/1025:2016-08-01 14:24:03 AWST : ERROR:  relation "bdr.pg_temp_17021" does not exist
2016-08-01 14:24:03 AWST 7505:9 5/1025:2016-08-01 14:24:03 AWST : CONTEXT:  apply INSERT from remote relation bdr.pg_temp_17021 in commit 0/19B1D50, xid 2059 commited at 2016-08-01 14:15:59.993719+08 (action #2)
 from node (6313739696228865416,1,16385)
```

which looks like a full-table rewrite being decoded. Since we block those usually, and since the test harness in `bdr_testcluster` doesn't attempt any full table rewrites, it must be created during the run of the BDR extension upgrade scripts. Sure enough:

```
bdr_testdb=# select bdr.bdr_get_local_nodeid();
     bdr_get_local_nodeid      
-------------------------------
 (6313739607933587156,1,16385)
(1 row)

bdr_testdb=# select relname from pg_class where oid = 17021;
  relname  
-----------
 bdr_nodes
(1 row)
```

so we've got an upgrade script bug.

**Comment by ringerc** [comment]
The culprit is

```
bdr--0.10.0.2--0.10.0.3.sql:ALTER TABLE bdr.bdr_nodes ADD COLUMN node_read_only boolean DEFAULT false;
```

Pushing 1151ba9c8d38591594776ecf71c449c9c29fbfe3 with a fix.

**Comment by ringerc** [comment]
I can't reproduce the problem you report:

```
2016-07-26 20:35:01 JST 25341:4 5/0:2016-07-26 20:35:01 JST bdr (6311575476929038125,1,16385,):receive: ERROR: could not parse slot name: È^G
```

or anything like it. Does it happen when you repeat the process?

**Comment by ringerc** [comment]
Committed docs.

**Comment by ringerc** [comment]
I'd like to test upgrading under load if time permits.

@amrutadeolasee Did you get a chance to follow up on reproducing that error?

**Comment by pavanvd** [comment]
@ringerc  Amruta is on leave for medical reasons and I don't think she will have a chance to get back to work at least this week.

**Comment by ringerc** [comment]
OK, thanks for the update. Understood.

**Comment by ringerc** [comment]
I've done what I can here.

**Comment by amrutadeolasee** [comment]
Tried upgrade to 1.0 using latest repository. Upgrade and replication is working fine.
