### ISSUE TITLE
1.0 DEBs

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#218]

**Comment by ringerc** [comment]
Had TONS of problems with this, landed up with a number of fixes that required a re-wrap of bdr 1.0 to remove `bdr_resetxlog` and modify `pg_dump` based on Petr's changes to pglogical's forked dump. Mainly because Debian insists on building against latest libpq. Also other minor issues, and then had to re-wrap again for 9.4.9.

All done now.

**Comment by ArtemGr** [comment]
Tough stuff. Congratulations!

So... are they, like, published anywhere yet? Or is it too early in the loop for that kind of thing?
