### ISSUE TITLE
BDR pg_xlog grow

### ISSUE THREAD

**Issue by turtle-bazon** [2ndQuadrant/bdr#229]
I've setup BDR. And I see that my pg_xlog grow unlimited. Now I don't know how pg_xlog influence to BDR. Can I use pg_resetxlog as in generic postgresql? Can I use archive_mode? How much should I keep archive and so on. Many questions that I can't find answer in documentation.

**Comment by execut** [comment]
I also have this problem, the logs are not cleaned. I periodically delete them manually older 5 hours. Replication is working fine. My log section in postgresql.conf:
```
wal_level = logical

archive_mode = on
archive_command = '/bin/true'
archive_timeout = 3600
```

**Comment by PJMODOS** [comment]
One possibility is that you have some stray replication slot left over there which is not used any more. I would check pg_replication_slot for slots which are not active. It's also something I would highly recommend to monitor.

**Comment by execut** [comment]
Thanks for the tip
Here is out SELECT * FROM pg_stat_activities:
Primary node:
<table border="1" style="border-collapse:collapse">
<tr><th>slot_name</th><th>plugin</th><th>slot_type</th><th>datoid</th><th>database</th><th>active</th><th>xmin</th><th>catalog_xmin</th><th>restart_lsn</th></tr>
<tr><td>bdr_30123_6277350226133802171_1_25141__</td><td>bdr</td><td>logical</td><td>30123</td><td>db</td><td>true</td><td>NULL</td><td>493948005</td><td>204/D74E83D8</td></tr>
<tr><td>bdr_30123_6277350226133802171_1_21931__</td><td>bdr</td><td>logical</td><td>30123</td><td>db</td><td>false</td><td>NULL</td><td>15007</td><td>2/467106B8</td></tr></table>
Secondary node:
<table border="1" style="border-collapse:collapse">
<tr><th>slot_name</th><th>plugin</th><th>slot_type</th><th>datoid</th><th>database</th><th>active</th><th>xmin</th><th>catalog_xmin</th><th>restart_lsn</th></tr>
<tr><td>bdr_25141_6277357126223215436_1_30123__</td><td>bdr</td><td>logical</td><td>25141</td><td>db</td><td>true</td><td>NULL</td><td>493174151</td><td>116/7D239B08</td></tr></table>
I think this is unnecessary node bdr_30123_6277350226133802171_1_21931__

**Comment by turtle-bazon** [comment]
Ok. I see that one slot doesn't active. I dropped them. Waht to do next? Is pg_xlog will not grow anymore? And can I delete them safely? And how to delete?

**Comment by turtle-bazon** [comment]
bdr_part_by_node_names is detaching nodes by it's name. There is replication slot and I think you should drop it using `select pg_drop_replication_slot('bdr_30123_6277350226133802171_1_21931__')`

**Comment by turtle-bazon** [comment]
Update: after some time pg_xlog cleared and all ok now.

**Comment by execut** [comment]
I also did it and logs are now perfectly clean. Thank to all!

**Comment by turtle-bazon** [comment]
So, we can close issue as it confirmed as not bug?

**Comment by martinmarques** [comment]
Yes, this should be closed. I suggest reading about how replication slots and logical decoding work before diving deep into BDR. you would have faced the same issue if you created a replication slot for normal Stream Replication and never used it. Replication slots prevent WALs which are still needed from being recycled.

Closing now.
