### ISSUE TITLE
BDR with one node can't operate

### ISSUE THREAD

**Issue by turtle-bazon** [2ndQuadrant/bdr#230]
I've setup "testing" instance with BDR setup but with one node only. But any operations cause:

```No peer nodes or peer node count unknown, cannot acquire global lock
HINT:  BDR is probably still starting up, wait a while```

So I need to add second node. Can I do it without needing in that?

**Comment by martinmarques** [comment]
No, you need at least 2 nodes to operate in multi-master. (I'd suggest actually having at least 3 nodes to avoid problems if one of the 2 nodes fails) If you want to have only 1 node, why bother using BDR?

**Comment by turtle-bazon** [comment]
It needed for testing environment to ensure BDR restrictions while executing database migration. So, problem slightly solved at that moment creating second database on that node and configuring second "node" on that database (due to BDR has per-database replication). It seems that all works except doubling needed size, but that is less problem.

**Comment by turtle-bazon** [comment]
I think I can close issue or move it to wishlist as you decide.
