### ISSUE TITLE
walsender timeout can be triggered by long xacts

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#233]
Currently when we apply big tx's we don't send replication feedback until we replay the commit.

That can result in inappropriate walsender timeouts. On reconnect we go back to the beginning and replay the tx again, so we're sure to time out again and get stuck.

We should be sending feedback as we process the tx to tell the walsender we're alive.

Per [the pgsql-hackers discussion on stopping logical replication protocol](https://www.postgresql.org/message-id/flat/CAMsr%2BYG_sC6wzNzEOz%3DYzHaKWHWtfHZQe0UsmqbsXUUf%3DXKP_w%40mail.gmail.com#CAMsr+YG_sC6wzNzEOz=YzHaKWHWtfHZQe0UsmqbsXUUf=XKP_w@mail.gmail.com), `ProcessRepliesIfAny()` is called from
`WalSndWriteData()`, which is invoked after each output plugin callback, so the walsender should notice such keepalives even during `ReorderBufferCommit` processing.

Related to RT#44777

**Comment by ringerc** [comment]
Oops, #254 is a duplicate.

**Comment by ringerc** [comment]
Resolved by 734a00dc98c1d3a0fc4e486ee82c4b819373737e . Still need to figure out how to test it effectively.

**Comment by ringerc** [comment]
Note that `WalSndWriteData` also calls `WalSndKeepaliveIfNecessary()`, so the walsender will ask us for keepalives whenever it's also capable of processing them.

However, the keepalive request gets tacked on to the end of the buffered data and won't be seen by the client until after the current buffered data finishes sending. If it's a big row and/or slow link or intermittent packet loss, etc, that could be well beyond the default `wal_sender_timeout` of 60s.

That's not a big deal for physical replication since it just resumes sending with the last chunk of wal. But for logical replication there's possibly a big cost to restarting decoding at `restart_lsn` and catching up to the last confirmed tx, then streaming that whole tx again.

The walsender can still receive and process keepalives even if it can't ask for them, so we probably should be sending these timeouts. Annoyingly, they'll cause the walsender to queue another keepalive request each time we approach walsender timeout, and we'll get them all in a burst when we finish replay. Nothing to be done about it.

**Comment by ringerc** [comment]
I wonder if this is an issue related to commit timestamps and the fact that we don't ensure that each peer has flushed changes to all the others before joining another node. It'll be interesting to see if 2.0 fixes this; if not I'll need to dig deeper.

**Comment by ringerc** [comment]
Important mailing list thread https://www.postgresql.org/message-id/CAMsr+YE2dSfHVr7iEv1GSPZihitWX-PMkD9QALEGcTYa+sdsgg@mail.gmail.com

**Comment by ringerc** [comment]
Patch in thread https://www.postgresql.org/message-id/e082a56a-fd95-a250-3bae-0fff93832510@2ndquadrant.com

This fix is pending for pg11, as yet uncommitted.

**Comment by ringerc** [comment]
Workaround: increase `wal_sender_timeout`

**Comment by ayurkows** [comment]
We've increased wal_sender_timeout, but in the instance of a timeout still occurring, our replication slot never seems to become active again. What causes the replication slot to become active again? Based on the logs, it doesn't seem to try again. Right now we have to restart the postgres server in order to for the replication slot to become active again.

**Comment by ringerc** [comment]
The fix for this bug was committed to PostgreSQL. If you're on a recent 9.4 then you won't be hitting this bug.

https://commitfest.postgresql.org/14/1151/

It landed in 9.4.16 as commit f5c7e0cddf6a970012bf4cfd18f00174f4d585b3
