### ISSUE TITLE
How to drop replication identifier?

### ISSUE THREAD

**Issue by turtle-bazon** [2ndQuadrant/bdr#239]
Subj. I have only 4 databases and 12 replication identifier. All after parting node.

**Comment by ringerc** [comment]
On 9 September 2016 at 06:01, turtle-bazon <notifications@github.com> wrote:

> I have only 4 databases and 12 replication identifier. All after parting
> node.
>

SELECT pg_replication_identifier_drop(...)

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services
