### ISSUE TITLE
Debian packages: pgsql-common package needs our own variant

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#24]
Need to support names that aren't just X.Y major version, e.g. `9.4bdr`.

Not just `pg_wrapper` support issues, can't even build BDR package w/o this.

**Comment by ringerc** [comment]
@anarazel suggests installing as "9.4" and conflict with stock 9.4 packages

**Comment by ringerc** [comment]
Note that we have a patched pgsql-common that should flow to upstream at some point, this is an interim issue.

**Comment by PJMODOS** [comment]
Well if we do conflicting package (which we'll do) we don't need the pgsql-common patch

**Comment by ringerc** [comment]
Bumped to next, we've just gone with conflicting packages for this release.

**Comment by PJMODOS** [comment]
I think conflicting is the way to go for foreseeable future so closing.
