### ISSUE TITLE
How to correctly remove node from BDR cluster?

### ISSUE THREAD

**Issue by turtle-bazon** [2ndQuadrant/bdr#240]
When I do part_node then it detached from cluster, but bdr process on node still active and I can't drop BDR extension. In documentation I can't find answer for my question.

**Comment by ringerc** [comment]
On BDR 1.0, see remove_bdr_from_local_node() in http://bdr-project.org/docs/stable/functions-node-mgmt.html and see http://bdr-project.org/docs/stable/node-management-disabling.html .

On older versions, see issue #127
