### ISSUE TITLE
Problems recovery

### ISSUE THREAD

**Issue by juandavidgc** [2ndQuadrant/bdr#243]
Hi! I've installed a postgres bdr and I have some troubles trying to recover. In my environment I'm using docker.

First, I created the group:

SELECT bdr.bdr_group_create(local_node_name := 'node1',node_external_dsn := 'host=10.42.50.112 port=5432 dbname=my_product');

On the second node, I've joined the group:

SELECT bdr.bdr_group_join(local_node_name := 'node2',node_external_dsn := 'host=10.65.89.120 port=5432 dbname=my_product',join_using_dsn := 'host=10.42.50.112 port=5432 dbname=my_prouduct');

At the end everything is working fine. I've created a table on node1 and the table is replicated to node2. The problem I have is when one of the node goes down. The other starts to receive dml operations and everything is fine. When I start another node, the problem is replicating the data, because an error starts to appear in the log:

27/9/2016 11:15:57ERROR:  establish BDR: timeout expired
27/9/2016 11:15:57
27/9/2016 11:15:57DETAIL:  Connection string is 'replication=database fallback_application_name='bdr (6335045079190958102,1,16386,):receive' connect_timeout=30 keepalives=1 keepalives_idle=20 keepalives_interval=20 keepalives_count=5   host=10.65.89.120 port=5432 dbname=detectid'
27/9/2016 11:15:57LOG:  worker process: bdr (6335045079190958102,1,16386,)->bdr (6335045476469264407,1, (PID 168) exited with exit code 1
27/9/2016 11:16:02LOG:  starting background worker process "bdr (6335045079190958102,1,16386,)->bdr (6335045476469264407,1,"
27/9/2016 11:16:20ERROR:  establish BDR: could not connect to server: No route to host
27/9/2016 11:16:20		Is the server running on host "10.65.89.120" and accepting
27/9/2016 11:16:20		TCP/IP connections on port 5432?

For example, suppose tha the node2 goes down. I start another node, "node3" and join it to the group:

SELECT bdr.bdr_group_join(local_node_name := 'node3',node_external_dsn := 'host=10.29.35.99 port=5432 dbname=my_product',join_using_dsn := 'host=10.42.50.112 port=5432 dbname=my_prouduct');

Now, node1 and node3 are seeking node2, but node2 does not respond. In the logs of node1 and node3 you can see:

27/9/2016 11:15:57ERROR:  establish BDR: timeout expired
27/9/2016 11:15:57
27/9/2016 11:15:57DETAIL:  Connection string is 'replication=database fallback_application_name='bdr (6335045079190958102,1,16386,):receive' connect_timeout=30 keepalives=1 keepalives_idle=20 keepalives_interval=20 keepalives_count=5   host=10.65.89.120 port=5432 dbname=detectid'
27/9/2016 11:15:57LOG:  worker process: bdr (6335045079190958102,1,16386,)->bdr (6335045476469264407,1, (PID 168) exited with exit code 1
27/9/2016 11:16:02LOG:  starting background worker process "bdr (6335045079190958102,1,16386,)->bdr (6335045476469264407,1,"
27/9/2016 11:16:20ERROR:  establish BDR: could not connect to server: No route to host
27/9/2016 11:16:20		Is the server running on host "10.65.89.120" and accepting
27/9/2016 11:16:20		TCP/IP connections on port 5432?

And if you insert data on node1 or node3, that data is not replicating anymore. 

In the Dockerfile I've installed these:

postgresql-bdr-client-9.4
postgresql-bdr-9.4
postgresql-bdr-contrib-9.4
postgresql-bdr-9.4-bdr-plugin

And I'm using debian:jessie in the latest version.

Could anybody help me with that? thank you!!

**Comment by ringerc** [comment]
Hi

We're trying to point general Q&A, rather than bug reports, at the mailing list to keep this issue tracker clearer. See bdr-list@2ndquadrant.com or https://groups.google.com/a/2ndquadrant.com/forum/#!forum/bdr-list .

Note that due to increasing adoption time for general Q&A is limited since we have to focus first on active support and consulting customer needs and future development.
