### ISSUE TITLE
RPMs for 0.9.0

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#25]
Need to build and test the 0.9.0 RPMs

**Comment by ringerc** [comment]
I've tagged 0.9.0 and uploaded the signed tarballs. Working on the RPMs.

**Comment by ringerc** [comment]
Tagged the packaging repo release `BDR_REL_0.9.0_1`

**Comment by PJMODOS** [comment]
Craig built the RPMs so closing.

**Comment by ringerc** [comment]
Released.
