### ISSUE TITLE
BDR node stuck in initializing state

### ISSUE THREAD

**Issue by r0fls** [2ndQuadrant/bdr#253]
I'm using postrgresql 9.4 and after following the instructions here:
http://bdr-project.org/docs/stable/quickstart.html

I'm left with one node stuck in initializing state for over a day now. The message I get when trying to use BDR is:

```
dbname=# create table test (age integer);
ERROR:  No peer nodes or peer node count unknown, cannot acquire global lock
HINT:  BDR is probably still starting up, wait a while
```

How can I troubleshoot this? Am I using the correct documentation? Other places discourage using `initdb` directly but this guide uses it, so I'm curious if there is a more up to date version of the documentation or if that's just a result of conflicting viewpoints on the subject.

**Comment by ringerc** [comment]
Please use the BDR mailing list bdr-list@2ndquadrant.com or its web gateway
https://groups.google.com/a/2ndquadrant.com/forum/#!forum/bdr-list for
general support questions. This tracker should be used for bug reports,
which should always include:

- Exact BDR version
- Log output
- Steps to reproduce
- A test script or test case if possible
​
