### ISSUE TITLE
Alter table hangs

### ISSUE THREAD

**Issue by turtle-bazon** [2ndQuadrant/bdr#261]
3 node bdr setup. All working fine. But when need to upgrade database structure in hangs on simple table. In logs nothing special. And I don't know where to see.

**Comment by ringerc** [comment]
This is not a complete bug report. 

Please see what I wrote on your last one for how to file useful bug reports.

If you have general questions you can write to the bdr-list@2ndquadrant.com mailing list. This tracker is for bugs.

**Comment by ringerc** [comment]
In this case you should start by enabling DDL lock tracing. See what's happening.
