### ISSUE TITLE
After removing BDR from local database, BDR worker keeps being restarted

### ISSUE THREAD

**Issue by bneumeier** [2ndQuadrant/bdr#263]
Using PostgreSQL-BDR from bdr-pg/REL9_4_STABLE as of 2016-10-14, and the BDR plugin from dr-plugin/next as of 2016-10-18 (I forgot to record the specific commits, sorry):

In a simple two-node BDR group, with nodes node1 and node2, I:
- on node1, run select bdr.bdr_part_by_node_names(ARRAY['node2']);
- on node2, run select bdr.remove_bdr_from_local_node();

From that point on, on node2: until the postgresql instance is shut down and restarted, the BDR worker process exits with code 1 and is restarted five seconds later. This continues even after dropping the BDR extension from node2.

It seems as though it would be preferable to remove all artifacts related to BDR from the database instance.

**Comment by ringerc** [comment]
That's why there's a `bdr.bdr.remove_bdr_from_local_node(...)` function in BDR 1.0.

We can't do it as part of the part operation its self for a variety of reasons.

Thanks for including the exact commands run. I'd prefer if in future you provide exact BDR version, relevant logs, etc too for bug reports. General questions (non-bug-reports) should go to the BDR mailing list.

**Comment by ringerc** [comment]
That's why there's a bdr.bdr.remove_bdr_from_local_node(...) function in
BDR 1.0.

We can't do it as part of the part operation its self for a variety of
reasons.

Thanks for including the exact commands run. I'd prefer if in future you
provide exact BDR version, relevant logs, etc too for bug reports. General
questions (non-bug-reports) should go to the BDR mailing list.

**Comment by bneumeier** [comment]
I am still perplexed that bdr.remove_bdr_from_local_node doesn't stop the bdr worker process from being started every 5 seconds on the node where it is run. Let me reproduce real quick and provide the additional context -- sorry I didn't include it previously.

This is PostgreSQL built from git a831a7304372b71d9492a5, and BDR built from git ead4f3644234c55ef6cfb31fae.

- Created new empty database "test263" on two servers
- Set up BDR between the databases, with node names "node1" and "node2"
- Verified replication is working properly in both directions
- on node1, ran: `select bdr.bdr_part_by_node_names(ARRAY['node2']);` resulting in log snippet attached as node1.txt
- at this point, node2 starts complaining "FATAL:  could not send replication command "START_REPLICATION SLOT..." every 5 seconds, as BDR worker process repeatedly exits with code 1
- on node2, ran: `select  bdr.remove_bdr_from_local_node();`
- at this point, the log message on node2 changes to "Failed to find expected bdr.connections row..." and BDR worker process continues to be started every 5 seconds and then exit with code 1. 
- on node2, ran: `drop extension bdr;`
- at this point, the log message on node2 changes to "ERROR:  bdr extension is not installed in the current database" and the BDR worker process continues to be started every 5 seconds and then exit with code 1.
- on node2, stop and restart postgres
- at this point, the BDR worker process is no longer launched every 5 seconds so the problem appears resolved. (Log file from node2 is attached as node2.txt)

To me this does seem like a bug, because after completely expunging BDR from a database, there is still *something* that is continues to re-start the BDR worker process for that database.

[node1.txt](https://github.com/2ndQuadrant/bdr/files/556440/node1.txt)
[node2.txt](https://github.com/2ndQuadrant/bdr/files/556439/node2.txt)

**Comment by ringerc** [comment]
On 28 October 2016 at 00:28, Brett Neumeier <notifications@github.com>
wrote:

> I am still perplexed that bdr.remove_bdr_from_local_node doesn't stop the
> bdr worker process from being started every 5 seconds on the node where it
> is run. Let me reproduce real quick and provide the additional context --
> sorry I didn't include it previously.
>

Thanks.


>
>    - on node1, ran: select bdr.bdr_part_by_node_names(ARRAY['node2']);
>    resulting in log snippet attached as node1.txt
>    - at this point, node2 starts complaining "FATAL: could not send
>    replication command "START_REPLICATION SLOT..." every 5 seconds, as BDR
>    worker process repeatedly exits with code 1
>
>
This much is currently expected. The part process isn't multi-phase, it
just cuts the parted peer off. It may or may not get the message that it's
been parted, depending on timing specifics.

I'm working on improving that for the coming version, but for now that much
is expeted.

>
>    - on node2, ran: select bdr.remove_bdr_from_local_node();
>    - at this point, the log message on node2 changes to "Failed to find
>    expected bdr.connections row..." and BDR worker process continues to be
>    started every 5 seconds and then exit with code 1.
>
> That's interesting. I think that in bdr_apply_main()  we should be testing
status == '\0' as well as the current test for status == 'k', so we exit
and unregister if all the node config has been purged completely.

I'll push a patch to try in a few.

> To me this does seem like a bug, because after completely expunging BDR
> from a database, there is still *something* that is continues to re-start
> the BDR worker process for that database.
>

I agree.


-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment]
Candidate fix pushed to bdr-plugin/next, please have a go. Didn't try to write a test for it, since on 9.4 we don't have usable TAP tests.
