### ISSUE TITLE
Installing dev for pg 9.6

### ISSUE THREAD

**Issue by indreek** [2ndQuadrant/bdr#264]
Hi

im getting error error:

:~/dev-bdr96$ make -j4 -s all
Building against PostgreSQL 9.6
bdr_apply.c: In function ‘process_remote_commit’:
bdr_apply.c:379:15: error: variable ‘committime’ set but not used [-Werror=unused-but-set-variable]
  TimestampTz  committime;
               ^
bdr_apply.c:378:14: error: variable ‘commit_lsn’ set but not used [-Werror=unused-but-set-variable]
  XLogRecPtr  commit_lsn;
              ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'bdr_apply.o' failed
make: *** [bdr_apply.o] Error 1
make: *** Waiting for unfinished jobs....

what could be wrong? 

I have installed postgresql-9.6, postgresql-server-dev-9.6, build-essnetial.

Thanks,
Indrek

**Comment by ringerc** [comment]
Thanks for the reports. That must be related to building without `--enable-cassert`. I'll take a look and push a patch.

If you can't fix this yourself, though, you shouldn't be using 9.6 yet. It's a developer preview at best. Please use the stable release.

**Comment by ringerc** [comment]
These specific warnings fixed by 77ab6111a622374cae67151112d92b1f92d2537d . There may be more. Build PostgreSQL with `--enable-cassert`, add appropriate `PG_USED_FOR_ASSERTS_ONLY` (and send me a patch), or remove `-Werror`.

**Comment by indreek** [comment]
Hi

Thanks. I'm not using in production. I'm just testing it (at moment) :)

Indrek

**Comment by indreek** [comment]
./configure --enable-cassert

gives error: configure: WARNING: unrecognized options: --enable-cassert

**Comment by martinmarques** [comment]
@ringerc said to build *postgres* with --enable-cassert. The bdr plugin doesn't have such flag in the configure script

**Comment by ringerc** [comment]
Yep. And really, if you're not comfortable at the C code level, you should
be using bdr-pg/REL9_4_STABLE and  bdr-plugin/REL1_0_STABLE, i.e. the
released versions.​
