### ISSUE TITLE
Altering with default value causes error

### ISSUE THREAD

**Issue by jasonvillalon** [2ndQuadrant/bdr#265]
Hi when executing 
STATEMENT:  
```
ALTER TABLE "tablename" 
	  ADD "fieldname" boolean DEFAULT false;
```

`ERROR:  ALTER TABLE ... ADD COLUMN ... DEFAULT may only affect UNLOGGED or TEMPORARY tables when BDR is active; tablename is a regular table`

but when executing code below it works:

```
ALTER TABLE "tablename" 
  ADD "fieldname" boolean;
```

I spent my whole day figuring that out. any idea why?

**Comment by martinmarques** [comment]
This is a documented behaviour.

http://bdr-project.org/docs/stable/ddl-replication-statements.html#DDL-REPLICATION-RESTRICTED-COMMANDS

Basically, and DDL that performs a full table rewrite will be prohibited as a global lock will be held for the duration of the DDL on each node (which may take a long time for big tables).

Adding a column with no default value doesn't do a full table rewrite.

**Comment by ringerc** [comment]
That's not the only reason we prohibit this operation.

We can't tell if the default expression will have the same results on each node. So it might cause rows to differ on nodes, resulting in later conflicts.

Add the column without a default, then add the default in a separate ALTER, and use `UPDATE` to set the value for existing rows.
