### ISSUE TITLE
Necessary permissions on bdr.bdr_conflict_handlers not granted automatically

### ISSUE THREAD

**Issue by bneumeier** [2ndQuadrant/bdr#267]
With PostgreSQL built from git a831a73, and BDR built from git ead4f36, replication has been observed to break arbitrarily after running fine for some time (usually days).

Log messages indicate the issue is with permissions on `bdr.bdr_conflict_handlers`:

> 2016-10-30 02:31:17.001717500  LOG:  starting background worker process "bdr (6327299559032024525,1,17613,)->bdr (632320401233966418
> 9,1,"
> 2016-11-01 14:38:08.467930500  ERROR:  permission denied for relation bdr_conflict_handlers
> 2016-11-01 14:38:08.467942500  CONTEXT:  SQL statement "SELECT ch_fun::regprocedure, ch_type::text ch_type, ch_timeframe FROM bdr.bdr_conflict_handlers   WHERE ch_reloid = $1 ORDER BY ch_type, ch_name"
> 2016-11-01 14:38:08.467944500   apply UPDATE from remote relation public.users in commit 0/8C3B478, xid 9897 commited at 2016-11-01 09:38:08.318049-05 (action #3) from node (6323204010697114938,1,17578)
> 2016-11-01 14:38:08.468861500  LOG:  worker process: bdr (6327299559032024525,1,17613,)->bdr (6323204010697114938,1, (PID 14489) exited with exit code 1

We've been able to correct the situation by granting select on bdr.bdr_conflict_handlers to the application user that performed the change, and granting that permission to public is an easy workaround, so this is not really a critical issue; but it seems as though others are likely to run into it as well.

**Comment by ringerc** [comment]
Good catch. Thanks. I'll prep a fix to bdr-plugin/next and bdr-plugin/REL9_4_STABLE soon. It just missed the 1.0.2 release though.

**Comment by ringerc** [comment]
I think the issue here is that we don't record the perpetrator when we queue conflic thandler changes for replication.

**Comment by ABeard89** [comment]
I've hit this issue, as well. Do we know when this fix will be released?

To work around it, I granted select permissions on `bdr.bdr_conflict_handlers` to the user, as suggested. But then, Doctrine DBAL pulls this table into its schema and chokes on a `name` data type, which it can't internally map.

As a result, I currently have to manually grant access for BDR to sync, and then revoke to let Doctrine continue. I have to do this every time, and it's slowing down my development quite a bit.

**Comment by ringerc** [comment]
@ABeard89 Most ORMs will require some adaptation for use with BDR. Surely it offers a way to blacklist tables/schemas?

I'd welcome a patch for the original issue. I thought I'd queued a fix, but I don't see anything obvious in the commit logs, and I don't expect to find time soon unless it's flagged as a priority by a support customer.

The simplest fix is probably to avoid the SPI and do low level heap access when reading bdr.bdr_conflict_handlers, so we don't have to worry about permissions checks and can continue to execute work as the apply role.

**Comment by ABeard89** [comment]
The internals of Postgres are black box of magic to me, so all I can do is hope for a fix.

In the meantime, I can try to Google Doctrine's blacklisting to try to educate myself on this. Maybe I can figure out a workaround.

Thanks again, Craig. Cheers!

**Comment by mnencia** [comment]
fixed by f9a7982

**Comment by rvanlaar** [comment]
I'm running BDR 1.0.7 and running into the same conflict.

d= p=1018 a=LOG:  00000: starting background worker process "bdr (6588584330094905218,1,16385,)->bdr (6588584333063829653,1,"
d= p=1018 a=LOCATION:  do_start_bgworker, postmaster.c:5644
d=eduworld p=32108 a=[unknown] NOTICE:  00000: version "1.0" of extension "btree_gist" is already installed
d=eduworld p=32108 a=[unknown] LOCATION:  ExecAlterExtensionStmt, extension.c:2703
d=eduworld p=32108 a=[unknown] NOTICE:  00000: version "1.0.7.0" of extension "bdr" is already installed
d=eduworld p=32108 a=[unknown] LOCATION:  ExecAlterExtensionStmt, extension.c:2703
d=eduworld p=32108 a=bdr (6588584330094905218,1,16385,): apply DEBUG:  00000: found valid replication identifier 1
d=eduworld p=32108 a=bdr (6588584330094905218,1,16385,): apply LOCATION:  bdr_establish_connection_and_slot, bdr.c:611
d=eduworld p=32108 a=bdr (6588584330094905218,1,16385,): apply INFO:  00000: starting up replication from 1 at 2/34330D20
d=eduworld p=32108 a=bdr (6588584330094905218,1,16385,): apply LOCATION:  bdr_apply_main, bdr_apply.c:2988
d=eduworld p=32108 a=bdr (6588584330094905218,1,16385,): apply ERROR:  42501: permission denied for relation bdr_conflict_handlers
d=eduworld p=32108 a=bdr (6588584330094905218,1,16385,): apply CONTEXT:  SQL statement "SELECT ch_fun::regprocedure, ch_type::text ch_type, ch_timeframe FROM bdr.bdr_conflict_handlers   WHERE ch_reloid = $1 ORDER BY ch_type, ch_name"
	apply UPDATE from remote relation public.MYTABLE in commit 2/347D7FD8, xid 4283299 commited at 2019-12-28 22:31:36.718883+00 (action #4) from node (6588584333063829653,1,16385)
d=eduworld p=32108 a=bdr (6588584330094905218,1,16385,): apply LOCATION:  aclcheck_error, aclchk.c:3356
d= p=1018 a=LOG:  00000: worker process: bdr (6588584330094905218,1,16385,)->bdr (6588584333063829653,1, (PID 32108) exited with exit code 1
d= p=1018 a=LOCATION:  LogChildExit, postmaster.c:3511

**Comment by rvanlaar** [comment]
Is was solved with:

`GRANT SELECT ON bdr.bdr_conflict_handlers TO <USER>`
