### ISSUE TITLE
postgresql 9.6?

### ISSUE THREAD

**Issue by madovsky** [2ndQuadrant/bdr#278]
Is BDR for pgsql 9.6 as an extension is coming or pglogical will replace it?
thanks

**Comment by umairshahid** [comment]
Please use the BDR mailing list bdr-list@2ndQuadrant.com for queries.

**Comment by ringerc** [comment]
For anyone else who finds this, the answer is that there will be a BDR
extension that supports PostgreSQL 9.6, pglogical does not replace it. More
will be announced when it's ready.​

**Comment by madovsky** [comment]
ok thanks for the info

**Comment by scherrey** [comment]
Any updates on this? We've got a system that we'd like to apply bdr to but
would prefer to be running 9.6+ rather than 9.4 if possible.

thanx,

  -- Ben Scherrey

**Comment by ringerc** [comment]
On 24 March 2017 at 15:18, Ben Scherrey <notifications@github.com> wrote:

> Any updates on this? We've got a system that we'd like to apply bdr to but
> would prefer to be running 9.6+ rather than 9.4 if possible.


Early access is available to 2ndQuadrant support customers. Contact
info@2ndquadrant.com if you're interested. Planned release is 2nd half of
2017.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by Kusmarius** [comment]
"Planned release is 2nd half of 2017"
Any updates on this?
