### ISSUE TITLE
bdr.remove_bdr_from_local_node fails if Barman replication slot is present

### ISSUE THREAD

**Issue by gbroccolo** [2ndQuadrant/bdr#281]
(thanks to Carl Clemens that helped to find the issue)

Hi,

The following error is obtained when bdr.remove_bdr_from_local_node is executed on a node that has also the replication slot used by pgbarman for WAL archiving:

-----
select bdr.remove_bdr_from_local_node(true, false);
NOTICE: removing BDR from node
NOTICE: global sequences not converted to local; they will not work until a new nodegroup is created

ERROR: could not parse slot name: barman
CONTEXT: SQL statement "SELECT pg_drop_replication_slot(slot_name)
FROM pg_catalog.pg_replication_slots,
bdr.bdr_parse_slot_name(slot_name) ps
WHERE ps.local_dboid = (select oid from pg_database where datname = current_database())"
PL/pgSQL function bdr.remove_bdr_from_local_node(boolean,boolean) line 107 at PERFORM
-----

The issue could be solved modifying bdr--0.10.0.10--0.10.0.11.sql, adding "AND slot_name like 'bdr_%' and plugin = 'bdr'" in the filter condition of the above query.

The following patch could solve the issue:

--- a/bdr-1.0.2/extsql/bdr--0.10.0.10--0.10.0.11.sql 2016-11-01 06:05:01.000000000 +0000
+++ b/bdr-1.0.2/extsql/bdr--0.10.0.10--0.10.0.11.sql 2017-02-22 20:30:08.324381081 +0000
@@ -295,7 +295,8 @@
PERFORM pg_drop_replication_slot(slot_name)
FROM pg_catalog.pg_replication_slots,
bdr.bdr_parse_slot_name(slot_name) ps
- WHERE ps.local_dboid = (select oid from pg_database where datname = current_database());
+ WHERE ps.local_dboid = (select oid from pg_database where datname = current_database())
+ AND slot_name like 'bdr_%' and plugin = 'bdr';

-- and replication identifiers
PERFORM pg_replication_identifier_drop(riname)

**Comment by ringerc** [comment]
​Thanks, fixed in 2.0 and the 1.0 stable branch.

**Comment by alessandroG77** [comment]
Hello to all,
i need to configure barman for two/3 bdr nodes.

Which wal attribute can i set?

Archive, Logical or wahtr else?

Thanks.

**Comment by ringerc** [comment]
@alessandroG77 I deleted your comment because this is not a general Q&A forum. You can ask on the bdr mailing list if you like. This issue tracker is for bugs and open work items, not general questions.

**Comment by alessandroG77** [comment]
I' ve just asked to bdr mailing list, Barman mailing list.
No response from weeks.

This is really annoying and fustrant.

Now, i try to open a question on your mailining list bdr channel.

Thnks,
Alessandro.

**Comment by ringerc** [comment]
@alessandroG77 I didn't see it on the BDR mailing list and I do try to keep an eye on it. Though support customers get priority and I can't guarantee responses to every question. Anyway, as I said, this issue tracker is not a general Q&A forum, please don't use it as one.

**Comment by ringerc** [comment]
@alessandroG77  The only mailing list post I could find from you did get a reply, a correct one. I also note you're using BDR in production. That's why we have production 24x7 support services. BDR development has to be funded somehow, and a free open source product doesn't come with free tech support. Please consider subscribing to the support service.

I will not respond to further messages here.

**Comment by alessandroG77** [comment]
Thanks a lot, Craig,
i've opened an info on your mailing list.

Thanks a lot.
