### ISSUE TITLE
setval() fix breaks cassert builds

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#283]
@ibarwick  Pull #282  breaks the regression tests for cassert builds:

         sequence                 ... FAILED (test process exited with exit code 2)

with

    TRAP: FailedAssertion("!(seq->is_called == iscalled)", File: "sequence.c", Line: 690)

Please fix. You can reproduce this by passing `--enable-cassert` to `configure`, which is preferable whenever you're doing development.

**Comment by ibarwick** [comment]
Fix tested and pushed directly. Embarrassingly I managed to miss the `--enable-cassert` when building this, apologies for the hassle.

**Comment by ringerc** [comment]
Appreciated, thanks.
