### ISSUE TITLE
Replication sets: Function to change rep set of a connection

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#29]
We have functions to change replication set membership of tables, but not of connections. Users must update `bdr.bdr_connections` and then restart the apply workers. Add functions to do this.

**Comment by ringerc** [comment]
Related: #26

**Comment by mz407f** [comment]
I am currently working on how to update a replication set configuration.

Is this the correct procedure to update a replication set?

1) Update "bdr.bdr_connections.conn_replication_sets" on all BDR machines
2) Perform "SELECT bdr.bdr_connections_changed();" on all BDR machines

Is the above SELECT a "restart", or do I need to restart postgres?  Also, is the order important?  Can I perform #1, followed by #2, (on one machine), sequentially  (on all machines)?

**Comment by mz407f** [comment]
Ah... I just read that bdr.bdr_connections is replicated across the cluster, so assume I only have to update bdr.bdr_connections and "restart".

**Comment by ringerc** [comment]
Done
