### ISSUE TITLE
where is 2.0 for 9.6?

### ISSUE THREAD

**Issue by MichaelDBA** [2ndQuadrant/bdr#291]
I cannot get a link to install 2.0 for PG 9.6.

**Comment by ringerc** [comment]
BDR 2.0 is currently only available for 2ndQuadrant production support customers.

**Comment by ringerc** [comment]
@mowaiskhan Please follow up to any further questions

**Comment by sdif** [comment]
With the release of BDR v3, will the v2 be open sourced ?

**Comment by ringerc** [comment]
@umairshahid Please address this question on BDR2 release plans

@sdif I can only direct you to https://blog.2ndquadrant.com/news-and-roadmap-for-bdr-multi-master-postgresql/

**Comment by umairshahid** [comment]
@sdif there are no current plans to open source v2.
