### ISSUE TITLE
Backing up and restoring database in Postgresql-bdr

### ISSUE THREAD

**Issue by hvorya** [2ndQuadrant/bdr#296]
Hi,

I have set up two nodes in bdr and now I want to back up my database and restore it in new cluster. Any help would be appreciated.

**Comment by ringerc** [comment]
This is an issue tracker. Please use the mailing list for Q&A.

**Comment by ringerc** [comment]
https://groups.google.com/a/2ndquadrant.com/forum/#!forum/bdr-list
