### ISSUE TITLE
Cloning fails during group join

### ISSUE THREAD

**Issue by ayurkows** [2ndQuadrant/bdr#298]
I've tried twice to do a group join on a new node, but each time it has failed with the below output, then asks to remove all identifiers and try again. Any pointers what's going wrong?

```
2017-12-15 23:49:59 UTC [3427-1] user@db ERROR:  missing data for column "search_path"
2017-12-15 23:49:59 UTC [3427-2] user@db CONTEXT:  COPY bdr_queued_commands, line 1: "0/17E8000   2017-07-29 06:24:24.182106+00   postgres    C         REATE EXTENSION CREATE EXTENSION  bdr SCHEMA pg_ca..."
2017-12-15 23:49:59 UTC [3427-3] user@db STATEMENT:  COPY bdr_queued_commands  FROM stdin;

pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 2841; 0 17037 TABLE DATA bdr_queued_commands postgres
pg_restore: [archiver (db)] COPY failed for table "bdr_queued_commands": ERROR:  missing data for column "search_path"
CONTEXT:  COPY bdr_queued_commands, line 1: "0/17E8000  2017-07-29 06:24:24.182106+00   postgres        CREATE EXTENSION        CREATE EXTENSION  bdr SCHEMA          pg_ca..."
```

**Comment by ayurkows** [comment]
Any ideas on this or any more logs that might help track down the cause?

**Comment by ayurkows** [comment]
@2ndquadrant-ci any idea on what the issue might be here or how to resolve this?

**Comment by ringerc** [comment]
You're joining 1.0 to 0.9.2 I think. Update to 0.9.3 first. Not 100% sure.

**Comment by ayurkows** [comment]
@ringerc I'm attempting to join  1.0.3-3.xenial+1 to  1.0.2-1.xenial+1

**Comment by ayurkows** [comment]
This was a version mismatch. I guess it didnt like joining 1.0.3-3 to 1.0.2-1.

Rather than upgrading we got the older package from the 2ndquadrant team + installed that. We will update in the future, but this works for now.

Ran into a separate issue afterwards that we resolved via this answer:
https://stackoverflow.com/questions/31375689/joining-postgres-bdr-node-uses-outdated-dsn
