### ISSUE TITLE
Incorrect bdr packages presented for redhat-7Server-x86_64 on repo

### ISSUE THREAD

**Issue by WhiteyDude** [2ndQuadrant/bdr#303]
Apologies if this is the wrong place to put this.

My architecture is rhel7-server, which means the baseurl for the repo is:

`http://packages.2ndquadrant.com/postgresql-bdr94-2ndquadrant/yum/redhat-7Server-x86_64/repoview/`

The packages here appear to be `pglogical` instead of `bdr`.

For comparison, the correct packages are at `http://packages.2ndquadrant.com/postgresql-bdr94-2ndquadrant/yum/redhat-7-x86_64/repoview/`.

I can confirm that manually modifying my repo file to point to the latter allows me to install packages normally.

Thanks!

**Comment by ringerc** [comment]
This was resolved by later mailing list discussion. Please reopen if I'm mistaken.
