### ISSUE TITLE
Global sequence is not initialized yet at single node setup

### ISSUE THREAD

**Issue by Regressor** [2ndQuadrant/bdr#308]
Hi. We are testing bdr with django and got some strange behaviour. The plan is to up first root node, and then add new nodes into this setup.

At the beginning we have only one node, so we started postgresql, added default_sequenceam = 'bdr' info postgresql.conf and run database initialization. Then we got permanent "All nodes must agree before the sequence is usable. Try again soon." 

So bdr is not usable as single node install. Is it normal?

**Comment by rvanlaar** [comment]
Yeah,that's not supported. The minimum amount is two:

It would be good to read the whole documentation, twice:
http://bdr-project.org/docs/stable/index.html

Here is a short presentation I made:
https://rvanlaar.github.io/Django-HA-presentation/#/

And a write up of the presentation itself:
https://reinout.vanrees.org/weblog/2016/06/22/high-availability-django-cheap.html

Three more things:
- BDR is only supported till end of 2019 (No signs if there will be an available OpenSource solution after 2019)
- Backups, be prepared:  https://github.com/2ndQuadrant/bdr/issues/140
- Automatic Django migrations: Be prepared to rewrite them in SQL.

**Comment by Regressor** [comment]
About django migrations. Are you made this by hands ? We have an idea to rewrite psycopg2 to auto split forbidden requests (like alter table alter column type) into allowed (add column, set default, set new=old, set not null)

**Comment by ringerc** [comment]
This won't be fixed in 1.0. BDR2 addresses it.
