### ISSUE TITLE
BDR and postgis: global DDl lock never released

### ISSUE THREAD

**Issue by aleksandrmelnyk** [2ndQuadrant/bdr#310]
Tried to install postgis in small 3node group with `create extension postgis` as a result whole group gets locked with global DDL lock. In log files receiving nodes lotsof messages like `table public.spatial_ref_sys doesn't exist` when trying to insert. 
The only way to use postgis in a bdr group was:
```
SET SESSION bdr.skip_ddl_locking= true;
SET SESSION bdr.permit_unsafe_ddl_commands= true;
SET SESSION bdr.skip_ddl_replication= true;
create extension postgis;
```
on all nodes.
Btw, is any way to remove global DDL lock?

**Comment by martinmarques** [comment]
2018-07-26 17:42 GMT-03:00 Аleksandr Melnyk <notifications@github.com>:

> Tried to install postgis in small 3node group with create extension
> postgis as a result whole group gets locked with global DDL lock. In log
> files receiving nodes lotsof messages like table public.spatial_ref_sys
> doesn't exist when trying to insert.
> The only way to use postgis in a bdr group was:
>
> SET SESSION bdr.skip_ddl_locking= true;
> SET SESSION bdr.permit_unsafe_ddl_commands= true;
> SET SESSION bdr.skip_ddl_replication= true;
> create extension postgis;
>
>
That's basically what I would suggest. Main problem here with the "create
extension" is that there's a transaction that mixes DDL and DML.

If you know you are going to use postgis in your cluster, the best option
is to install it before you join the nodes.


> on all nodes.
>
> Btw, is any way to remove global DDL lock?
>
You will have to consume the transactions that are being blocked.

Another option would be to analyse what got broken (missing table seems to
be the issue) and create it with ddl_replication off.

But I would go for consuming all the transaction that is failing.

**Comment by aleksandrmelnyk** [comment]
thanks, that makes sense.
