### ISSUE TITLE
Replication lag issue

### ISSUE THREAD

**Issue by SoumitraBhandary** [2ndQuadrant/bdr#317]
Hi , 

I need some clarity on the below mentioned point on replication lag byte transfer process between 2 BDR nodes.

1. Both BDR nodes are active and BDR is working fine . 
2. Size of retain bytes is 56 Bytes (default one).
3. Stopped Postgres Service in second node .
4. Did some transaction in First node (inserted 20 Million rows into one table), which generated a replication retain bytes of 2.75 GB .
5. Started  Postgres Service in second node and replication started instantly . 
6. I checked,  it took 3 minutes time to transfer the  20 Million rows to the same table. 
7. But retained bytes took another 3 minutes to reach to the default 56 bytes again . 

My question is : Does it transfer the data blocks and wal log files separately through replication slots and due to that reason it took some more time to transfer all retain bytes and make the retain bytes to default 56 bytes ?

NB :  During this period there was no other connection and transaction was happening to the DB.

**Comment by ringerc** [comment]
Big transactions produce lots of lag with logical decoding. This is down to how logical decoding works, not BDR specifically. Don't do big transactions, split them up.
