### ISSUE TITLE
Back up and restoration of BDR enabled Postgres database 

### ISSUE THREAD

**Issue by SoumitraBhandary** [2ndQuadrant/bdr#318]
Hi , 
I am taking a pgdump of one bdr enabled database and then dropping the same DB , followed by restoration process of the same dump. But it is complaining about some BDR configuration and while restoring getting ERROR like BDR extension does not exists . 
So I used following command, which excludes BDR related configuration and takes the dump . An it restores properly while there is no BDR configuration . But , I can not find any documentation about  bdr_dump. Is it a safe utility to be used in production ? 

 :  bdr_dump -Fp -npublic dbname | perl -p -i -e "s/ USING bdr;/ USING local;/" > /opt/pgsql/bin/dbnamedump_nobdr.sql

**Comment by rvanlaar** [comment]
On 04-10-18 15:02, SoumitraBhandary wrote:
>
> Hi ,
> I am taking a pgdump of one bdr enabled database and then dropping the 
> same DB , followed by restoration process of the same dump. But it is 
> complaining about some BDR configuration and while restoring getting 
> ERROR like BDR extension does not exists .
> So I used following command, which excludes BDR related configuration 
> and takes the dump . An it restores properly while there is no BDR 
> configuration . But , I can not find any documentation about bdr_dump. 
> Is it a safe utility to be used in production ?
>

This is a topic that comes up frequently. What you've done is a good 
first step.
More information about how to do backups and restores can be found here:
https://github.com/2ndQuadrant/bdr/issues/140
>
> : bdr_dump -Fp -npublic dbname | perl -p -i -e "s/ USING bdr;/ USING 
> local;/" > /opt/pgsql/bin/dbnamedump_nobdr.sql
>

- Roland

**Comment by SoumitraBhandary** [comment]
Thanks Roland ... 
~ Soumitra

**Comment by ringerc** [comment]
`bdr_dump` and `pg_dump` in a BDR install are the same thing. We originally patched `pg_dump` then intended to move the changes to reside only in a patched `bdr_dump`, but it never quite got done.

`bdr_dump` only contains some changes to handle legacy BDR 1.0 global sequences. There are no other differences.

Dump and restore is not as simple as it could be. It's quite tricky to properly manage dump/restore of a DB where you keep the cluster configuration in the DB itself, and where dump/restore is used for multiple different purposes. If you've ever read the `pg_dump` source code you'll know part of why it's tricky ;) .

Usually I advise people to `pg_basebackup`, start without `bdr` in `shared_preload_libraries` and drop the BDR extension. But you can indeed do a selective `pg_dump` instead.

One of the issues is `pg_dump`'s lack of an `--exclude-extension` type option. You can filter out data and schemas but not extensions.

**Comment by SoumitraBhandary** [comment]
Thanks Craig , for the update . 

I have one doubt , on the below mentioned file level back up approach . 
Two node participating in BDR are running properly in production .
I am starting the back up using pg_start_backup(label) . [bdr in shared_preload_libraries and BDR extension enabled as running BDR ]
Using pg_basebackup for backing up the file level back of data and xlog directory .
Once done pg_stop_backup . 
Can I use the same back up for PITR of any one Postgres Node or only to the node from where this back was taken? (Both the DB is in archive mode separately)
Also , I was going through BDR documentation , Logical replication cannot be used for point-in-time recovery .  If I follow the above approach , can I use BDR with PITR . Please suggest . 

Thanks , 
Soumitra

**Comment by ringerc** [comment]
> Can I use the same back up for PITR of any one Postgres Node or only to the node from where this back was taken? (Both the DB is in archive mode separately)

No. In fact you cannot PITR a node *at all* and have it rejoin the cluster. That is simply not supported, because the replication slots tracking data is not maintained. There is no simple solution to that. BDR3 now has limited PITR support but it's taken years of effort to get there.

**Comment by SoumitraBhandary** [comment]
Thanks Craig for your response
