### ISSUE TITLE
Any way to cancel queued statement?

### ISSUE THREAD

**Issue by alexsp01** [2ndQuadrant/bdr#319]
Hi all,

am lookiing for an reasonable and fast way to remove constantly failing transaction. For example, on one node I created table with
```
SET SESSION bdr.skip_ddl_locking= true;
SET SESSION bdr.permit_unsafe_ddl_commands= true;
SET SESSION bdr.skip_ddl_replication= true;
```
on other node I forgot to disable ddl replication, and terminated my console (due to closed internet connection). As a result, bdr tries to replicate create table on first node, but table  already exists there, blocking any changes to the node. 
The create statement is listed in bdr.bdr_queued_commands.
IS THERE ANY WAY TO SAFELY CANCEL/KILL/REMOVE that bdr process which tries to rceate table???
Log file of first node already grown 1gb.

The only way which worked for me:  remove bdr, recreate cluster(bdr group) again from scratch. 

Can ddl replication be cancelled globbaly and forever at least? 

thanks in advance.

**Comment by ringerc** [comment]
Once committed, it's committed. You can't cancel it.

You used an option called `bdr.permit_unsafe_ddl_commands`. What did you expect?

**Comment by ringerc** [comment]
With that said, you can stop BDR and use `pg_logical_slot_get_changes` with NULL lsn and 1 as the number of changes, plus the parameters BDR uses to connect per your log file. This will pull one transaction off the queue for the slot. The **whole transaction** is skipped and only for **the node receiving from this slot** your cluster will be in an inconsistent state. Further manual repairs are almost always required, making changes with DDL replication off, or even with data replication off, to manually restore the consistency of the system.

There's a safety-catch on this for a reason. In retrospect I wish I'd made `bdr.skip_ddl_replication` and `bdr.skip_ddl_locking` require a `bdr.i_read_the_manual = 'I_know_this_is_dangerous_if_i_do_it_wrong'` setting too...
