### ISSUE TITLE
How to get BDR3?

### ISSUE THREAD

**Issue by hom7** [2ndQuadrant/bdr#320]
How to get BDR3?

**Comment by rvanlaar** [comment]
Well, you pay. The open source commitment from 2nd quadrant regarding BDR3 has been rather quietly rescinded. 

You can get more information about BDR from 2nd quadrant itself.
https://www.2ndquadrant.com/en/resources/postgres-bdr-2ndquadrant/postgres-bdr-deployment-options/

**Comment by fertiland** [comment]
@rvanlaar, oops! is there any plan to return to open source? If no, we might try to move to other solutions.
anyway, BDR solution even on BDR1.0 seems fantastic to us.

**Comment by ringerc** [comment]
No, BDR 1.0 is not working with PostgreSQL 10, nor will it ever work with PostgreSQL 10.

BDR 2.0 works with PostgreSQL 9.6. BDR 3.0 works with PostgreSQL 10 and 11. Both are only available for 2ndQuadrant support subscribers at this time. See [this blog post](https://blog.2ndquadrant.com/news-and-roadmap-for-bdr-multi-master-postgresql/). Contact info@2ndquadrant.com if you need more details.

**Comment by ringerc** [comment]
@rvanlaar Those choices are not within my control. You're better off making noise on Twitter, reaching out at conferences, or emailing the relevant 2ndQuadrant senior people directly if you are unhappy with the way the company is communicating about its decisions and actions. I do not speak for 2ndQuadrant itself.

With that said, please consider that 2ndQuadrant does continue to put a huge effort into core PostgreSQL enhancements, maintenance and bug fixing. That includes ongoing work on logical decoding and laying the groundwork for more multimaster functionality. Also have a look at the logical replication facilities - directly based on BDR - that were added in PostgreSQL 10.

It can sometimes be a long slow and difficult process to get things merged into PostgreSQL, even small things. We'd really benefit from more help from others in the broader PostgreSQL community when it comes to enhancing the logical replication facilities so they can serve as a foundation for multi-master logical replication.

All this work also needs to be funded somehow.

Unfortunately, BDR never got any significant open source contributions. pglogical has seen a few, but not a great deal. They have a large cost in terms of issue triage and investigation and discussion time which impacts the small team who work on the core code, but they yield little benefit to the team, product, or other users. So while I don't make the choices about when and how new releases are released to the public, I do understand them.

After all, everyone asks for 9.6/10/etc support, but nobody's even started work on a patch for it...

**Comment by ROBERT-MCDOWELL** [comment]
why not to create a crowd funding? after all, to develop and debug bdr 1.0 in open source, it was requesting a lot of users to test it and help you to debug it right? the success of a program is linked to the amount of users, so if you close the door suddenly after the first version open source community won't follow for sure

**Comment by ringerc** [comment]
@ROBERT-MCDOWELL I can't engage in further discussion here. Feel free to raise a conversation on Twitter, the 2ndQuadrant blog, PostgreSQL mailing lists, etc.

**Comment by ringerc** [comment]
(After some internal discussion I can say):

2ndQuadrant puts a huge effort into core PostgreSQL enhancements, maintenance and bug fixing. That includes ongoing work on logical decoding and laying the groundwork for more multimaster functionality. Also have a look at the logical replication facilities - directly based on BDR - that were added in PostgreSQL 10. Other work is currently pending.

It can sometimes be a long slow and difficult process to get things merged into PostgreSQL, even small things. We'd really benefit from more help from others in the broader PostgreSQL community when it comes to enhancing the logical replication facilities so they can serve as a foundation for multi-master logical replication.

All this work also needs to be funded somehow.

Unfortunately, BDR never got any significant open source contributions. pglogical has seen a few, but not a great deal. They have a large cost in terms of issue triage and investigation and discussion time which impacts the small team who work on the core code.

After all, everyone asks for 9.6/10/etc support, but nobody's even started work on a patch for it...

Keep an eye on the [2ndQuadrant blog](https://blog.2ndquadrant.com/) or [twitter](https://twitter.com/2ndQuad) for ongoing news about BDR releases and plans.

cc @rvanlaar @ROBERT-MCDOWELL @fertiland

**Comment by ringerc** [comment]
@ROBERT-MCDOWELL Re crowd funding, I don't have much insight into the business and operations side with 2ndQ's logical replication products, and cannot say much about that. But my personal experience has been that crowd funding is:

(a) very expensive if you want to succeed - it takes a significant investment to get a project off the ground;
(b) generally useful for consumer products and services, as businesses are typically more risk-averse, have more rules around procurement etc, often have tighter timelines, and want more input into design and requirements.

How many businesses could you convince to drop $50,000 or $100,000 into a pot that *might* result in a change they want *sometime*?

So - from my personal perspective, and having had no discussion within the company about it, I can't see crowdfunding being useful here.

**Comment by ROBERT-MCDOWELL** [comment]
I'm sorry but your comment makes a little non sense to me. The sponsors of postgresql and 2ndquadrant is mostly big corporations, so I don't think money is a problem.
Secondly, mysql, mariadb etc offer already builtin multi masters like BDR3 for free, so the issue is somewhere else, and of couse I think open source developers know already.

**Comment by ringerc** [comment]
@ROBERT-MCDOWELL As I said, these are not decisions I make personally. But I do understand them. In any case, I'm not the one you need to convince.

**Comment by ROBERT-MCDOWELL** [comment]
My comments are not directed to you personally, but good to know your position.
