### ISSUE TITLE
BDR postgres 10

### ISSUE THREAD

**Issue by maipeng** [2ndQuadrant/bdr#321]
Hello,
is BDR 1.0.x is working with postgres 10.x ?
Thank you

**Comment by ringerc** [comment]
No, BDR 1.0 is not working with PostgreSQL 10, nor will it ever work with PostgreSQL 10.

BDR 2.0 works with PostgreSQL 9.6. BDR 3.0 works with PostgreSQL 10 and 11. Both are only available for 2ndQuadrant support subscribers at this time. See [this blog post](https://blog.2ndquadrant.com/news-and-roadmap-for-bdr-multi-master-postgresql/). Contact info@2ndquadrant.com if you need more details.
