### ISSUE TITLE
Could templates be setup?

### ISSUE THREAD

**Issue by rvanlaar** [2ndQuadrant/bdr#322]
Dear 2nd quadrant, 

Could an issue template be set up?
At least with some information regarding BDR 1.0 being only for 9.6.
That BDR 2 and 3 are available from 2ndquadrant support service. 
Those seem to be the most asked for features and questions.

An example of those type of issues would be #321 #320

**Comment by ringerc** [comment]
That seems sensible.

**Comment by ringerc** [comment]
Thanks @rvanlaar - https://github.com/2ndQuadrant/bdr/issues/new/choose
