### ISSUE TITLE
BDR APT key expired on 2019-03-23

### ISSUE THREAD

**Issue by mz4wheeler** [2ndQuadrant/bdr#324]
pub   2048R/AA7A6805 2015-03-24 [expired: 2019-03-23]
uid                  BDR Apt Signing Key for 2ndQuadrant <packagers@2ndquadrant.com>

**Comment by mz407f** [comment]
W: GPG error: http://packages.2ndquadrant.com trusty-2ndquadrant InRelease: The following signatures were invalid: KEYEXPIRED 1553321615 KEYEXPIRED 1553321615 KEYEXPIRED 1553321615

**Comment by mz407f** [comment]
It would sure be nice of 2ndquadrant fixed this expired key so everybody who uses ubuntu can perform system updates.

**Comment by martinmarques** [comment]
Those repos are depreciated and soon they will not exist anymore. Use these instead:

http://apt.2ndquadrant.com

**Comment by mz407f** [comment]
Thanks!  The script was helpful too.

curl https://dl.2ndquadrant.com/default/release/get/deb | sudo bash
