### ISSUE TITLE
Docs: replication sets

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#35]
The replication sets docs are somewhat skeletal. There aren't any examples and there isn't much explanation, but there's some info there at least.

http://bdr-project.org/docs/next/replication-sets.html

**Comment by jberkus** [comment]
If you haven't written anything for this yet, I'd be happy to.  At least, for the UDR case.

**Comment by ringerc** [comment]
Docs patches would certainly be valued, yes. I'm working on cutting 0.9.1 at the moment, plus general stabilisation work.

**Comment by jberkus** [comment]
I don't think I'll get anything in this week, I just got subscribe working (which you know).  Next week, probably.

**Comment by ringerc** [comment]
Repset docs are pretty solid now.
