### ISSUE TITLE
Swap chapter 4 and 5

### ISSUE THREAD

**Issue by martinmarques** [2ndQuadrant/bdr#38]
I think that it would be a good idea to swap chapters 4 (Node Management) and 5 (Configuration Settings).

I think it's better to give the user the prerequisites for using postgresql-bdr, and then start talking about how to initialize the first node and then join new nodes. Specially since chapter 4 already has some function calls to run, which makes it more suitable for reading once you have a configured bdr server running.

**Comment by ringerc** [comment]
Sure. That seems sensible. Please feel free to make the change, or other
appropriate ones as you see fit.

On 27 March 2015 at 18:59, Martín Marqués <notifications@github.com> wrote:

> I think that it would be a good idea to swap chapters 4 (Node Management)
> and 5 (Configuration Settings).
>
> I think it's better to give the user the prerequisites for using
> postgresql-bdr, and then start talking about how to initialize the first
> node and then join new nodes. Specially since chapter 4 already has some
> function calls to run, which makes it more suitable for reading once you
> have a configured bdr server running.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2ndQuadrant/bdr/issues/38>.
>



-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services
