### ISSUE TITLE
Test and document UDR unsubscribe

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#39]
We need to make sure UDR unsubscribe works and document it.

**Comment by keithf4** [comment]
The unsubscribe function is in the documentation,but doesn't appear to be being installed in the latest UDR version.
```
keith=# select bdr.bdr_variant();
 bdr_variant 
-------------
 UDR
(1 row)

Time: 0.520 ms
keith=# select bdr.bdr_version();
       bdr_version        
--------------------------
 0.9.0-2015-04-09-2f9a961
(1 row)

Time: 0.619 ms
keith=# \dx+ bdr
                                     Objects in extension "bdr"
                                         Object Description                                          
-----------------------------------------------------------------------------------------------------
 event trigger bdr_truncate_trigger_add
 function bdr.bdr_apply_pause()
 function bdr.bdr_apply_resume()
 function bdr.bdr_connections_changed()
 function bdr.bdr_create_conflict_handler(regclass,name,regprocedure,bdr.bdr_conflict_type)
 function bdr.bdr_create_conflict_handler(regclass,name,regprocedure,bdr.bdr_conflict_type,interval)
 function bdr.bdr_drop_conflict_handler(regclass,name)
 function bdr.bdr_format_slot_name(text,oid,oid,oid,name)
 function bdr.bdr_get_local_nodeid()
 function bdr.bdr_get_local_node_name()
 function bdr.bdr_get_remote_nodeinfo(text)
 function bdr.bdr_group_create(text,text,text,integer,text[])
 function bdr.bdr_group_join(text,text,text,text,integer,text[])
 function bdr.bdr_min_remote_version_num()
 function bdr.bdr_node_join_wait_for_ready()
 function bdr.bdr_parse_slot_name(name)
 function bdr.bdr_part_by_node_names(text[])
 function bdr.bdr_replicate_ddl_command(text)
 function bdr.bdr_replication_identifier_advance(text,pg_lsn,pg_lsn)
 function bdr.bdr_replication_identifier_create(text)
 function bdr.bdr_replication_identifier_drop(text)
 function bdr.bdr_replication_identifier_is_replaying()
 function bdr.bdr_sequencer_vote(text,oid,oid,text)
 function bdr.bdr_subscribe(text,text,text,integer,text[],bdr.bdr_sync_type)
 function bdr.bdr_test_remote_connectback(text,text)
 function bdr.bdr_test_replication_connection(text)
 function bdr.bdr_truncate_trigger_add()
 function bdr.bdr_upgrade_to_090(cstring,cstring,cstring)
 function bdr.bdr_variant()
 function bdr.bdr_version()
 function bdr.bdr_version_num()
 function bdr.internal_begin_join(text,text,text,text)
 function bdr.internal_node_join(text,oid,oid,text,integer,text[])
 function bdr.internal_update_seclabel()
 function bdr.pg_stat_get_bdr()
 function bdr.queue_truncate()
 function bdr.table_get_replication_sets(regclass)
 function bdr.table_set_replication_sets(regclass,text[])
 schema bdr
 sequence bdr.bdr_conflict_history_id_seq
 table bdr.bdr_conflict_handlers
 table bdr.bdr_conflict_history
 table bdr.bdr_connections
 table bdr.bdr_global_locks
 table bdr.bdr_nodes
 table bdr.bdr_queued_commands
 table bdr.bdr_queued_drops
 table bdr.bdr_replication_identifier
 table bdr.bdr_replication_identifier_pos
 table bdr.bdr_replication_set_config
 table bdr.bdr_sequence_elections
 table bdr.bdr_sequence_values
 table bdr.bdr_votes
 type bdr.bdr_conflict_handler_action
 type bdr.bdr_conflict_resolution
 type bdr.bdr_conflict_type
 type bdr.bdr_sync_type
 type bdr.dropped_object
 view bdr.bdr_list_conflict_handlers
 view bdr.bdr_node_slots
 view bdr.pg_stat_bdr
(61 rows)
```

**Comment by ringerc** [comment]
@keithf4  This was an oversight in the last stages of the release. It'll be sorted out by 0.9.1.

**Comment by jberkus** [comment]
why the delay in milestone?  UDR is kind of useless without unsubscribe ...

**Comment by ringerc** [comment]
The usual - it wasn't ready for 0.9.1, we had higher priorities and there's only so long that it makes sense to delay a release because there are still other things to do. 

It's possible to remove a UDR downstream, it's just a manual process at the moment. Delete the `bdr.bdr_connections` entry on the downstream, delete the `bdr.bdr_nodes` entries on both ends, clera the `bdr` security label on the downstream database, `pg_terminate_backend` the downstream's perdb worker and apply workers, drop the upstream slot, delete the downstream replication identifier.

I'd certainly welcome patches for UDR, though I don't imagine you'd want to start by tackling something like node removal.

**Comment by jberkus** [comment]
Probably not, no.  I'd have to understand way too much of how BDR/UDR works ...

**Comment by anarazel** [comment]
On 2015-05-28 19:53:26 -0700, Craig Ringer wrote:
> The usual - it wasn't ready for 0.9.1, we had higher priorities and there's only so long that it makes sense to delay a release because there are still other things to do.
>
> It's possible to remove a UDR downstream, it's just a manual process at the moment. Delete the `bdr.bdr_connections` entry on the downstream, delete the `bdr.bdr_nodes` entries on both ends, clera the `bdr` security label on the downstream database, `pg_terminate_backend` the downstream's perdb worker and apply workers, drop the upstream slot, delete the downstream replication identifier.

Actually it's easier:
SELECT bdr.bdr_part_by_node_names(ARRAY['node-standby-01']);

The only thing it doesn't - and can't reliably - is drop the upstream
slot.

**Comment by jberkus** [comment]
If it disconnects from the slot, though, that's not bad for cleanup.  Fixable with a doc patch.

Will test.

**Comment by ringerc** [comment]
It can drop the upstream slot if we make a libpq connection to the upstream in non-replication mode and drop the slot over the SQL interface.

That's probably not crucial, so you're right that a docs patch is likely sufficient.

**Comment by jberkus** [comment]
Well, let's please keep dropping the slot on the TODO list.  But we could go ahead with a bdr_unsubscribe which didn't do that and just document it for now.  However, bdr_unsubscribe should also clean up from a failed bdr_subscribe(), though.  Otherwise, there's not point in having it; just tell folks to use bdr_part_by_node_names().

**Comment by PJMODOS** [comment]
closing as UDR is deprecated in favour of pglogical

**Comment by jberkus** [comment]
Is pglogical good-to-go?  I had the impression that it was still pre-alpha.

**Comment by PJMODOS** [comment]
Well, afaik it's more stable than UDR ever was. And for example the slot dropping on unsubscribe (or drop subscription as we call it now) works fine. Does not mean it's bug free probably though.

**Comment by jberkus** [comment]
Well, the only software which is bug-free is the software where all of the lines of code have been deleted.

**Comment by ringerc** [comment]
I wouldn't call pglogical pre-alpha by any stretch.​

-hackers is making a great fuss because it's not being developed exactly
how they want it to be. The people in question are not wholly wrong either,
there are definitely problems with how it's being done. But not ones I can
control unfortunately.

Like most things I think it depends on what exactly you plan on doing with
it. It has issues in some areas, works really solidly in others. We tried,
as much as possible, to rip out the problematic parts of BDR and accept
reduced functionality, or where possible redesign them to fix issues. Some
people think that hasn't gone far enough and we should cut it down further,
others think it's already too cut down to meet their needs. So whether it's
suitable for your use is unknowable without knowing what that use is.

Stability-wise, in reality I'd say we're talking early beta level at this
point. Mostly due to rough edges and quirks rather than outright bugs, and
many of those are forced on us by Pg limitations.
