### ISSUE TITLE
Multi-user 'ALTER' test case in BDR cores

### ISSUE THREAD

**Issue by kforte90** [2ndQuadrant/bdr#49]
`ALTER TABLE` in a multi-user test causes a core.

This scenario covers two sessions to two different nodes each adding columns.

First, we attach to node 1 and add a column, then to node 2 to add a column, both with autocommit off in two sessions.  As expected, we see an error since only one DDL statement is allowed in a BDR database at a time.

But then, we try again and we get a core:

—node 1
```
begin;
alter table t1 add column c2 int;
```
    —node 2
```
   begin;
   alter table t2 add column c2 int;

   ERROR:  database is locked against ddl by another node
   HINT:  Node (6123149945090188243,1,17144) in the cluster is already performing DDL
    end;
```
— back to node 1
```
commit;
```

===========================

— run it again, it crashes

   — back to node 2:
```
    begin;
```

— back to node 1:

```
alter table t1 add column c6 int;
```
  —back to node 2:
```
  bdrdemo=# alter table t2 add column c3 int;
  server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
   The connection to the server was lost. Attempting reset: Succeeded.
```
— This is what the log says
```
d=bdrdemo p=6991 a=psql FATAL:  40001: terminating connection due to conflict with recovery
d=bdrdemo p=6991 a=psql DETAIL:  User was holding a relation lock for too long.
d=bdrdemo p=6991 a=psql HINT:  In a moment you should be able to reconnect to the database and repeat your command.
d=bdrdemo p=6991 a=psql LOCATION:  ProcessInterrupts, postgres.c:2908
d= p=6779 a=DEBUG:  00000: requesting replay confirmation from all other nodes before confirming global DDL lock granted
d= p=6779 a=LOCATION:  bdr_process_acquire_ddl_lock, bdr_locks.c:827
```

----
Can create a python test to cover this that interleaved transactions.

**Comment by anarazel** [comment]
Are you sure this actually crashed hard? And it wasn't just the session being cancelled due to the concurrent ddl lock acquisition?

**Comment by PJMODOS** [comment]
This needs to be retested with current /next branch.

**Comment by kforte90** [comment]
Not able to reproduce with newer version.  Did see same crash with older version:
--  new code, as expected:
bdrdemo=# alter table t2 add column c3 int;
ERROR:  database is locked against ddl by another node
HINT:  Node (6165907737962198687,1,16386) in the cluster is already performing DDL

--old code
alter table t2 add column c3 int;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
Closing as fixed
