### ISSUE TITLE
ALTER BDR sequence OWNED BY NONE causes cluster to block all subsequent DDL

### ISSUE THREAD

**Issue by kforte90** [2ndQuadrant/bdr#52]
Altering a BDR sequence causes cluster to block all subsequent DDL
```
CREATE SEQUENCE cust_seq USING bdr;
-- this ALTER is accepted by parser and executor
ALTER SEQUENCE cust_seq OWNED BY  none;
--  now try to create a new object, it hangs
CREATE SEQUENCE myseq1;
^CCancel request sent
```
Now, try to connect to another node and create an object:
```
 psql -p 5598 bdrdemo
CREATE SEQUENCE myseq1;
ERROR:  database is locked against ddl by another node
HINT:  Node (6132933952391508093,1,16386) in the cluster is already performing DDL
```
Originally, I was trying to ALTER my sequence since a load to a table with a sequence from two different nodes saw  'ERROR:  could not find free sequence value for global sequence'.
Should probably issue an error as with other types of 'ALTER SEQUENCE' on a BDR sequence:
' ALTER SEQUENCE is not supported when bdr is active'.
All of the DDL statements are part of new test 'bdrsanity'.  
Is there a way that the user can remove the 'block' on DDL? I tried taking the nodes down and back up but that didn't clear the database lock.

**Comment by ringerc** [comment]
Restarting the nodes should clear the DDL lock. Failure to do so is a bug.

The initial issue with `ALTER SEQUENCE` needs separate attention. I'll see what's happening there. I'm trying to work through these, though I'm going to need to rope @alvherre in to look at some of the DDL replication specific ones.
