### ISSUE TITLE
Backport 9.6 seqam to 9.4bdr

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#55]
The 9.5 sequence access method needs to be backported to 9.4bdr and BDR global sequences needs to be adapted to use it.

This will fix:

    ERROR:  could not find free sequence value for global sequence someseqname

by allowing sessions to block on acquisition of a sequence value instead of `ERROR`ing out.

**Comment by anarazel** [comment]
On 2015-04-12 23:13:44 -0700, Craig Ringer wrote:
> The 9.5 sequence access method needs to be backported to 9.4bdr and BDR global sequences needs to be adapted to use it.
> 
> This will fix:
> 
>     ERROR:  could not find free sequence value for global sequence someseqname
> 
> by allowing sessions to block on acquisition of a sequence value instead of `ERROR`ing out.

I seriously doubt that's realistic, given it completely changes the on
disk format.

**Comment by PJMODOS** [comment]
not going to happen
