### ISSUE TITLE
Backport 9.5 committs to 9.4bdr

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#56]
The 9.5 implementation of the commit timestamps API should be backported to 9.4bdr, so we can support just the one API in BDR and to bring us closer to 9.5 support.

It needs to be a partial backport that keeps the same storage format on disk as used in the 9.4 version so that we can retain compatibility with existing 9.4bdr data directories. Alternately, we may choose to reset commit timestamp information, but if we do that we need it to be consistent across all nodes, which may be harder than just keeping the on-disk format.

**Comment by PJMODOS** [comment]
Probably just the API part since the ondisk format is different.

**Comment by PJMODOS** [comment]
not gonna happen
