### ISSUE TITLE
While node is in a user-inititated paused state, you cannot shut it down gracefully

### ISSUE THREAD

**Issue by kforte90** [2ndQuadrant/bdr#58]
After pausing a node, while it is paused, you cannot shut it down gracefully.
```
 pg_ctl -D $HOME/bdrgo3 -l $HOME/bdrgo3/bdrgo_6050.log  -o "-p 6050" -w stop -m fast
waiting for server to shut down............................................................... failed
pg_ctl: server does not shut down
```
Let's look at the log:
```
cd ../bdrgo3
tail bdrgo_6050.log
d= p=39345 a=LOCATION:  LogChildExit, postmaster.c:3325
d= p=39414 a=FATAL:  57P01: terminating connection due to administrator command
d= p=39414 a=CONTEXT:  SQL statement "SELECT node_status FROM bdr.bdr_nodes WHERE node_sysid = $1 AND node_timeline = $2 AND node_dboid = $3"
d= p=39414 a=LOCATION:  ProcessInterrupts, postgres.c:2872
d= p=39345 a=LOG:  00000: worker process: bdr db: bdrdemo (PID 39414) exited with exit code 1
d= p=39345 a=LOCATION:  LogChildExit, postmaster.c:3325
d= p=39345 a=LOG:  00000: received fast shutdown request
d= p=39345 a=LOCATION:  pmdie, postmaster.c:2477
d= p=39345 a=LOG:  00000: aborting any active transactions
d= p=39345 a=LOCATION:  pmdie, postmaster.c:2503
```
The use case is that the node is paused to stop node from receiving changes.  The DBA may want to pause the node for some kind of maintenance and/or to let node catch up to current log changes.  
There is no way for the DBA to know that the node is paused since the state of paused or 'p' is not replicated to bdr.bdr_nodes.  The change could be written to the bdr.bdr_nodes table before the node is paused.
The workaround at the point where a graceful shutdown fails is to kill the postgres progress.

**Comment by ringerc** [comment]
I think the latch we wait on when paused must be failing to check for postmaster death. Clearly a bug, anyway.

To shut down in this situation, use `pg_ctl stop -m immediate`.

**Comment by ringerc** [comment]
I suspect that the immediate issue is that the `WaitLatch` call in bdr_apply.c:2387 fails to accept `WL_POSTMASTER_DEATH`. Re-testing.
