### ISSUE TITLE
Provide a function to show that node is in a 'paused' state

### ISSUE THREAD

**Issue by kforte90** [2ndQuadrant/bdr#59]
It would be a good enhancement to show whether or not a node is paused. When a node is paused, the 'bdr.bdr_nodes' table doesn't show a change in status.  Of course, when a node is paused, DDL cannot succeed since not all nodes in the cluster are up so that is one way the DBA can see evidence that the 'pause' command has taken effect.  Issue #58 is related - the node cannot be shutdown gracefully when node is paused.
Here's the command:
```
SELECT bdr.bdr_apply_pause();
```

**Comment by ringerc** [comment]
The node pause is transient; as it stands, paused is not a state that could be or should be recorded in `bdr_nodes`.

It might be interesting to do that in future. Right now pause/replaying state is in shared memory, and is cleared on restart.

We certainly need a status function to report paused/replaying status.
