### ISSUE TITLE
bdr doesn't complain when creating the bdr extension on a bdr DB

### ISSUE THREAD

**Issue by martinmarques** [2ndQuadrant/bdr#60]
If I "createdb bdr" and then login to that db and "CREATE EXTENSION bdr" (after creating the btree_gist extension) everything works with no error, it even replicates DDL and DML.

But only with the postgres user. Once you try to connect as another user you get a message 

FATAL:  too many connections for database "bdr"

This is because the bdr DB is a special DB, so it shouldn't be created/used when doing bdr.

Several things:

1) CREATE EXTENSION bdr would have given an error
2) bdr is a bad name for the pseudo-db used by bdr (maybe _bdr)
3) The error message was totally misguiding, but well, I guess it's a normal message I should have never gotten to.

**Comment by ringerc** [comment]
​As discussed on chat:

* We should use a name like `bdr_supervisor_db` for the db
* The commandfilter should check `CREATE DATABASE` even if BDR isn't
enabled in the current DB and should `ERROR` if someone tries to manually
create that DB

I don't think there's much to be done with the error, we just prevent the
issue in the first place.

**Comment by ringerc** [comment]
I've renamed the BDR supervisor DB in bdr-plugin/next and bdr-plugin/REL0_9_STABLE .

Commandfilter not done yet.

**Comment by ringerc** [comment]
Commandfilter also implemented. Closing, fixed by 3ab51d68fe75b99f4fc097527f1d4172093b025f (bdr-plugin/REL0_9_STABLE) and a67e0e033b434737b1bd219c41b7e21ca7504503 (bdr-plugin/next)

**Comment by ringerc** [comment]
Also relevant for #61

**Comment by ringerc** [comment]
97ed5f4 and ff52792 also touch this.
