### ISSUE TITLE
BDR's ON TRUNCATE triggers are dumped

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#62]
Our `ON TRUNCATE` triggers are system triggers, really, and should not be dumped by `pg_dump`.

Create them with `tgisinternal`, and in an extension upgrade script update the catalogs to mark all current ones internal.

@PJMODOS opinions?

**Comment by PJMODOS** [comment]
Sounds sane to me

**Comment by ringerc** [comment]
After internal discussion it was pointed out by @anarazel that handling truncation in the command filter isn't practical, because at command-filter time `CASCADE` handling has not yet been done. When `TRUNCATE` triggers are fired they're fired in order for `CASCADE`d `TRUNCATE`s.

What we really want, then, is IMO a way to register a global hook that's fired when a `TRUNCATE` trigger would be called, but doesn't require poking in the catalogs. We can check relpersistence and replication set membership and replicate the `TRUNCATE` then, if appropriate. This is more invasive, though, as it doesn't look like there is currently any such hook.

**Comment by anarazel** [comment]
On 2015-06-19 02:38:51 -0700, Craig Ringer wrote:
> After internal discussion it was pointed out by @anarazel that handling truncation in the command filter isn't practical, because at command-filter time `CASCADE` handling has not yet been done. When `TRUNCATE` triggers are fired they're fired in order for `CASCADE`d `TRUNCATE`s.
> 
> What we really want, then, is IMO a way to register a global hook that's fired when a `TRUNCATE` trigger would be called, but doesn't require poking in the catalogs. We can check relpersistence and replication set membership and replicate the `TRUNCATE` then, if appropriate. This is more invasive, though, as it doesn't look like there is currently any such hook.

Why not just change the trigger to be internal for now? I thought that's
what we had concluded on?

**Comment by ringerc** [comment]
​It is, and that's what I'm doing. I just noted why.

**Comment by ringerc** [comment]
Turns out there's a wrinkle in this plan. `pg_trigger` has no `PRIMARY KEY`. It has a `UNIQUE` index on `oid`, but it's not declared as a `PRIMARY KEY`. This index does not get marked as `rd_replidindex` in the index's `RelationData`. So the trigger entry can't be updated. We check for a replica identity index in `BdrExecutorStart` and fail there.

I think the best thing to do is call `CreateTrigger` rather than using the SPI to invoke `CREATE TRIGGER`. That way we can create it as internal in the first place. There's still the separate concern about replicating changes to catalog tables where there's no explicit `PRIMARY KEY`, but an equivalent index, though.

**Comment by ringerc** [comment]
Maybe it's best to create the truncate trigger on the downstream when applying `CREATE TABLE` on the downstream end, using `CreateTrigger`, and not attempt to queue a `CREATE TRIGGER` after the `CREATE TABLE` in the DDL command queue.

`pg_dump` will no longer include the create triggers since they'll be `tgisinternal` and we'll no longer be enqueueing them from `bdr_truncate_trigger_add` so there's no recursion avoidance issue.

**Comment by ringerc** [comment]
Doing that will break DDL replication from older versions, since they'll still enqueue the `CREATE TRIGGER` after the `CREATE TABLE` and it'll fail because we've just created it. That's not much of a problem IMO; we just don't do `CREATE TABLE` while we're doing an upgrade.

**Comment by ringerc** [comment]
So @PJMODOS points out in chat that we can just drop and re-create the triggers to deal with the issue of being unable to `UPDATE` them due to lack of a `pg_trigger` PK

**Comment by ringerc** [comment]
Done and merged.

Per the most recent set of commits 0c96b9ff29e4acca465cf492b5f0c01c6e789978, 0acfbaa8b1fb303683fdd2b7f1a7dea05cfb5b8e and 11c7e1827493c87640b987fd3a593cf6244878df, this:

* Creates new triggers as `tgisinternal` using a direct `CreateTrigger` call

* Creates triggers when tables are created, whether the create is done by replicated DDL, restoration of a dump, or directly. The old approach expected triggers to be dumped and to be replicated so it only created them on direct user DDL.

* Doesn't add trigger creation to the DDL replication queue because it's always done on the other end

* Updates existing triggers to tgisinternal when the 0.10.0.7 extension update script runs
