### ISSUE TITLE
table_set_replication_sets requires permit_unsafe_ddl_commands in UDR

### ISSUE THREAD

**Issue by jberkus** [2ndQuadrant/bdr#67]
Folks:

```
cio=# select bdr.table_set_replication_sets('s0.people',array['all','default','shard1']);
ERROR:  DDL commands are not allowed when UDR is active unless bdr.permit_unsafe_ddl_commands is true
CONTEXT:  SQL statement "SECURITY LABEL FOR bdr ON TABLE s0.people IS '{ "sets" : ["all","default","shard1"] }'"
PL/pgSQL function bdr.table_set_replication_sets(regclass,text[]) line 30 at EXECUTE statement
```

So either the documentation is missing some information, or this is a code bug.  Which?

**Comment by ringerc** [comment]
This is a code bug caused by making `bdr.bdr_replicate_ddl_command` respect the command filter. `bdr.table_set_replication_sets` should `SET bdr.permit_unsafe_ddl_commands` in its function declaration.

**Comment by ringerc** [comment]
I'm mostly done with this, I'm just having an exciting time getting the ddl/replication_sets suite to run on UDR.

**Comment by ringerc** [comment]
After looking into it further we're going to need separate tests for this, and in the process need to unify bdr+subscribe and UDR behaviour. So pushed as-is for now.

**Comment by jberkus** [comment]
Verified to be fixed in current HEAD.
