### ISSUE TITLE
9.4 UDR attempts to create 9.5 BDR distributed sequences, fails

### ISSUE THREAD

**Issue by jberkus** [2ndQuadrant/bdr#69]
Per Issue #68, this happened with postgresql-94-bdr:

[postgres @ cio @ 2015-05-11 21:45:07.155 GMT]:STATEMENT:  CREATE SEQUENCE "people_id_seq"
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
            USING "local";
        
It appears to me that 94-UDR is attempting to create sequences using 9.5 BDR syntax, which fails.

**Comment by jberkus** [comment]
Great!  I'll continue with bdr_subscribe testing now.  Hopefully I can get all the way ...

**Comment by jberkus** [comment]
Verified to be fixed in current HEAD.

**Comment by ringerc** [comment]
Backported to 0.9.1 too.
