### ISSUE TITLE
Switch to 9.5 function names/behaviour for commit timestamps

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#7]
Currently calling `pg_get_transaction_committime` on an xid that's unknown returns `2000-01-01 00:00:00+0`. While convenient, that's not really a true value, and for something exposed to the user we should probably return `null` (unknown) or `-infinity`.

**Comment by simonat2ndQuadrant** [comment]
Is that a bug in 9.5?

Does pg_get_transaction_committime() exist in 9.5? (Can't find it! How do I
use the feature in 9.5??)

On 17 March 2015 at 02:22, Craig Ringer <notifications@github.com> wrote:

> Currently calling pg_get_transaction_committime on an xid that's unknown
> returns 2000-01-01 00:00:00+0. While convenient, that's not really a true
> value, and for something exposed to the user we should probably return
> null (unknown) or -infinity.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2ndQuadrant/bdr/issues/7>.
>



-- 
 Simon Riggs                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, RemoteDBA, Training & Services

**Comment by ringerc** [comment]
This is about BDR, which is based on PostgreSQL 9.4. I haven't yet checked how 9.5 behaves. Let's see...

The relevant commit looks to be https://github.com/postgres/postgres/commit/73c986adde5d73a5e2555da9b5c8facedb146dcd . It changes `pg_proc.h` to add `pg_xact_commit_timestamp` and `pg_last_committed_xact`.

The implementation of `pg_xact_commit_timestamp` returns null if the ts is not found; see https://github.com/postgres/postgres/commit/73c986adde5d73a5e2555da9b5c8facedb146dcd#diff-a98cfe246f31c45932f89a47aed7aa6bR403 .

After 0.9.0 we should probably adopt the 9.5 function and semantics, leaving the old one deprecated or just removing it.

**Comment by PJMODOS** [comment]
I think we will keep current behavior on 9.4 and go with new one on later releases, no backporting
