### ISSUE TITLE
bdr.bdr_replicate_ddl_command requires fully qualified objects

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#70]
If used with non-schema-qualified objects `bdr.bdr_replicate_ddl_command(...)` will fail with

```
no schema has been selected to create in
```

Document this. Then fix it by adding a `search_path` col to the queued commands table, make `bdr_replicate_ddl_command` capture the `search_path` and set it, and make the DDL apply code `SET` the `search_path` if found in the queued object entry.

**Comment by anarazel** [comment]
I don't think that'd necessarily be a good idea. There's a fair number of ambiguities if you just copy the search path. I.e. creating an object will use the first existing schema, not the first schema. Altering a table will use the first schema something exists in, not the first schema. Etc.

**Comment by ringerc** [comment]
Good point. We can't rely on deparse in UDR though. I guess it's an issue that's going to go away, so it can just be documented and forgotten about.

**Comment by anarazel** [comment]
What do you mean with "can't rely on deparse in UDR though"? Sure, there's no deparse. That's why we force the user to be a bit more careful?

**Comment by ringerc** [comment]
Documented. Since, as you note, we can't sensibly ensure an exact behaviour match for the search path, I'm going to treat the docs update making this google-able as sufficient and close this.
