### ISSUE TITLE
Missing symbol "bdr_permit_ddl_locking" in UDR mode

### ISSUE THREAD

**Issue by 0xd01** [2ndQuadrant/bdr#71]
I fetched code from **bdr-plugin/REL0_9_STABLE** branch then built it in UDR mode (against PostgreSQL 9.4.1).

After running ```initdb ...``` and modifying config files, I tried to start database with ```pg_ctl ...``` then experienced this error:

>2015-05-25 21:28:38.784 ICT p=1336 d= u= a=FATAL:  XX000: could not load library "/usr/local/lib/postgresql/bdr.so": dlopen (/usr/local/lib/postgresql/bdr.so) failed: /usr/local/lib/postgresql/bdr.so: Undefined symbol "bdr_permit_ddl_locking"

As I investigated, I saw that you declared ```bdr_permit_ddl_locking``` in ```bdr_locks.c``` and also in ```#ifdef BUILDING_BDR...#endif```. Thus, it will not be declared in UDR mode.

I also found that you have already fixed this issue in **bdr-plugin/next** branch (commit c628558cd7fefa3ba0de02c1bee3054eaca30fca).

So, would you merge that commit into **bdr-plugin/REL0_9_STABLE** branch?

**Comment by ringerc** [comment]
Thanks for catching that. It doesn't make sense to cherry pick that commit (which really should've been two separate ones),  but I've applied the fix.

Fixed by a0ee8777810ecbc1dd3020a7774537bbf4d97352.
