### ISSUE TITLE
Slots aren't dropped as part of node part

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#73]
When a node parts in 0.9.0 the slots it held on other nodes are not dropped, and must be manually cleaned up.

**Comment by ringerc** [comment]
Fixed by 22a82daec820be04d564d5dff6d5f9a07809ab04 in bdr-plugin/next and cherry-picked to  bdr-plugin/REL0_9_STABLE as 23d6ede5851455a16ee4c22e12477027fc22c331 .

**Comment by anarazel** [comment]
Note that this, as mentioned in the commit, only works when not executed on the dropped node.
