### ISSUE TITLE
Update UDR compile instructions

### ISSUE THREAD

**Issue by jberkus** [2ndQuadrant/bdr#74]
INSTALL.src currently says:

"For UDR you may instead put the bin directory of an
unmodified PostgreSQL 9.4 on the PATH and then invoke ./configure with the
--enable-udr flag."

This is out of date.  The plugin now automatically detects if you don't have BDR capability and builds UDR instead.  There is no --enable-udr flag.

**Comment by ringerc** [comment]
It's `--enable-bdr=no` or the env var `BUILDING_UDR=1`
