### ISSUE TITLE
DDL lock problem when deleting a schema with a function

### ISSUE THREAD

**Issue by sym39** [2ndQuadrant/bdr#87]
# How to reproduce:
* 2 nodes
* create a database mydb in both nodes

## Node 1:
Start psql, then

    mydb=# CREATE SCHEMA IF NOT EXISTS test;
    mydb=# CREATE OR REPLACE FUNCTION test.nothing() RETURNS void AS $$ BEGIN END; $$ LANGUAGE plpgsql;
    CREATE FUNCTION

    mydb=# drop schema test cascade ;
    NOTICE:  drop cascades to function test.nothing()
    DROP SCHEMA

    mydb=# \dn
      List of schemas
      Name  |  Owner
    --------+----------
     bdr    | postgres
     public | postgres
    (2 rows)

## Node 2:
    mydb=# \dn
      List of schemas
      Name  |  Owner
    --------+----------
     bdr    | postgres
     public | postgres
     test   | dbadmin
    (3 rows)

    mydb=# drop schema test cascade ;
    ERROR:  database is locked against ddl by another node
    HINT:  Node (6158090345987221693,1,17189) in the cluster is already performing DDL

#Additionnal information
* After that, it is not possible anymore to do DDL operation on node1. This blocks.
* Restarting postgres on both nodes does not solve the problem

# Workaround
Remove first the function on _both_ nodes, then to remove the schema.

**Comment by PJMODOS** [comment]
This is actually not problem with DDL locks, but with replay of a DROP of function without parameter which we handled incorrectly and it was failing. This caused the lock to never be released because the transaction was never replayed.

Fixed by commit 55ee643
