### ISSUE TITLE
bdr_init_copy connects to wrong database when multiple upstream DBs are BDR-enabled

### ISSUE THREAD

**Issue by jtorral** [2ndQuadrant/bdr#88]
In the process of testing out BDR for a possible solution. I originally setup the environment on two
separate servers as per the quick start guid and used the sql commands to create groups and
add nodes. 

* originally on node 1
* created db1 and db2
* use bdr_group_create inside of db1 to create group
* use bdr_group_create inside of db2 to create group
* went to node2 and created blank db's connected to each db and joined groups from node 1

The above worked as expected

However, moving on to command line, I am running into some issues.

I am sure I am just overlooking something really simple. But, on the
node1 I created two databases and created two groups. one within
each database. No issues so far. 

I figured if these databases had valid data I would use bdr_init_copy to join node2 to node1 and copy data at the same time.

However, now on the 2nd node, I want to
add it to the cluster using bdr_init_copy. It partially works but then it
dies as you can see below. 

Just a side note. If I create only 1 db on node one and run the command it works.

```
/var/lib/pgsql/9.4-bdr/data

-bash-4.1$ rm -rf *

-bash-4.1$ bdr_init_copy -D /var/lib/pgsql/9.4-bdr/data -n node2 -d
'host=10.5.101.176 port=5432' --local-dbname='host=10.5.101.179 port=5432'

bdr_init_copy: starting ...

Getting remote server identification ...

Detected 2 BDR database(s) on remote server

Updating BDR configuration on the remote node:

 abc: validating BDR configuration ...

 abc: creating replication slot ...

 abc: creating node entry for local node ...

 xyz: validating BDR configuration ...

 xyz: creating replication slot ...

 xyz: creating node entry for local node ...

Creating base backup of the remote node...

44543/44543 kB (100%), 1/1 tablespace

Creating restore point on remote node ...

Bringing local node to the restore point ...

Transaction log reset

Initializing BDR on the local node:

 abc: adding the database to BDR cluster ...

*Could not add local node to cluster, status PGRES_FATAL_ERROR: ERROR:
getting remote node id failed*

DETAIL:  SELECT sysid, timeline, dboid FROM bdr.bdr_get_local_nodeid()
failed with: ERROR:  schema "bdr" does not exist


CONTEXT:  SQL statement "SELECT *                           FROM
bdr_get_remote_nodeinfo(node_local_dsn)"

PL/pgSQL function internal_begin_join(text,text,text,text) line 41 at SQL
statement

SQL statement "SELECT bdr.internal_begin_join(

        'bdr_group_join',

        local_node_name,

        CASE WHEN node_local_dsn IS NULL THEN node_external_dsn ELSE
node_local_dsn END,

        join_using_dsn)"

PL/pgSQL function bdr_group_join(text,text,text,text,integer,text[]) line
21 at PERFORM
```

Thanks for looking.

JT

**Comment by ringerc** [comment]
This looks closely related to http://www.postgresql.org/message-id/CACut7uQOmB7dG7P3GhCa6U7BfnrOXi5qHRrWK6O0t-wJ74OPjg@mail.gmail.com . In both cases we seem to be connecting to the wrong DB for `bdr_group_join`.

**Comment by ringerc** [comment]
@jtorral also filed the related #89

**Comment by jtorral** [comment]
Is this a bug then? Based on my connection string in the original message
both -db and --local-dbname point to different servers.  How could I then
get 2 databases replicating if this wont work?

Thanks !

JT

On Thu, Jun 18, 2015 at 8:43 PM, Craig Ringer <notifications@github.com>
wrote:

> This looks closely related to
> http://www.postgresql.org/message-id/CACut7uQOmB7dG7P3GhCa6U7BfnrOXi5qHRrWK6O0t-wJ74OPjg@mail.gmail.com
> . In both cases we seem to be connecting to the wrong DB for
> bdr_group_join.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2ndQuadrant/bdr/issues/88#issuecomment-113358200>.
>



-- 
Thanks,

Jorge Torralba
----------------------------

Note: This communication may contain privileged or other confidential
information. If you are not the intended recipient, please do not print,
copy, retransmit, disseminate or otherwise use the information. Please
indicate to the sender that you have received this email in error and
delete the copy you received. Thank You.

**Comment by ringerc** [comment]
Use `bdr_group_join` to do an SQL-level join. There does appear to be an issue here with `bdr_init_copy` support for multiple databases.

**Comment by ringerc** [comment]
I haven't tested and reproduced this yet, just tagging for work.

**Comment by ringerc** [comment]
Should be fixed by Petr's commit.
