### ISSUE TITLE
bdr_init_copy should refuse to target an active BDR datadir

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#91]
Per #89 it's possible to run bdr_init_copy against a datadir that's already an active BDR node.

We should really prevent this rather than producing a confusing error and quite likely mangling the existing BDR node.

**Comment by PJMODOS** [comment]
I think this would be as easy as checking that the systemid of the datadir is same as systemid of the remote node at the beginning.

**Comment by PJMODOS** [comment]
I think the sysid check is enough as prevention even though it does not really check for active BDR node...
