### ISSUE TITLE
bdr.bdr_part_by_node_names should delete bdr.bdr_connections entry

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#97]
We leave a dangling connections entry when removing a node. Should remove that too, and if possible the node's statistics.

We can't remove the bdr.bdr_nodes entry. Users will need to manually remove that once part has completed if they want to re-use the node name. Document this.

(This is simple, but I can't do it right now and will forget it if I don't task it. Assigning to self.)

**Comment by anarazel** [comment]
> We leave a dangling connections entry when removing a node. Should remove that too, and if possible the node's statistics.
> 
> (This is simple, but I can't do it right now and will forget it if I don't task it. Assigning to self.)

I think that's actually a good thing. We might want to add code to
overwrite those (if in the correct state), but I think it's good to
retain knowledge that a node was part of a group/subscribed and where
to. In some situation swe might actually prevent such a node from
rejoining and such.

**Comment by ringerc** [comment]
Good point as usual.​

I had some issues with a `bdr_init_copy` IIRC due to a dangling
bdr.bdr_connections entry after the bdr.bdr_nodes entry was removed (to
re-use the name). But that's where the nodes entry was removed manually, so
it's not really the same thing as here.

Documenting a safe way to re-use a node name should be sufficient.

**Comment by PJMODOS** [comment]
Or just providing cleanup function that removes the old node/connection info.
